YClops: Sensors/Camera/test.cpp File Reference
Sensors/Camera/test.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <iostream>
#include "Camera.h"
#include "opencv2/core/core.hpp"
#include "opencv2/imgproc/imgproc.hpp"
#include "opencv2/highgui/highgui.hpp"
Functions
void hasObstacles (int dimension, bool *array, Mat &image)
void distort (Mat &src)
VideoCapture startCamera ()
void getFrame (VideoCapture capture, Mat &image)
vector< Mat > convertRGBtoHSV (Mat &image)
void getWhite (Mat &image)
void insertObstacles (void *map, int size, bool *array)
void initializeArray (bool *array, int dimension)
int main (int argc, char *argv[])
Function Documentation
vector< Mat > convertRGBtoHSV (Mat & image)
Definition at line 115 of file test.cpp.
Referenced by getWhite().
void distort (Mat & src)
Definition at line 48 of file test.cpp.
void getFrame (VideoCapture capture, Mat & image)
Definition at line 105 of file test.cpp.
void getWhite (Mat & image)
Definition at line 126 of file test.cpp.
References convertRGBtoHSV().
void hasObstacles (int dimension, bool * array, Mat & image)
Definition at line 24 of file test.cpp.
void initializeArray (bool * array, int dimension)
Definition at line 195 of file test.cpp.
void insertObstacles (void * map, int size, bool * array)
Definition at line 165 of file test.cpp.
int main (int argc, char * argv[])
Definition at line 202 of file test.cpp.
References Camera::getObstacles(), Camera::loadConfig(), and Camera::startCamera().
VideoCapture startCamera ()
Definition at line 94 of file test.cpp.