YClops: YClopsConfiguration Class Reference
YClopsConfiguration Class Reference
#include <YClopsConfiguration.h>
Public Member Functions
virtual ~YClopsConfiguration ()
Static Public Member Functions
static void setConfigFile (const std::string)
static
mrpt::utils::CConfigFileBase & instance ()
static void destroyConfig ()
Protected Member Functions
YClopsConfiguration ()
Static Protected Attributes
static std::string configFileName = ""
static
mrpt::utils::CConfigFileBase * configFile = NULL
Detailed Description
Definition at line 14 of file YClopsConfiguration.h.
Constructor & Destructor Documentation
virtual YClopsConfiguration::~YClopsConfiguration () [inline, virtual]
Definition at line 16 of file YClopsConfiguration.h.
YClopsConfiguration::YClopsConfiguration () [inline, protected]
Definition at line 23 of file YClopsConfiguration.h.
Member Function Documentation
void YClopsConfiguration::destroyConfig () [static]
Definition at line 30 of file YClopsConfiguration.cpp.
References configFile.
CConfigFileBase & YClopsConfiguration::instance () [static]
Definition at line 23 of file YClopsConfiguration.cpp.
References configFile, and configFileName.
Referenced by main(), signal_handler(), and YClopsReactiveNavInterface::YClopsReactiveNavInterface().
void YClopsConfiguration::setConfigFile (const std::string fileName) [static]
Definition at line 19 of file YClopsConfiguration.cpp.
References configFileName.
Referenced by main().
Member Data Documentation
mrpt::utils::CConfigFileBase * YClopsConfiguration::configFile = NULL [static, protected]
Definition at line 22 of file YClopsConfiguration.h.
Referenced by destroyConfig(), and instance().
std::string YClopsConfiguration::configFileName = "" [static, protected]
Definition at line 21 of file YClopsConfiguration.h.
Referenced by instance(), and setConfigFile().
The documentation for this class was generated from the following files:
/home/tallred3/ecen493/SeniorProject/trunk/Code/YClopsLib/inc/YClopsConfiguration.h
/home/tallred3/ecen493/SeniorProject/trunk/Code/YClopsLib/src/YClopsConfiguration.cpp