YClops: Lidar Class Reference
Lidar Class Reference
#include <Lidar.h>
Public Member Functions
Lidar ()
void loadConfiguration (const mrpt::utils::CConfigFileBase &config, const std::string &sectionName)
void init ()
void sensorProcess ()
SensorData * getData ()
void dumpData (std::ostream &out)
virtual ~Lidar ()
Detailed Description
Definition at line 14 of file Lidar.h.
Constructor & Destructor Documentation
Lidar::Lidar ()
Definition at line 18 of file Lidar.cpp.
Lidar::~Lidar () [virtual]
Definition at line 103 of file Lidar.cpp.
References DEBUG3, and LOG_LIDAR.
Member Function Documentation
void Lidar::dumpData (std::ostream & out)
Definition at line 68 of file Lidar.cpp.
References DEBUG3, ERROR, and LOG_LIDAR.
Referenced by YClopsReactiveNavInterface::senseObstacles().
SensorData * Lidar::getData () [virtual]
SensorData needs to be allocated on the heap to avoid splicing when we cast it to be a various sensor type
Implements YClopsSensor.
Definition at line 53 of file Lidar.cpp.
void Lidar::init () [virtual]
initialize the sensor
Implements YClopsSensor.
Definition at line 42 of file Lidar.cpp.
Referenced by YClopsReactiveNavInterface::YClopsReactiveNavInterface().
void Lidar::loadConfiguration (const mrpt::utils::CConfigFileBase & config, const std::string & sectionName) [virtual]
load sensor specific values from the configuration file
Implements YClopsSensor.
Definition at line 22 of file Lidar.cpp.
References DEBUG3, and LOG_LIDAR.
Referenced by YClopsReactiveNavInterface::YClopsReactiveNavInterface().
void Lidar::sensorProcess () [virtual]
collect data from the sensor and cache it
Implements YClopsSensor.
Definition at line 46 of file Lidar.cpp.
Referenced by YClopsReactiveNavInterface::senseObstacles().
The documentation for this class was generated from the following files:
/home/tallred3/ecen493/SeniorProject/trunk/Code/YClopsLib/inc/Lidar.h
/home/tallred3/ecen493/SeniorProject/trunk/Code/YClopsLib/src/Lidar.cpp