YClops: WiiController Class Reference
WiiController Class Reference
#include <WiiController.h>
Public Member Functions
void getMoteButtons (uint16_t &mButtons)
void getClassicButtons (uint16_t &cButtons)
void getLeftStick (uint16_t &xAxis, uint16_t &yAxis)
void getRightStick (uint16_t &xAxis, uint16_t &yAxis)
void getLeftAnalog (uint16_t &left)
void getRightAnalog (uint16_t &right)
Static Public Member Functions
static WiiController * create ()
static WiiController * getReference (int index=0)
static void destroyReference (int index=0)
static int getControllerCount ()
Private Member Functions
virtual ~WiiController ()
WiiController ()
void process_btn_mesg (struct cwiid_btn_mesg *mesg)
void process_classic_mesg (struct cwiid_classic_mesg *mesg)
Private Attributes
cwiid_wiimote_t * wiiMote
uint16_t motePrevButtons
uint16_t moteButtonsPressed
uint16_t moteButtonsReleased
uint16_t moteButtons
uint16_t classicButtonsPressed
uint16_t classicButtonsReleased
uint16_t classicButtons
uint16_t lXaxis
uint16_t lYaxis
uint16_t rXaxis
uint16_t rYaxis
uint16_t lAnalog
uint16_t rAnalog
Static Private Attributes
static std::vector
< WiiController * > controllers
Friends
cwiid_mesg_callback_t cwiid_callback
Detailed Description
Definition at line 16 of file WiiController.h.
Constructor & Destructor Documentation
WiiController::~WiiController () [private, virtual]
Definition at line 78 of file WiiController.cpp.
References wiiMote.
WiiController::WiiController () [private]
Definition at line 40 of file WiiController.cpp.
References cwiid_callback, and wiiMote.
Referenced by create().
Member Function Documentation
WiiController * WiiController::create () [static]
Definition at line 21 of file WiiController.cpp.
References controllers, and WiiController().
Referenced by main().
void WiiController::destroyReference (int index = 0) [static]
Definition at line 32 of file WiiController.cpp.
References controllers.
void WiiController::getClassicButtons (uint16_t & cButtons) [inline]
Definition at line 24 of file WiiController.h.
References classicButtons.
Referenced by signal_handler().
int WiiController::getControllerCount () [static]
Definition at line 36 of file WiiController.cpp.
References controllers.
void WiiController::getLeftAnalog (uint16_t & left) [inline]
Definition at line 27 of file WiiController.h.
References lAnalog.
Referenced by signal_handler().
void WiiController::getLeftStick (uint16_t & xAxis, uint16_t & yAxis) [inline]
Definition at line 25 of file WiiController.h.
References lXaxis, and lYaxis.
Referenced by DualMotorCommand::doProcess(), and signal_handler().
void WiiController::getMoteButtons (uint16_t & mButtons) [inline]
Definition at line 23 of file WiiController.h.
References moteButtons.
Referenced by signal_handler().
WiiController * WiiController::getReference (int index = 0) [static]
Definition at line 28 of file WiiController.cpp.
References controllers.
Referenced by cwiid_callback(), DualMotorCommand::doProcess(), and signal_handler().
void WiiController::getRightAnalog (uint16_t & right) [inline]
Definition at line 28 of file WiiController.h.
References rAnalog.
Referenced by signal_handler().
void WiiController::getRightStick (uint16_t & xAxis, uint16_t & yAxis) [inline]
Definition at line 26 of file WiiController.h.
References rXaxis, and rYaxis.
Referenced by DualMotorCommand::doProcess(), and signal_handler().
void WiiController::process_btn_mesg (struct cwiid_btn_mesg * mesg) [private]
Definition at line 122 of file WiiController.cpp.
References moteButtons, moteButtonsPressed, and moteButtonsReleased.
Referenced by cwiid_callback().
void WiiController::process_classic_mesg (struct cwiid_classic_mesg * mesg) [private]
Definition at line 131 of file WiiController.cpp.
References classicButtons, classicButtonsPressed, classicButtonsReleased, lAnalog, lXaxis, lYaxis, rAnalog, rXaxis, and rYaxis.
Referenced by cwiid_callback().
Friends And Related Function Documentation
friend cwiid_mesg_callback_t cwiid_callback [friend]
Definition at line 39 of file WiiController.h.
Referenced by WiiController().
Member Data Documentation
uint16_t WiiController::classicButtons [private]
Definition at line 48 of file WiiController.h.
Referenced by getClassicButtons(), and process_classic_mesg().
uint16_t WiiController::classicButtonsPressed [private]
Definition at line 46 of file WiiController.h.
Referenced by process_classic_mesg().
uint16_t WiiController::classicButtonsReleased [private]
Definition at line 47 of file WiiController.h.
Referenced by process_classic_mesg().
std::vector< WiiController * > WiiController::controllers [static, private]
Definition at line 33 of file WiiController.h.
Referenced by create(), destroyReference(), getControllerCount(), and getReference().
uint16_t WiiController::lAnalog [private]
Definition at line 52 of file WiiController.h.
Referenced by getLeftAnalog(), and process_classic_mesg().
uint16_t WiiController::lXaxis [private]
Definition at line 50 of file WiiController.h.
Referenced by getLeftStick(), and process_classic_mesg().
uint16_t WiiController::lYaxis [private]
Definition at line 50 of file WiiController.h.
Referenced by getLeftStick(), and process_classic_mesg().
uint16_t WiiController::moteButtons [private]
Definition at line 44 of file WiiController.h.
Referenced by getMoteButtons(), and process_btn_mesg().
uint16_t WiiController::moteButtonsPressed [private]
Definition at line 42 of file WiiController.h.
Referenced by process_btn_mesg().
uint16_t WiiController::moteButtonsReleased [private]
Definition at line 43 of file WiiController.h.
Referenced by process_btn_mesg().
uint16_t WiiController::motePrevButtons [private]
Definition at line 41 of file WiiController.h.
uint16_t WiiController::rAnalog [private]
Definition at line 52 of file WiiController.h.
Referenced by getRightAnalog(), and process_classic_mesg().
uint16_t WiiController::rXaxis [private]
Definition at line 51 of file WiiController.h.
Referenced by getRightStick(), and process_classic_mesg().
uint16_t WiiController::rYaxis [private]
Definition at line 51 of file WiiController.h.
Referenced by getRightStick(), and process_classic_mesg().
cwiid_wiimote_t* WiiController::wiiMote [private]
Definition at line 35 of file WiiController.h.
Referenced by WiiController(), and ~WiiController().
The documentation for this class was generated from the following files:
Sensors/MultiSensorLib/inc/WiiController.h
Sensors/MultiSensorLib/src/WiiController.cpp