YClops: MotorController Class Reference
MotorController Class Reference
#include <MotorController.h>
Public Types
enum MotorChannel { Channel1 = 1, Channel2 = 2, BothChannels = 3 }
Public Member Functions
virtual ~MotorController ()
void doProcess ()
bool setAcceleration (MotorChannel channel, double acceleration)
bool setDeceleration (MotorChannel channel, double deceration)
bool emergencyStop ()
bool clearEmergencyStop ()
bool setSpeed (MotorChannel channel, int value)
bool setEncoderCounter (MotorChannel channel, int value=0)
bool setEncoderUsage (int value=1)
bool setMixingMode (int value)
bool restoreMixingMode ()
bool setOperatingMode (int value)
bool restoreOperatingMode ()
bool getMotorAmps (double &motor1Amps, double &motor2Amps)
bool getAnalogInputs (int input, int &value)
bool getBatteryAmps (double &motor1Amps, double &motor2Amps)
bool getAbsoluteEncoderCount (int *ch1, int *ch2)
bool getRelativeEncoderCount (int &ch1, int &ch2)
bool getEncoderSpeeds (int &speed1, int &speed2)
bool getTemperature (int &ch1, int &ch2, int &ic)
bool getTime (int &hours, int &minutes, int &seconds)
bool getVoltages (double &driverVolt, double &batteryVolt, double &v5out)
bool loadEEPROMSettings ()
bool failSafeReset ()
bool saveConfigSettings ()
bool reset ()
bool setTime (int hours, int minutes, int seconds)
bool setCommandLinearity (int linearity)
bool setCommandPriority (int signal, int priority)
bool setSerialWatchDogTimer (int time)
bool setEncoderPPR (int ppr)
bool setOverVoltageLimit (double limit)
bool setUnderVoltageLimit (double limit)
bool setShortCircuitDetectionThreshold (int value)
bool getMotorLimits (int &m1Max, int &m2Max, int &m1Min, int &m2Min)
bool setLoopMode (MotorChannel channel, std::string &loopMode)
Static Public Member Functions
static MotorController * instance ()
Static Public Attributes
static const int MOTOR_SECRET_KEY = 321654987
static const std::string MOTOR_BAD_COMMAND = "-"
Motor reset key used for sensitive operations.
Static Protected Attributes
static MotorController * mc = NULL
A semaphore to protect the serialPort.
Private Member Functions
MotorController ()
bool assertValidMotorRange (int max, int min, int value) const
The pointer to the instance of the motor controller.
bool assertValidVoltage ()
bool sendCommand (const std::string command, const std::string expectedResponse, std::string *response, bool permissive=false)
void enableSerialEcho ()
void disableSerialEcho ()
bool getFaultFlags ()
bool getStatusFlags ()
bool getControlUnitType ()
bool clearBufferHistory ()
bool responseParser (std::string response, int num,...)
Private Attributes
mrpt::hwdrivers::CSerialPort serialPort
bool echoEnabled
the serial port to communicate to the motor controller
int motor1Speed
true if the motor controller is set to echo serial commands
int motor2Speed
the current speed for the first channel motor
const int motor1SpeedMax
the current speed for the second channel motor
const int motor2SpeedMax
The hard upper limit for the first channel motor speed.
const int motor1SpeedMin
The hard upper limit for the second channel motor speed.
const int motor2SpeedMin
The hard lower limit for the first channel motor speed (lower limit would be the reverse speed)
int faultFlagVector
The hard lower limit for the second channel motor speed.
int mixingMode
The fault flag status for the motor controller.
int currentMixingMode
The how a !M command is interpreted.
int operatingMode
How the !M command is currently interpreted.
int currentOperatingMode
The configuration for the operating mode (open, closed, position)
sem_t serialPortSem
The current mode the controller is set to.
Detailed Description
MotorController - interface class to the RoboteQ 2440 motor controller
Definition at line 27 of file MotorController.h.
Member Enumeration Documentation
enum MotorController::MotorChannel
Abstract representation for a channel in the motor controller
Enumerator:
Channel1
Channel2
BothChannels
Definition at line 37 of file MotorController.h.
Constructor & Destructor Documentation
virtual MotorController::~MotorController () [inline, virtual]
Class destructor
Definition at line 46 of file MotorController.h.
References serialPortSem.
MotorController::MotorController () [private]
MotorController constructor
Parameters:
portName - the serial port over which the commands will be sent
enableEcho - set to true to check error for errors from the motor controller
motor1Max - the maximum power for channel1 defined on the interval [1000,-1000] where -1000 is full reverse
motor2Max - the maximum power for channel2 defined on the interval [1000, -1000] where -1000 is full reverse
motor1Min - the minimum power for channel1
motor2Min - the minimum power for channel2
Definition at line 38 of file MotorController.cpp.
References BothChannels, clearEmergencyStop(), DEBUG4, disableSerialEcho(), echoEnabled, emergencyStop(), enableSerialEcho(), FATAL, LOG, motor1SpeedMax, motor1SpeedMin, motor2SpeedMax, motor2SpeedMin, sendCommand(), serialPort, and setLoopMode().
Member Function Documentation
bool MotorController::assertValidMotorRange (int max, int min, int value) const [private]
The pointer to the instance of the motor controller.
assertValidMotorRange - checks the parameters if they are in a valid range
Parameters:
max - the max value for the range
min - the min value for the range
value - the value to check
Returns:
true if the value is in range
Definition at line 355 of file MotorController.cpp.
bool MotorController::assertValidVoltage () [private]
assertValidVoltage - shuts off the motor controller if the voltage is out of safe operating parameters
Definition at line 359 of file MotorController.cpp.
References sendCommand().
bool MotorController::clearBufferHistory () [private]
clearBufferHistory - clears the command history buffer
Returns:
true upon success
Definition at line 410 of file MotorController.cpp.
bool MotorController::clearEmergencyStop ()
clearEmergencyStop - clears the emergency stop state
Returns:
true upon successful transmission
Definition at line 110 of file MotorController.cpp.
References DEBUG4, LOG, and sendCommand().
Referenced by MotorController().
void MotorController::disableSerialEcho () [private]
disableSerialEcho - turns off the echo of commands from the motor controller
Definition at line 390 of file MotorController.cpp.
References DEBUG4, LOG, and sendCommand().
Referenced by MotorController().
void MotorController::doProcess ()
doProcess - sends the current speed command to the motor controller
Definition at line 87 of file MotorController.cpp.
References motor1Speed, motor2Speed, and sendCommand().
Referenced by DualMotorCommand::doProcess(), and MotorCommand::doProcess().
bool MotorController::emergencyStop ()
emergencyStop - sends the emergency stop command to the motor controller the motor controller will not start until it is power cycled or the clearEmergencyStop function is called.
Returns:
true upon successful transmission
Definition at line 105 of file MotorController.cpp.
References DEBUG4, LOG, and sendCommand().
Referenced by MotorController(), and setLoopMode().
void MotorController::enableSerialEcho () [private]
enableSerialEcho - turns on the echo of commands from the motor controller
Definition at line 385 of file MotorController.cpp.
References DEBUG4, LOG, and sendCommand().
Referenced by MotorController().
bool MotorController::failSafeReset ()
failSafeReset - power cycles the motor controller and resets values to their default factory settings
Definition at line 268 of file MotorController.cpp.
bool MotorController::getAbsoluteEncoderCount (int * ch1, int * ch2)
getAbsoluteEncoderCount - gets the absolute number of encoder counts as a 32bit signed number
Parameters:
channel1Count - reference to the encoder count for channel 1
channel2Count - reference to the encoder count for channel 2
Returns:
true upon success
Definition at line 226 of file MotorController.cpp.
References sendCommand().
Referenced by WheelEncoder::sensorProcess().
bool MotorController::getAnalogInputs (int input, int & value)
getAnalogInputs - gets the number of millivolts on the given analog input pin
Parameters:
input - the input pin to query
value - reference to the number of millivolts on the analog input pin
Returns:
true upon success
Definition at line 208 of file MotorController.cpp.
bool MotorController::getBatteryAmps (double & motor1Amps, double & motor2Amps)
getBatteryAmps - gets the number of deciamps flowing from the batteries
Parameters:
motor1Amps - the number of deciamps flowing into the first motor channel
motor2Amps - the number of deciamps flowing into the second motor channel
Returns:
true upon success
Definition at line 213 of file MotorController.cpp.
References sendCommand().
bool MotorController::getControlUnitType () [private]
getControlUnitType - checks to see if the attached roboteq control unit is supported
Returns:
true upon supported control unit
Definition at line 405 of file MotorController.cpp.
bool MotorController::getEncoderSpeeds (int & speed1, int & speed2)
getEncoderSpeed - returns the speed of the encoder for the given channel
Parameters:
channel - the motor channel to query
speed - the speed of the encoder in RPMs
Returns:
- true upon success
Definition at line 293 of file MotorController.cpp.
References DEBUG3, LOG_MOTOR, responseParser(), and sendCommand().
Referenced by WheelEncoder::sensorProcess().
bool MotorController::getFaultFlags () [private]
getFaultFlags returns the status of any faults that may occour in the motor controller
Definition at line 395 of file MotorController.cpp.
bool MotorController::getMotorAmps (double & motor1Amps, double & motor2Amps)
getMotorAmps - gets the amps flowing through the motors
Parameters:
motor1Amps - the number of amps flowing through the first channel motor
motor2Amps - the number of amps flowing through the second channel motor
Returns:
true upon success
Definition at line 193 of file MotorController.cpp.
References serialPort.
bool MotorController::getMotorLimits (int & m1Max, int & m2Max, int & m1Min, int & m2Min)
getMotorLimits - returns the maximum rpms for the motors
Parameters:
m1Max - a reference to where to put the motor 1 max
m2Max - a reference to where to put the motor 2 max
m1Min - a reference to where to put the motor 1 min
m2Min - a reference to where to put the motor 2 min
Returns:
true
Definition at line 325 of file MotorController.cpp.
References motor1SpeedMax, motor1SpeedMin, motor2SpeedMax, and motor2SpeedMin.
bool MotorController::getRelativeEncoderCount (int & ch1, int & ch2)
getRelativeEncoderCount - gets the encoder count since the last time this command was used
Parameters:
ch1 - the encoder count for the first channel
ch2 - the encoder count for the second channel
Returns:
true if successful
Definition at line 231 of file MotorController.cpp.
References sendCommand().
Referenced by WheelEncoder::sensorProcess().
bool MotorController::getStatusFlags () [private]
getStatusFlags returns the status of the motor controller as a bit vector
Definition at line 400 of file MotorController.cpp.
bool MotorController::getTemperature (int & ch1, int & ch2, int & ic)
getTemperature - gets the temperature of the heatsinks of the motor controller
Parameters:
ch1 - the temperature in degrees C for the first channel
ch2 - the temperature in degrees C for the second channel
ic - the temperature in degrees C of the internal IC
Returns:
true if successful
Definition at line 241 of file MotorController.cpp.
References sendCommand().
bool MotorController::getTime (int & hours, int & minutes, int & seconds)
getTime - returns the time of the motor controller
Parameters:
hours - reference to the number of hours
minutes - reference to the number of minutes
seconds - reference to the number of seconds
Returns:
true upon success
Definition at line 246 of file MotorController.cpp.
References sendCommand().
bool MotorController::getVoltages (double & driverVolt, double & batteryVolt, double & v5out)
getVoltages - gets the voltages from the battery, internal motor driver and the 5 volt usb out.
Parameters:
driverVolt - the motor driver output voltages as measured in volts
batteryVolt - the battery voltage as measured in volts
v5out - the voltage of the usb as measured in volts
Returns:
true upon success.
Definition at line 251 of file MotorController.cpp.
References sendCommand().
MotorController * MotorController::instance () [static]
Definition at line 26 of file MotorController.cpp.
References DEBUG4, LOG, and mc.
Referenced by DualMotorCommand::doProcess(), MotorCommand::doProcess(), WheelEncoder::init(), and WheelEncoder::sensorProcess().
bool MotorController::loadEEPROMSettings ()
loadEEPROMSettings - loads setting set in the eeprom back into ram and activates the settings
Returns:
true upon success
Definition at line 264 of file MotorController.cpp.
References sendCommand().
bool MotorController::reset ()
reset - power cycles the motor controller
Returns:
true upon successful transmission
Definition at line 278 of file MotorController.cpp.
References MOTOR_SECRET_KEY, and sendCommand().
bool MotorController::responseParser (std::string response, int num, ...) [inline, private]
Definition at line 414 of file MotorController.h.
Referenced by getEncoderSpeeds().
bool MotorController::restoreMixingMode ()
Definition at line 211 of file MotorController.cpp.
References DEBUG3, LOG_MOTOR, mixingMode, and setMixingMode().
bool MotorController::restoreOperatingMode ()
Definition at line 235 of file MotorController.cpp.
References DEBUG3, LOG_MOTOR, operatingMode, and setOperatingMode().
bool MotorController::saveConfigSettings ()
saveConfigSettings - saves the current settings in ram to the EEPROM DON'T Save while motors are running
Returns:
true upon success
Definition at line 273 of file MotorController.cpp.
bool MotorController::sendCommand (const std::string command, const std::string expectedResponse, std::string * response, bool permissive = false) [private]
sendCommand - low level function call to send a command to the motor controller
Parameters:
command - the carriage return ended command to send to the motor controller
Returns:
true upon successful transmission of the command
Definition at line 365 of file MotorController.cpp.
References DEBUG4, echoEnabled, LOG, and serialPort.
Referenced by assertValidVoltage(), clearEmergencyStop(), disableSerialEcho(), doProcess(), emergencyStop(), enableSerialEcho(), getAbsoluteEncoderCount(), getBatteryAmps(), getEncoderSpeeds(), getRelativeEncoderCount(), getTemperature(), getTime(), getVoltages(), loadEEPROMSettings(), MotorController(), reset(), setEncoderUsage(), setLoopMode(), setMixingMode(), setOperatingMode(), and setTime().
bool MotorController::setAcceleration (MotorChannel channel, double acceleration)
SetAcceleration - sets a limit to the acceleration for the motor controller
Parameters:
channel - the motor channel for which to set the acceleration
acceleration - the number of rpms per second of acceleration precise enough to one tenth of an rpm
Returns:
true upon success
Definition at line 95 of file MotorController.cpp.
bool MotorController::setCommandLinearity (int linearity)
SetCommandLinearity - This parameter is used for applying an exponential or a logarithmic transformation on the command input, regardless of its source (serial, pulse or analog). There are 3 exponential and 3 logarithmic choices. Exponential correction make the commands change less at the beginning and become stronger at the end of the command input range. The logarithmic correction will have a stronger effect near the start and lesser effect near the end. The linear selection causes no change to the input. A linearity transform is also available for all analog and pulse inputs. Both can be enabled although in most cases, it is best to use the Command Linearity parameter for modifying command profiles. 0 : linear (no change) 1 : exp weak 2 : exp medium 3 : exp strong 4 : log weak 5 : log medium 6 : log strong
Definition at line 290 of file MotorController.cpp.
bool MotorController::setCommandPriority (int signal, int priority)
setCommandPriority - This parameter contains up to 3 variables and is used to set which type of command in priority the controller will respond to and in which order. The first item is the first priority, second second priority, third third priority. Each priority item is then one of the three command modes: Serial, Analog or RC Pulse. 1 : Serial 2 : RC 3 : Analog
Parameters:
signal - the singal to set to the priority
priority - the priority level to be set for the signal
Returns:
true upon success
Definition at line 295 of file MotorController.cpp.
bool MotorController::setDeceleration (MotorChannel channel, double deceration)
SetDeceleration - sets a limit for how fast the motor controller will slow down a channel
Parameters:
channel - the motor channel for which to set the acceleration
deceleration - the number of rpms per second of deceleration precise to one tenth of an rpm
Returns:
true upon success
Definition at line 100 of file MotorController.cpp.
bool MotorController::setEncoderCounter (MotorChannel channel, int value = 0)
setEncoderCounter - sets the wheel encoder count to a specific value
Parameters:
channel - the channel of the wheel encoder count to set
value - the value to set the encoder count
Returns:
true upon success
Definition at line 167 of file MotorController.cpp.
References BothChannels, Channel1, Channel2, and serialPort.
Referenced by WheelEncoder::init().
bool MotorController::setEncoderPPR (int ppr)
setEncoderPPR - sets the pulses per revolution for the encoder on the motor controller
Parameters:
ppr - the number of pulses per revolution on the wheel encoder
Returns:
true upon success
Definition at line 305 of file MotorController.cpp.
Referenced by WheelEncoder::init().
bool MotorController::setEncoderUsage (int value = 1)
Definition at line 182 of file MotorController.cpp.
References DEBUG3, LOG_MOTOR, and sendCommand().
Referenced by WheelEncoder::init().
bool MotorController::setLoopMode (MotorChannel channel, std::string & loopMode)
Definition at line 333 of file MotorController.cpp.
References DEBUG4, emergencyStop(), FATAL, LOG, and sendCommand().
Referenced by MotorController().
bool MotorController::setMixingMode (int value)
Definition at line 196 of file MotorController.cpp.
References currentMixingMode, DEBUG3, LOG_MOTOR, and sendCommand().
Referenced by restoreMixingMode().
bool MotorController::setOperatingMode (int value)
Definition at line 216 of file MotorController.cpp.
References currentOperatingMode, DEBUG3, ERROR, LOG_MOTOR, and sendCommand().
Referenced by restoreOperatingMode().
bool MotorController::setOverVoltageLimit (double limit)
setOverVoltageLimit - sets the maximum voltage value for the power stage. Higher voltages will cause the motor controller to turn off and signal an overvoltage fault
Parameters:
limit - the upper limit of the power stage voltage measured in volts
Returns:
true upon success
Definition at line 310 of file MotorController.cpp.
bool MotorController::setSerialWatchDogTimer (int time)
setSerialWatchDogTimer - will set the serial watchdog timer to be equal to the parameter where it is measured in ms
Parameters:
time - the length of the watchdog timer as measured in ms
Returns:
true upon success
Definition at line 300 of file MotorController.cpp.
bool MotorController::setShortCircuitDetectionThreshold (int value)
setShortCircuitDetectionThreshold - Short Circuit Detection Threshold This configuration parameter sets the threshold level for the short circuit detection. There are 4 sensitivity levels from 0 to 3. 0 : Very high sensitivity 1 : Medium sensitivity 2 : Low sensitivity 3 : Short circuit protection disabled Using a value of 3 will cause an error
Parameters:
value - the sensitivity of the short circuit detection threshold to be used
Returns:
true upon success
Definition at line 320 of file MotorController.cpp.
bool MotorController::setSpeed (MotorChannel channel, int value)
setSpeed - sets the speed for the motor control channel
Parameters:
channel - the channel to change the speed { Channel1, Channel2, BothChannels }
value - the speed at which to set the channel
Returns:
true upon success
Definition at line 115 of file MotorController.cpp.
References BothChannels, Channel1, Channel2, motor1Speed, motor1SpeedMax, motor1SpeedMin, motor2Speed, motor2SpeedMax, and motor2SpeedMin.
Referenced by DualMotorCommand::doProcess().
bool MotorController::setTime (int hours, int minutes, int seconds)
setTime - sets the local time of the motor controller to the time in the parameters
Parameters:
hours - the hours segment of the time
minutes - the minutes segment of the time
seconds - the seconds segment of the time
Returns:
true upon successful transmission
Definition at line 284 of file MotorController.cpp.
References sendCommand().
bool MotorController::setUnderVoltageLimit (double limit)
setUnderVoltageLimit - sets the minimum voltage value for the power stage. Lower voltages will cause the motor controller to turn off and signal an undervoltage fault.
Parameters:
limit - the lower limit of the power stage voltage measured in volts
Returns:
true upon success
Definition at line 315 of file MotorController.cpp.
Member Data Documentation
int MotorController::currentMixingMode [private]
The how a !M command is interpreted.
Definition at line 353 of file MotorController.h.
Referenced by setMixingMode().
int MotorController::currentOperatingMode [private]
The configuration for the operating mode (open, closed, position)
Definition at line 355 of file MotorController.h.
Referenced by setOperatingMode().
bool MotorController::echoEnabled [private]
the serial port to communicate to the motor controller
Definition at line 344 of file MotorController.h.
Referenced by MotorController(), and sendCommand().
int MotorController::faultFlagVector [private]
The hard lower limit for the second channel motor speed.
Definition at line 351 of file MotorController.h.
MotorController * MotorController::mc = NULL [static, protected]
A semaphore to protect the serialPort.
Definition at line 358 of file MotorController.h.
Referenced by instance().
int MotorController::mixingMode [private]
The fault flag status for the motor controller.
Definition at line 352 of file MotorController.h.
Referenced by restoreMixingMode().
int MotorController::motor1Speed [private]
true if the motor controller is set to echo serial commands
Definition at line 345 of file MotorController.h.
Referenced by doProcess(), and setSpeed().
const int MotorController::motor1SpeedMax [private]
the current speed for the second channel motor
Definition at line 347 of file MotorController.h.
Referenced by getMotorLimits(), MotorController(), and setSpeed().
const int MotorController::motor1SpeedMin [private]
The hard upper limit for the second channel motor speed.
Definition at line 349 of file MotorController.h.
Referenced by getMotorLimits(), MotorController(), and setSpeed().
int MotorController::motor2Speed [private]
the current speed for the first channel motor
Definition at line 346 of file MotorController.h.
Referenced by doProcess(), and setSpeed().
const int MotorController::motor2SpeedMax [private]
The hard upper limit for the first channel motor speed.
Definition at line 348 of file MotorController.h.
Referenced by getMotorLimits(), MotorController(), and setSpeed().
const int MotorController::motor2SpeedMin [private]
The hard lower limit for the first channel motor speed (lower limit would be the reverse speed)
Definition at line 350 of file MotorController.h.
Referenced by getMotorLimits(), MotorController(), and setSpeed().
const std::string MotorController::MOTOR_BAD_COMMAND = "-" [static]
Motor reset key used for sensitive operations.
Definition at line 30 of file MotorController.h.
const int MotorController::MOTOR_SECRET_KEY = 321654987 [static]
Definition at line 29 of file MotorController.h.
Referenced by reset().
int MotorController::operatingMode [private]
How the !M command is currently interpreted.
Definition at line 354 of file MotorController.h.
Referenced by restoreOperatingMode().
mrpt::hwdrivers::CSerialPort MotorController::serialPort [private]
Definition at line 343 of file MotorController.h.
Referenced by getMotorAmps(), MotorController(), sendCommand(), and setEncoderCounter().
sem_t MotorController::serialPortSem [private]
The current mode the controller is set to.
Definition at line 356 of file MotorController.h.
Referenced by ~MotorController().
The documentation for this class was generated from the following files:
/home/tallred3/ecen493/SeniorProject/trunk/Code/YClopsLib/inc/MotorController.h
MotorControllerResponseParsing/MotorController.cpp
/home/tallred3/ecen493/SeniorProject/trunk/Code/YClopsLib/src/MotorController.cpp