YClops: Beeper Class Reference
Beeper Class Reference
#include <Beeper.h>
Classes
struct beep_struct
Static Public Member Functions
static void beep (int frequency, int length)
Private Types
typedef struct Beeper::beep_struct beep_t
Private Member Functions
Beeper ()
virtual ~Beeper ()
Static Private Member Functions
static void * beepi (void *)
Static Private Attributes
static beep_t buffer = Beeper::beep_struct(0,0)
Detailed Description
This class is an empty class used only for a grouping of static functions to make the internal pc speaker beep
Definition at line 17 of file Beeper.h.
Member Typedef Documentation
typedef struct Beeper::beep_struct Beeper::beep_t [private]
An internal structure to contain data that needs to be passed into the beepi function
Constructor & Destructor Documentation
Beeper::Beeper () [private]
Class Constructor - not used
Definition at line 24 of file Beeper.cpp.
Beeper::~Beeper () [private, virtual]
Class Destructor - not used
Definition at line 27 of file Beeper.cpp.
Member Function Documentation
void Beeper::beep (int frequency, int length) [static]
play a beep through the pc_spkr
Parameters:
frequency - the frequency of the sound to be played
length - the length in milliseconds to play
Definition at line 30 of file Beeper.cpp.
References beepi().
Referenced by signal_handler().
void * Beeper::beepi (void * data) [static, private]
Internal static method that writes values to the pc speaker
Parameters:
void pointer to the location of the beep_struct that contains the sound to play
Definition at line 38 of file Beeper.cpp.
References Beeper::beep_struct::frequency, and Beeper::beep_struct::length.
Referenced by beep().
Member Data Documentation
Beeper::beep_t Beeper::buffer = Beeper::beep_struct(0,0) [static, private]
Definition at line 37 of file Beeper.h.
The documentation for this class was generated from the following files:
/home/tallred3/ecen493/SeniorProject/trunk/Code/YClopsLib/inc/Beeper.h
/home/tallred3/ecen493/SeniorProject/trunk/Code/YClopsLib/src/Beeper.cpp