YClops: TSPNavigation Class Reference
TSPNavigation Class Reference
#include <WaypointPlanner.h>
Public Member Functions
TSPNavigation (double initLat, double initLon)
virtual ~TSPNavigation ()
mrpt::aligned_containers
< mrpt::poses::CPoint2D >
::vector_t solve (bool inMeters)
Static Private Member Functions
static void nieveTSPSolution (mrpt::aligned_containers< mrpt::poses::CPoint2D >::vector_t &toVisit, mrpt::aligned_containers< mrpt::poses::CPoint2D >::vector_t &visited, bool inMeters)
static void acoTSPSolution (mrpt::aligned_containers< mrpt::poses::CPoint2D >::vector_t &toVisit, mrpt::aligned_containers< mrpt::poses::CPoint2D >::vector_t &visited, bool inMeters)
Detailed Description
Definition at line 90 of file WaypointPlanner.h.
Constructor & Destructor Documentation
TSPNavigation::TSPNavigation (double initLat, double initLon)
Definition at line 133 of file WaypointPlanner.cpp.
virtual TSPNavigation::~TSPNavigation () [inline, virtual]
Definition at line 94 of file WaypointPlanner.h.
Member Function Documentation
void TSPNavigation::acoTSPSolution (mrpt::aligned_containers< mrpt::poses::CPoint2D >::vector_t & toVisit, mrpt::aligned_containers< mrpt::poses::CPoint2D >::vector_t & visited, bool inMeters) [static, private]
Definition at line 180 of file WaypointPlanner.cpp.
References tkhl::besttour, tkhl::TSPDriver::GetAnt(), tkhl::iCityCount, and tkhl::TSPDriver::StartSearch().
void TSPNavigation::nieveTSPSolution (mrpt::aligned_containers< mrpt::poses::CPoint2D >::vector_t & toVisit, mrpt::aligned_containers< mrpt::poses::CPoint2D >::vector_t & visited, bool inMeters) [static, private]
nieveTSPSolution - a nieve solution to the traveling salesman problem this implementation is greedy in that it simply goes to the nearest unvisited point
Parameters:
toVisit a std::vector of latitudes and longitudes that are to be visited
visited a std::vector of (initially) one latitude and longitude representing where we start after the algorithm is run it will be an ordered set of latlon_t where the first is where we are at and each subsequent latlon_t is the next closest latlon_t
Definition at line 152 of file WaypointPlanner.cpp.
References AbstractNavigationInterface::haversineDistance(), AbstractNavigationInterface::LAT, and AbstractNavigationInterface::LON.
Referenced by solve().
std::vector< mrpt::poses::CPoint2D, Eigen::aligned_allocator< mrpt::poses::CPoint2D > > TSPNavigation::solve (bool inMeters) [virtual]
TSPNavigation::solve - solves the TSP by calling TSPNavigation::nieveTSPSolution
See also:
nieveTSPSolution
Implements AbstractNavigationInterface.
Definition at line 135 of file WaypointPlanner.cpp.
References nieveTSPSolution(), AbstractNavigationInterface::toVisit, and AbstractNavigationInterface::visited.
Referenced by NavigationChallenge::AutonomousMode(), and SimpleNavigation::go().
The documentation for this class was generated from the following files:
/home/tallred3/ecen493/SeniorProject/trunk/Code/YClopsLib/inc/WaypointPlanner.h
/home/tallred3/ecen493/SeniorProject/trunk/Code/YClopsLib/src/WaypointPlanner.cpp