YClops: ReactiveNavigationDemoFrame Class Reference
ReactiveNavigationDemoFrame Class Reference
#include <ReactiveNavigationDemoMain.h>
Public Member Functions
ReactiveNavigationDemoFrame (wxWindow *parent, wxWindowID id=-1)
virtual ~ReactiveNavigationDemoFrame ()
void OnQuit (wxCommandEvent &event)
void OnAbout (wxCommandEvent &event)
void OnbtnStartClick (wxCommandEvent &event)
void OnbtnPauseClick (wxCommandEvent &event)
void OnbtnExitClick (wxCommandEvent &event)
void OnbtnNavigateClick (wxCommandEvent &event)
void OnplotMouseMove (wxMouseEvent &event)
void OntimSimulateTrigger (wxTimerEvent &event)
void OnbtnResetClick (wxCommandEvent &event)
void OnbtnEditRobotParamsClick (wxCommandEvent &event)
void OnbtnEditNavParamsClick (wxCommandEvent &event)
void OnrbExtMapSelect (wxCommandEvent &event)
void OncbInternalParamsClick (wxCommandEvent &event)
void OncbInternalParamsClick1 (wxCommandEvent &event)
void OnLoadPointsFileClick (wxCommandEvent &event)
void OnSelectMapClick (wxCommandEvent &event)
void OnreactivenavTargetMenu (wxCommandEvent &event)
bool reloadMap ()
void reloadRobotShape ()
void tryConstructReactiveNavigator ()
Public Attributes
wxTextCtrl * edMapFile
wxPanel * Panel1
wxTextCtrl * edX
mpWindow * plot
wxTextCtrl * edY
wxStatusBar * StatusBar1
wxTextCtrl * edRobotCfgFile
wxButton * btnNavigate
wxButton * btnPause
wxCheckBox * cbExtMap
wxStaticText * StaticText3
wxButton * btnEditNavParams
wxButton * btnExit
wxTextCtrl * edLog
wxTextCtrl * edNavCfgFile
wxStaticText * StaticText4
wxStaticText * StaticText5
wxStaticText * StaticText2
wxStaticText * StaticText6
wxTimer timSimulate
wxButton * btnStart
wxCheckBox * cbInternalParams
wxButton * btnEditRobotParams
wxButton * btnLoadPointsFile
wxCheckBox * cbTSP
wxButton * btnLoadMapsFile
mpBitmapLayer * lyGridmap
mpPolygon * lyVehicle
mpPolygon * lyTarget
CMyRedirector * myRedirector
Static Public Attributes
static const long ID_BUTTON1 = wxNewId()
static const long ID_BUTTON2 = wxNewId()
static const long ID_BUTTON3 = wxNewId()
static const long ID_CHECKBOX1 = wxNewId()
static const long ID_STATICTEXT1 = wxNewId()
static const long ID_TEXTCTRL2 = wxNewId()
static const long ID_BUTTON6 = wxNewId()
static const long ID_BUTTON7 = wxNewId()
static const long ID_CHECKBOX2 = wxNewId()
static const long ID_STATICTEXT5 = wxNewId()
static const long ID_TEXTCTRL5 = wxNewId()
static const long ID_STATICTEXT6 = wxNewId()
static const long ID_TEXTCTRL6 = wxNewId()
static const long ID_STATICTEXT2 = wxNewId()
static const long ID_TEXTCTRL3 = wxNewId()
static const long ID_STATICTEXT4 = wxNewId()
static const long ID_STATICTEXT3 = wxNewId()
static const long ID_TEXTCTRL4 = wxNewId()
static const long ID_BUTTON4 = wxNewId()
static const long ID_BUTTON5 = wxNewId()
static const long ID_PANEL1 = wxNewId()
static const long ID_CUSTOM1 = wxNewId()
static const long ID_TEXTCTRL1 = wxNewId()
static const long ID_STATUSBAR1 = wxNewId()
static const long ID_TIMER1 = wxNewId()
static const long ID_CHECKBOX3 = wxNewId()
static const long ID_BUTTON8 = wxNewId()
static const long ID_MENUITEM_SET_reactivenav_TARGET = wxNewId()
Detailed Description
Definition at line 48 of file ReactiveNavigationDemoMain.h.
Constructor & Destructor Documentation
ReactiveNavigationDemoFrame::ReactiveNavigationDemoFrame (wxWindow * parent, wxWindowID id = -1)
Definition at line 227 of file ReactiveNavigationDemoMain.cpp.
References EDIT_internalCfgReactive, EDIT_internalCfgRobot, CIniEditor::edText, iniEditoreactivenav, OnbtnEditNavParamsClick(), OnbtnEditRobotParamsClick(), OnbtnExitClick(), OnbtnNavigateClick(), OnbtnPauseClick(), OnbtnStartClick(), OncbInternalParamsClick(), OnplotMouseMove(), OnrbExtMapSelect(), OnreactivenavTargetMenu(), and OntimSimulateTrigger().
ReactiveNavigationDemoFrame::~ReactiveNavigationDemoFrame () [virtual]
Definition at line 440 of file ReactiveNavigationDemoMain.cpp.
References iniEditoreactivenav, iniEditorRobot, and reacNavObj.
Member Function Documentation
void ReactiveNavigationDemoFrame::OnAbout (wxCommandEvent & event)
Definition at line 457 of file ReactiveNavigationDemoMain.cpp.
void ReactiveNavigationDemoFrame::OnbtnEditNavParamsClick (wxCommandEvent & event)
Definition at line 797 of file ReactiveNavigationDemoMain.cpp.
References EDIT_internalCfgReactive, CIniEditor::edText, and iniEditoreactivenav.
Referenced by ReactiveNavigationDemoFrame().
void ReactiveNavigationDemoFrame::OnbtnEditRobotParamsClick (wxCommandEvent & event)
Definition at line 790 of file ReactiveNavigationDemoMain.cpp.
References EDIT_internalCfgRobot, and CIniEditor::edText.
Referenced by ReactiveNavigationDemoFrame().
void ReactiveNavigationDemoFrame::OnbtnExitClick (wxCommandEvent & event)
Definition at line 491 of file ReactiveNavigationDemoMain.cpp.
Referenced by ReactiveNavigationDemoFrame().
void ReactiveNavigationDemoFrame::OnbtnNavigateClick (wxCommandEvent & event)
Definition at line 569 of file ReactiveNavigationDemoMain.cpp.
References mrpt::reactivenav::YclopsNavigationSystem::navigate(), and reacNavObj.
Referenced by ReactiveNavigationDemoFrame().
void ReactiveNavigationDemoFrame::OnbtnPauseClick (wxCommandEvent & event)
Definition at line 483 of file ReactiveNavigationDemoMain.cpp.
Referenced by ReactiveNavigationDemoFrame().
void ReactiveNavigationDemoFrame::OnbtnResetClick (wxCommandEvent & event)
Definition at line 786 of file ReactiveNavigationDemoMain.cpp.
void ReactiveNavigationDemoFrame::OnbtnStartClick (wxCommandEvent & event)
Definition at line 461 of file ReactiveNavigationDemoMain.cpp.
References reacNavObj, and SIMULATION_TIME_STEPS.
Referenced by ReactiveNavigationDemoFrame().
void ReactiveNavigationDemoFrame::OncbInternalParamsClick (wxCommandEvent & event)
Definition at line 809 of file ReactiveNavigationDemoMain.cpp.
Referenced by ReactiveNavigationDemoFrame().
void ReactiveNavigationDemoFrame::OncbInternalParamsClick1 (wxCommandEvent & event)
void ReactiveNavigationDemoFrame::OnLoadPointsFileClick (wxCommandEvent & event)
Definition at line 877 of file ReactiveNavigationDemoMain.cpp.
References pointsFileLoaded, reacNavObj, mrpt::reactivenav::YclopsNavigationSystem::setChallenge(), mrpt::reactivenav::YclopsNavigationSystem::setFileName(), and mrpt::reactivenav::YclopsNavigationSystem::setup().
void ReactiveNavigationDemoFrame::OnplotMouseMove (wxMouseEvent & event)
Definition at line 665 of file ReactiveNavigationDemoMain.cpp.
References curCursorPos.
Referenced by ReactiveNavigationDemoFrame().
void ReactiveNavigationDemoFrame::OnQuit (wxCommandEvent & event)
Definition at line 452 of file ReactiveNavigationDemoMain.cpp.
void ReactiveNavigationDemoFrame::OnrbExtMapSelect (wxCommandEvent & event)
Definition at line 804 of file ReactiveNavigationDemoMain.cpp.
Referenced by ReactiveNavigationDemoFrame().
void ReactiveNavigationDemoFrame::OnreactivenavTargetMenu (wxCommandEvent & event)
Definition at line 678 of file ReactiveNavigationDemoMain.cpp.
References curCursorPos.
Referenced by ReactiveNavigationDemoFrame().
void ReactiveNavigationDemoFrame::OnSelectMapClick (wxCommandEvent & event)
Definition at line 898 of file ReactiveNavigationDemoMain.cpp.
void ReactiveNavigationDemoFrame::OntimSimulateTrigger (wxTimerEvent & event)
Definition at line 686 of file ReactiveNavigationDemoMain.cpp.
References reacNavObj, robotSim(), SIMULATION_TIME_STEPS, WX_END_TRY, and WX_START_TRY.
Referenced by ReactiveNavigationDemoFrame().
bool ReactiveNavigationDemoFrame::reloadMap ()
Definition at line 608 of file ReactiveNavigationDemoMain.cpp.
References gridMap.
void ReactiveNavigationDemoFrame::reloadRobotShape ()
Definition at line 759 of file ReactiveNavigationDemoMain.cpp.
References createConfigSources().
void ReactiveNavigationDemoFrame::tryConstructReactiveNavigator ()
Definition at line 531 of file ReactiveNavigationDemoMain.cpp.
References createConfigSources(), ENABLE_reactivenav_LOG_FILES, mrpt::reactivenav::YclopsNavigationSystem::loadConfigFile(), myReactiveInterface, and reacNavObj.
Member Data Documentation
wxButton* ReactiveNavigationDemoFrame::btnEditNavParams
Definition at line 122 of file ReactiveNavigationDemoMain.h.
wxButton* ReactiveNavigationDemoFrame::btnEditRobotParams
Definition at line 133 of file ReactiveNavigationDemoMain.h.
wxButton* ReactiveNavigationDemoFrame::btnExit
Definition at line 123 of file ReactiveNavigationDemoMain.h.
wxButton* ReactiveNavigationDemoFrame::btnLoadMapsFile
Definition at line 136 of file ReactiveNavigationDemoMain.h.
wxButton* ReactiveNavigationDemoFrame::btnLoadPointsFile
Definition at line 134 of file ReactiveNavigationDemoMain.h.
wxButton* ReactiveNavigationDemoFrame::btnNavigate
Definition at line 118 of file ReactiveNavigationDemoMain.h.
wxButton* ReactiveNavigationDemoFrame::btnPause
Definition at line 119 of file ReactiveNavigationDemoMain.h.
wxButton* ReactiveNavigationDemoFrame::btnStart
Definition at line 131 of file ReactiveNavigationDemoMain.h.
wxCheckBox* ReactiveNavigationDemoFrame::cbExtMap
Definition at line 120 of file ReactiveNavigationDemoMain.h.
wxCheckBox* ReactiveNavigationDemoFrame::cbInternalParams
Definition at line 132 of file ReactiveNavigationDemoMain.h.
Referenced by createConfigSources().
wxCheckBox* ReactiveNavigationDemoFrame::cbTSP
Definition at line 135 of file ReactiveNavigationDemoMain.h.
wxTextCtrl* ReactiveNavigationDemoFrame::edLog
Definition at line 124 of file ReactiveNavigationDemoMain.h.
wxTextCtrl* ReactiveNavigationDemoFrame::edMapFile
Definition at line 111 of file ReactiveNavigationDemoMain.h.
wxTextCtrl* ReactiveNavigationDemoFrame::edNavCfgFile
Definition at line 125 of file ReactiveNavigationDemoMain.h.
Referenced by createConfigSources().
wxTextCtrl* ReactiveNavigationDemoFrame::edRobotCfgFile
Definition at line 117 of file ReactiveNavigationDemoMain.h.
Referenced by createConfigSources().
wxTextCtrl* ReactiveNavigationDemoFrame::edX
Definition at line 113 of file ReactiveNavigationDemoMain.h.
wxTextCtrl* ReactiveNavigationDemoFrame::edY
Definition at line 115 of file ReactiveNavigationDemoMain.h.
const long ReactiveNavigationDemoFrame::ID_BUTTON1 = wxNewId() [static]
Definition at line 79 of file ReactiveNavigationDemoMain.h.
const long ReactiveNavigationDemoFrame::ID_BUTTON2 = wxNewId() [static]
Definition at line 80 of file ReactiveNavigationDemoMain.h.
const long ReactiveNavigationDemoFrame::ID_BUTTON3 = wxNewId() [static]
Definition at line 81 of file ReactiveNavigationDemoMain.h.
const long ReactiveNavigationDemoFrame::ID_BUTTON4 = wxNewId() [static]
Definition at line 97 of file ReactiveNavigationDemoMain.h.
const long ReactiveNavigationDemoFrame::ID_BUTTON5 = wxNewId() [static]
Definition at line 98 of file ReactiveNavigationDemoMain.h.
const long ReactiveNavigationDemoFrame::ID_BUTTON6 = wxNewId() [static]
Definition at line 85 of file ReactiveNavigationDemoMain.h.
const long ReactiveNavigationDemoFrame::ID_BUTTON7 = wxNewId() [static]
Definition at line 86 of file ReactiveNavigationDemoMain.h.
const long ReactiveNavigationDemoFrame::ID_BUTTON8 = wxNewId() [static]
Definition at line 105 of file ReactiveNavigationDemoMain.h.
const long ReactiveNavigationDemoFrame::ID_CHECKBOX1 = wxNewId() [static]
Definition at line 82 of file ReactiveNavigationDemoMain.h.
const long ReactiveNavigationDemoFrame::ID_CHECKBOX2 = wxNewId() [static]
Definition at line 87 of file ReactiveNavigationDemoMain.h.
const long ReactiveNavigationDemoFrame::ID_CHECKBOX3 = wxNewId() [static]
Definition at line 104 of file ReactiveNavigationDemoMain.h.
const long ReactiveNavigationDemoFrame::ID_CUSTOM1 = wxNewId() [static]
Definition at line 100 of file ReactiveNavigationDemoMain.h.
const long ReactiveNavigationDemoFrame::ID_MENUITEM_SET_reactivenav_TARGET = wxNewId() [static]
Definition at line 108 of file ReactiveNavigationDemoMain.h.
const long ReactiveNavigationDemoFrame::ID_PANEL1 = wxNewId() [static]
Definition at line 99 of file ReactiveNavigationDemoMain.h.
const long ReactiveNavigationDemoFrame::ID_STATICTEXT1 = wxNewId() [static]
Definition at line 83 of file ReactiveNavigationDemoMain.h.
const long ReactiveNavigationDemoFrame::ID_STATICTEXT2 = wxNewId() [static]
Definition at line 92 of file ReactiveNavigationDemoMain.h.
const long ReactiveNavigationDemoFrame::ID_STATICTEXT3 = wxNewId() [static]
Definition at line 95 of file ReactiveNavigationDemoMain.h.
const long ReactiveNavigationDemoFrame::ID_STATICTEXT4 = wxNewId() [static]
Definition at line 94 of file ReactiveNavigationDemoMain.h.
const long ReactiveNavigationDemoFrame::ID_STATICTEXT5 = wxNewId() [static]
Definition at line 88 of file ReactiveNavigationDemoMain.h.
const long ReactiveNavigationDemoFrame::ID_STATICTEXT6 = wxNewId() [static]
Definition at line 90 of file ReactiveNavigationDemoMain.h.
const long ReactiveNavigationDemoFrame::ID_STATUSBAR1 = wxNewId() [static]
Definition at line 102 of file ReactiveNavigationDemoMain.h.
const long ReactiveNavigationDemoFrame::ID_TEXTCTRL1 = wxNewId() [static]
Definition at line 101 of file ReactiveNavigationDemoMain.h.
const long ReactiveNavigationDemoFrame::ID_TEXTCTRL2 = wxNewId() [static]
Definition at line 84 of file ReactiveNavigationDemoMain.h.
const long ReactiveNavigationDemoFrame::ID_TEXTCTRL3 = wxNewId() [static]
Definition at line 93 of file ReactiveNavigationDemoMain.h.
const long ReactiveNavigationDemoFrame::ID_TEXTCTRL4 = wxNewId() [static]
Definition at line 96 of file ReactiveNavigationDemoMain.h.
const long ReactiveNavigationDemoFrame::ID_TEXTCTRL5 = wxNewId() [static]
Definition at line 89 of file ReactiveNavigationDemoMain.h.
const long ReactiveNavigationDemoFrame::ID_TEXTCTRL6 = wxNewId() [static]
Definition at line 91 of file ReactiveNavigationDemoMain.h.
const long ReactiveNavigationDemoFrame::ID_TIMER1 = wxNewId() [static]
Definition at line 103 of file ReactiveNavigationDemoMain.h.
mpBitmapLayer* ReactiveNavigationDemoFrame::lyGridmap
Definition at line 141 of file ReactiveNavigationDemoMain.h.
mpPolygon * ReactiveNavigationDemoFrame::lyTarget
Definition at line 142 of file ReactiveNavigationDemoMain.h.
mpPolygon* ReactiveNavigationDemoFrame::lyVehicle
Definition at line 142 of file ReactiveNavigationDemoMain.h.
CMyRedirector* ReactiveNavigationDemoFrame::myRedirector
Definition at line 144 of file ReactiveNavigationDemoMain.h.
wxPanel* ReactiveNavigationDemoFrame::Panel1
Definition at line 112 of file ReactiveNavigationDemoMain.h.
mpWindow* ReactiveNavigationDemoFrame::plot
Definition at line 114 of file ReactiveNavigationDemoMain.h.
wxStaticText* ReactiveNavigationDemoFrame::StaticText2
Definition at line 128 of file ReactiveNavigationDemoMain.h.
wxStaticText* ReactiveNavigationDemoFrame::StaticText3
Definition at line 121 of file ReactiveNavigationDemoMain.h.
wxStaticText* ReactiveNavigationDemoFrame::StaticText4
Definition at line 126 of file ReactiveNavigationDemoMain.h.
wxStaticText* ReactiveNavigationDemoFrame::StaticText5
Definition at line 127 of file ReactiveNavigationDemoMain.h.
wxStaticText* ReactiveNavigationDemoFrame::StaticText6
Definition at line 129 of file ReactiveNavigationDemoMain.h.
wxStatusBar* ReactiveNavigationDemoFrame::StatusBar1
Definition at line 116 of file ReactiveNavigationDemoMain.h.
wxTimer ReactiveNavigationDemoFrame::timSimulate
Definition at line 130 of file ReactiveNavigationDemoMain.h.
The documentation for this class was generated from the following files:
/home/tallred3/ecen493/SeniorProject/trunk/Code/Simulator/Simulator/ReactiveNavigationDemoMain.h
AI/Sim/ReactiveNavigationDemoMain.cpp
/home/tallred3/ecen493/SeniorProject/trunk/Code/Simulator/Simulator/ReactiveNavigationDemoMain.cpp