YClops: ColorSegment Class Reference
ColorSegment Class Reference
#include <ColorSegment.h>
Public Member Functions
ColorSegment ()
~ColorSegment ()
void TestRGB (string imageName)
void TestYCrCb (string imageName)
Mat TestThreshold (string imageName)
Mat TestThreshold (Mat &image)
void TestThresholdVideo ()
void saveRGBtoHSV (string imageName)
void saveImages ()
Mat detectLines (Mat &src)
Private Member Functions
vector< Mat > RGBtoHSV (Mat &image)
vector< Mat > RGBtoYCrCb (Mat &image)
Mat getOrange (Mat &image)
Mat getWhite (Mat &image)
Detailed Description
Definition at line 22 of file ColorSegment.h.
Constructor & Destructor Documentation
ColorSegment::ColorSegment ()
Definition at line 65 of file ColorSegment.cpp.
ColorSegment::~ColorSegment ()
Definition at line 69 of file ColorSegment.cpp.
Member Function Documentation
Mat ColorSegment::detectLines (Mat & src)
Definition at line 73 of file ColorSegment.cpp.
Referenced by main().
Mat ColorSegment::getOrange (Mat & image) [private]
Definition at line 242 of file ColorSegment.cpp.
Referenced by TestThreshold(), and TestThresholdVideo().
Mat ColorSegment::getWhite (Mat & image) [private]
Definition at line 230 of file ColorSegment.cpp.
vector< Mat > ColorSegment::RGBtoHSV (Mat & image) [private]
Definition at line 260 of file ColorSegment.cpp.
Referenced by TestThreshold(), and TestThresholdVideo().
vector< Mat > ColorSegment::RGBtoYCrCb (Mat & image) [private]
Definition at line 276 of file ColorSegment.cpp.
Referenced by TestYCrCb().
void ColorSegment::saveImages ()
Definition at line 323 of file ColorSegment.cpp.
void ColorSegment::saveRGBtoHSV (string imageName)
Definition at line 288 of file ColorSegment.cpp.
void ColorSegment::TestRGB (string imageName)
Definition at line 104 of file ColorSegment.cpp.
Mat ColorSegment::TestThreshold (Mat & image)
Definition at line 188 of file ColorSegment.cpp.
References getOrange(), and RGBtoHSV().
Mat ColorSegment::TestThreshold (string imageName)
Definition at line 152 of file ColorSegment.cpp.
References getOrange(), and RGBtoHSV().
Referenced by main().
void ColorSegment::TestThresholdVideo ()
Definition at line 197 of file ColorSegment.cpp.
References getOrange(), and RGBtoHSV().
void ColorSegment::TestYCrCb (string imageName)
Definition at line 130 of file ColorSegment.cpp.
References RGBtoYCrCb().
The documentation for this class was generated from the following files:
Sensors/Camera/ColorSegment.h
Sensors/Camera/ColorSegment.cpp