YClops: GPS Class Reference
GPS Class Reference
#include <GPS.h>
Classes
class GPSStringer
class NovatelGPSStringer
class PocketMaxGPSStringer
Public Member Functions
GPS (const int Buffer_Length=500)
void loadConfiguration (const mrpt::utils::CConfigFileBase &config, const std::string &sectionName)
void init ()
void sensorProcess ()
SensorData * getData ()
void dumpData (std::ostream &out) const
virtual ~GPS ()
double GetDistanceToWaypoint (double lat, double lon) const
double GetDistanceToWaypoint (double lat1, double lon1, double lat2, double lon2) const
double GetGpsSpeed () const
double GetGpsDirection () const
double GetGpsLatitude () const
double GetGpsLongitude () const
mrpt::poses::CPoint2D GetCurrentGpsLocation () const
Private Member Functions
void initializeCom ()
void initConfig (mrpt::utils::CConfigFileBase &configSource, const std::string &iniSection="GPS")
bool usesGpgga () const
bool usesGprmc () const
Private Attributes
bool isGpggaUsed
bool isGprmcUsed
int baudRate
int processRate
double testLat
double testLon
GPSStringer * gpsStrings
CGenericSensor::TListObservations lstObs
CGenericSensor::TListObservations::iterator itObs
mrpt::slam::CObservationGPSPtr gpsData
Detailed Description
Definition at line 25 of file GPS.h.
Constructor & Destructor Documentation
GPS::GPS (const int Buffer_Length = 500)
Definition at line 21 of file GPS.cpp.
GPS::~GPS () [virtual]
Definition at line 161 of file GPS.cpp.
References gpsStrings.
Member Function Documentation
void GPS::dumpData (std::ostream & out) const
dumps data out to the parameter out
Parameters:
out - the stream to which to write the data
Reimplemented from YClopsSensor.
Definition at line 122 of file GPS.cpp.
References GetDistanceToWaypoint(), GetGpsLatitude(), GetGpsLongitude(), gpsData, lstObs, testLat, and testLon.
Referenced by YClopsReactiveNavInterface::getCurrentPoseAndSpeeds(), and testGPSShowData().
CPoint2D GPS::GetCurrentGpsLocation () const
Definition at line 205 of file GPS.cpp.
References GetGpsLatitude(), and GetGpsLongitude().
SensorData * GPS::getData () [virtual]
SensorData needs to be allocated on the heap to avoid splicing when we cast it to be a various sensor type
Implements YClopsSensor.
Definition at line 104 of file GPS.cpp.
References gpsData.
Referenced by YClopsReactiveNavInterface::getCurrentPoseAndSpeeds().
double GPS::GetDistanceToWaypoint (double lat, double lon) const
Definition at line 166 of file GPS.cpp.
References GetGpsLatitude(), GetGpsLongitude(), and AbstractNavigationInterface::haversineDistance().
Referenced by accuracyTest(), and dumpData().
double GPS::GetDistanceToWaypoint (double lat1, double lon1, double lat2, double lon2) const
Definition at line 170 of file GPS.cpp.
References AbstractNavigationInterface::haversineDistance().
double GPS::GetGpsDirection () const
Definition at line 181 of file GPS.cpp.
References DEBUG3, gpsData, and LOG_GPS.
double GPS::GetGpsLatitude () const
Definition at line 191 of file GPS.cpp.
References gpsData.
Referenced by accuracyTest(), dumpData(), GetCurrentGpsLocation(), and GetDistanceToWaypoint().
double GPS::GetGpsLongitude () const
Definition at line 198 of file GPS.cpp.
References gpsData.
Referenced by accuracyTest(), dumpData(), GetCurrentGpsLocation(), and GetDistanceToWaypoint().
double GPS::GetGpsSpeed () const
Definition at line 174 of file GPS.cpp.
References gpsData.
void GPS::init () [virtual]
initialize the sensor
Implements YClopsSensor.
Definition at line 66 of file GPS.cpp.
References DEBUG3, gpsData, initializeCom(), LOG_GPS, lstObs, and WARNING.
Referenced by YClopsReactiveNavInterface::YClopsReactiveNavInterface().
void GPS::initConfig (mrpt::utils::CConfigFileBase & configSource, const std::string & iniSection = "GPS") [private]
Referenced by initGPS(), and testGPSInitialize().
void GPS::initializeCom () [private]
Definition at line 217 of file GPS.cpp.
References baudRate, GPS::GPSStringer::clearCommand, GPS::GPSStringer::clearCommandResponse, DEBUG3, FATAL, GPS::GPSStringer::ggaCommand, gpsStrings, isGpggaUsed, isGprmcUsed, LOG_GPS, GPS::GPSStringer::portName, processRate, GPS::GPSStringer::rmcCommand, and GPS::GPSStringer::vendor.
Referenced by init().
void GPS::loadConfiguration (const mrpt::utils::CConfigFileBase & config, const std::string & sectionName) [virtual]
load sensor specific values from the configuration file
Implements YClopsSensor.
Definition at line 24 of file GPS.cpp.
References baudRate, DEBUG3, FATAL, gpsStrings, isGpggaUsed, isGprmcUsed, LOG_GPS, GPS::GPSStringer::NOVATEL, GPS::GPSStringer::POCKETMAX, processRate, testLat, and testLon.
Referenced by YClopsReactiveNavInterface::YClopsReactiveNavInterface().
void GPS::sensorProcess () [virtual]
collect data from the sensor and cache it
Implements YClopsSensor.
Definition at line 86 of file GPS.cpp.
References DEBUG3, gpsData, itObs, LOG_GPS, lstObs, and WARNING.
Referenced by YClopsReactiveNavInterface::getCurrentPoseAndSpeeds().
bool GPS::usesGpgga () const [inline, private]
Definition at line 138 of file GPS.h.
References isGprmcUsed.
bool GPS::usesGprmc () const [inline, private]
Definition at line 141 of file GPS.h.
Member Data Documentation
int GPS::baudRate [private]
Definition at line 120 of file GPS.h.
Referenced by initializeCom(), and loadConfiguration().
mrpt::slam::CObservationGPSPtr GPS::gpsData [private]
Definition at line 128 of file GPS.h.
Referenced by dumpData(), getData(), GetGpsDirection(), GetGpsLatitude(), GetGpsLongitude(), GetGpsSpeed(), init(), and sensorProcess().
GPSStringer* GPS::gpsStrings [private]
Definition at line 124 of file GPS.h.
Referenced by initializeCom(), loadConfiguration(), and ~GPS().
bool GPS::isGpggaUsed [private]
Definition at line 118 of file GPS.h.
Referenced by initializeCom(), and loadConfiguration().
bool GPS::isGprmcUsed [private]
Definition at line 119 of file GPS.h.
Referenced by initializeCom(), loadConfiguration(), and usesGpgga().
CGenericSensor::TListObservations::iterator GPS::itObs [private]
Definition at line 127 of file GPS.h.
Referenced by sensorProcess().
CGenericSensor::TListObservations GPS::lstObs [private]
Definition at line 126 of file GPS.h.
Referenced by dumpData(), init(), and sensorProcess().
int GPS::processRate [private]
Definition at line 121 of file GPS.h.
Referenced by initializeCom(), and loadConfiguration().
double GPS::testLat [private]
Definition at line 122 of file GPS.h.
Referenced by dumpData(), and loadConfiguration().
double GPS::testLon [private]
Definition at line 123 of file GPS.h.
Referenced by dumpData(), and loadConfiguration().
The documentation for this class was generated from the following files:
/home/tallred3/ecen493/SeniorProject/trunk/Code/YClopsLib/inc/GPS.h
/home/tallred3/ecen493/SeniorProject/trunk/Code/YClopsLib/src/GPS.cpp