YClops: CMyRedirector Class Reference
CMyRedirector Class Reference
#include <CMyRedirector.h>
Public Member Functions
CMyRedirector (wxTextCtrl *obj, bool yieldApplication=false, int bufferSize=3000, bool also_cerr=false, bool threadSafe=false, bool also_to_cout_cerr=false)
virtual ~CMyRedirector ()
void flush ()
virtual void writeString (const std::string &str)
void dumpNow ()
CMyRedirector (wxTextCtrl *obj, bool yieldApplication=false, int bufferSize=3000, bool also_cerr=false, bool threadSafe=false, bool also_to_cout_cerr=false)
virtual ~CMyRedirector ()
void flush ()
virtual void writeString (const std::string &str)
void dumpNow ()
Protected Attributes
wxTextCtrl * m_txt
std::streambuf * sbOld
std::streambuf * sbOldErr
const bool m_yieldApplication
const bool m_also_cerr
const bool m_threadSafe
const bool m_also_to_cout_cerr
wxCriticalSection m_cs
std::string m_strbuf
Private Member Functions
int overflow (int c)
int sync ()
int overflow (int c)
int sync ()
Detailed Description
This auxiliary class redirects the output sent to a streambuf to a wxTextCtrl object. Uses code from http://www.devmaster.net/forums/showthread.php?t=7037 Jose Luis Blanco - Dec 2007 NOTE (10-Aug-2009): Added thread-safe support: We cannot write in a wxTextCtrl from a thread different than the main wx one, so if this object will be used by several threads, set "m_threadSafe" to true. In this mode, the object will NEVER write the text to the text control, unless the method "dumpNow()" is explicitly called FROM THE MAIN THREAD.
Definition at line 47 of file CMyRedirector.h.
Constructor & Destructor Documentation
CMyRedirector::CMyRedirector (wxTextCtrl * obj, bool yieldApplication = false, int bufferSize = 3000, bool also_cerr = false, bool threadSafe = false, bool also_to_cout_cerr = false) [inline]
Definition at line 62 of file CMyRedirector.h.
References m_also_cerr, sbOld, and sbOldErr.
virtual CMyRedirector::~CMyRedirector () [inline, virtual]
Definition at line 88 of file CMyRedirector.h.
References m_also_cerr, sbOld, sbOldErr, and sync().
CMyRedirector::CMyRedirector (wxTextCtrl * obj, bool yieldApplication = false, int bufferSize = 3000, bool also_cerr = false, bool threadSafe = false, bool also_to_cout_cerr = false) [inline]
Definition at line 62 of file CMyRedirector.h.
References m_also_cerr, sbOld, and sbOldErr.
virtual CMyRedirector::~CMyRedirector () [inline, virtual]
Definition at line 88 of file CMyRedirector.h.
References m_also_cerr, sbOld, sbOldErr, and sync().
Member Function Documentation
void CMyRedirector::dumpNow () [inline]
Writes all the stored strings to the text control (only for threadSafe mode). CALL THIS METHOD FROM THE MAIN THREAD!
Definition at line 127 of file CMyRedirector.h.
References m_also_to_cout_cerr, m_cs, m_strbuf, and m_txt.
void CMyRedirector::dumpNow () [inline]
Writes all the stored strings to the text control (only for threadSafe mode). CALL THIS METHOD FROM THE MAIN THREAD!
Definition at line 127 of file CMyRedirector.h.
References m_also_to_cout_cerr, m_cs, m_strbuf, and m_txt.
void CMyRedirector::flush () [inline]
Definition at line 101 of file CMyRedirector.h.
References sync().
void CMyRedirector::flush () [inline]
Definition at line 101 of file CMyRedirector.h.
References sync().
int CMyRedirector::overflow (int c) [inline, private]
Definition at line 144 of file CMyRedirector.h.
References m_cs, sync(), and writeString().
int CMyRedirector::overflow (int c) [inline, private]
Definition at line 144 of file CMyRedirector.h.
References m_cs, sync(), and writeString().
int CMyRedirector::sync () [inline, private]
Definition at line 164 of file CMyRedirector.h.
References m_cs, and writeString().
Referenced by flush(), overflow(), and ~CMyRedirector().
int CMyRedirector::sync () [inline, private]
Definition at line 164 of file CMyRedirector.h.
References m_cs, and writeString().
virtual void CMyRedirector::writeString (const std::string & str) [inline, virtual]
Definition at line 106 of file CMyRedirector.h.
References m_also_to_cout_cerr, m_strbuf, m_threadSafe, m_txt, and m_yieldApplication.
virtual void CMyRedirector::writeString (const std::string & str) [inline, virtual]
Definition at line 106 of file CMyRedirector.h.
References m_also_to_cout_cerr, m_strbuf, m_threadSafe, m_txt, and m_yieldApplication.
Referenced by overflow(), and sync().
Member Data Documentation
const bool CMyRedirector::m_also_cerr [protected]
Definition at line 54 of file CMyRedirector.h.
Referenced by CMyRedirector(), and ~CMyRedirector().
const bool CMyRedirector::m_also_to_cout_cerr [protected]
Definition at line 56 of file CMyRedirector.h.
Referenced by dumpNow(), and writeString().
wxCriticalSection CMyRedirector::m_cs [protected]
Definition at line 58 of file CMyRedirector.h.
Referenced by dumpNow(), overflow(), and sync().
std::string CMyRedirector::m_strbuf [protected]
Definition at line 59 of file CMyRedirector.h.
Referenced by dumpNow(), and writeString().
const bool CMyRedirector::m_threadSafe [protected]
Definition at line 55 of file CMyRedirector.h.
Referenced by writeString().
wxTextCtrl * CMyRedirector::m_txt [protected]
Definition at line 50 of file CMyRedirector.h.
Referenced by dumpNow(), and writeString().
const bool CMyRedirector::m_yieldApplication [protected]
Definition at line 53 of file CMyRedirector.h.
Referenced by writeString().
std::streambuf * CMyRedirector::sbOld [protected]
Definition at line 51 of file CMyRedirector.h.
Referenced by CMyRedirector(), and ~CMyRedirector().
std::streambuf * CMyRedirector::sbOldErr [protected]
Definition at line 52 of file CMyRedirector.h.
Referenced by CMyRedirector(), and ~CMyRedirector().
The documentation for this class was generated from the following files:
/home/tallred3/ecen493/SeniorProject/trunk/Code/Simulator/Simulator/CMyRedirector.h
/home/tallred3/ecen493/SeniorProject/trunk/Code/Simulator/Simulator/wx-common/CMyRedirector.h