YClops: Camera Class Reference
Camera Class Reference
#include <Camera.h>
Public Member Functions
Camera ()
virtual ~Camera ()
void loadConfiguration (const mrpt::utils::CConfigFileBase &config, const std::string &sectionName)
void init ()
void sensorProcess ()
SensorData * getData ()
void getObstacles (mrpt::slam::CSimplePointsMap &map)
void dumpData (std::ostream &out) const
Private Member Functions
void getFrame (cv::Mat &image)
void insertObstacles (mrpt::slam::CSimplePointsMap &map, int size, bool *array)
void hasObstacles (bool *array, cv::Mat &image)
void getWhite (cv::Mat &image)
void distort (cv::Mat &src)
void initializeArray (bool *array)
std::vector< cv::Mat > convertRGBtoHSV (cv::Mat &image)
Static Private Member Functions
static void * cameraDataShow (void *)
Private Attributes
cv::VideoCapture capture
cv::Mat image
bool * array
mrpt::slam::CSimplePointsMap * map
pthread_t dataDumpThread
pthread_attr_t dataDumpThreadAttr
double PERCENT_FILLED
int GRID_SIZE
int THRESHOLD
int ERODE_AMOUNT
int HSV_VECTOR
Static Private Attributes
static bool killThread = false
Detailed Description
Definition at line 31 of file Camera.h.
Constructor & Destructor Documentation
Camera::Camera ()
Definition at line 21 of file Camera.cpp.
Camera::~Camera () [virtual]
Definition at line 24 of file Camera.cpp.
References array, dataDumpThread, DEBUG3, killThread, LOG_CAMERA, and map.
Member Function Documentation
void * Camera::cameraDataShow (void * dataShow) [static, private]
Definition at line 157 of file Camera.cpp.
References killThread.
Referenced by init().
vector< Mat > Camera::convertRGBtoHSV (cv::Mat & image) [private]
Definition at line 288 of file Camera.cpp.
Referenced by getWhite().
void Camera::distort (cv::Mat & src) [private]
Definition at line 246 of file Camera.cpp.
Referenced by getObstacles().
void Camera::dumpData (std::ostream & out) const
dumps data out to the parameter out
Parameters:
out - the stream to which to write the data
Reimplemented from YClopsSensor.
Definition at line 132 of file Camera.cpp.
References map.
Referenced by YClopsReactiveNavInterface::senseObstacles().
SensorData * Camera::getData () [virtual]
SensorData needs to be allocated on the heap to avoid splicing when we cast it to be a various sensor type
Implements YClopsSensor.
Definition at line 94 of file Camera.cpp.
References map.
void Camera::getFrame (cv::Mat & image) [private]
Definition at line 99 of file Camera.cpp.
References capture, and image.
Referenced by getObstacles(), and init().
void Camera::getObstacles (mrpt::slam::CSimplePointsMap & map)
Definition at line 103 of file Camera.cpp.
References array, DEBUG3, DEBUG_COMMAND, distort(), getFrame(), getWhite(), GRID_SIZE, hasObstacles(), image, initializeArray(), insertObstacles(), and LOG_CAMERA.
Referenced by main(), and sensorProcess().
void Camera::getWhite (cv::Mat & image) [private]
Definition at line 219 of file Camera.cpp.
References convertRGBtoHSV(), ERODE_AMOUNT, HSV_VECTOR, and THRESHOLD.
Referenced by getObstacles().
void Camera::hasObstacles (bool * array, cv::Mat & image) [private]
Definition at line 191 of file Camera.cpp.
References DEBUG4, DEBUG_COMMAND, GRID_SIZE, image, LOG_CAMERA, and PERCENT_FILLED.
Referenced by getObstacles().
void Camera::init () [virtual]
initialize the sensor
Implements YClopsSensor.
Definition at line 60 of file Camera.cpp.
References array, cameraDataShow(), capture, dataDumpThread, dataDumpThreadAttr, DEBUG3, FATAL, getFrame(), GRID_SIZE, image, LOG_CAMERA, and map.
Referenced by main(), and YClopsReactiveNavInterface::YClopsReactiveNavInterface().
void Camera::initializeArray (bool * array) [inline, private]
Definition at line 282 of file Camera.cpp.
References GRID_SIZE.
Referenced by getObstacles().
void Camera::insertObstacles (mrpt::slam::CSimplePointsMap & map, int size, bool * array) [private]
Definition at line 167 of file Camera.cpp.
Referenced by getObstacles().
void Camera::loadConfiguration (const mrpt::utils::CConfigFileBase & config, const std::string & sectionName) [virtual]
load sensor specific values from the configuration file
Implements YClopsSensor.
Definition at line 35 of file Camera.cpp.
References DEBUG3, ERODE_AMOUNT, FATAL, GRID_SIZE, HSV_VECTOR, LOG_CAMERA, PERCENT_FILLED, and THRESHOLD.
Referenced by main(), and YClopsReactiveNavInterface::YClopsReactiveNavInterface().
void Camera::sensorProcess () [virtual]
collect data from the sensor and cache it
Implements YClopsSensor.
Definition at line 80 of file Camera.cpp.
References DEBUG3, getObstacles(), LOG_CAMERA, and map.
Referenced by YClopsReactiveNavInterface::senseObstacles().
Member Data Documentation
bool* Camera::array [private]
Definition at line 60 of file Camera.h.
Referenced by getObstacles(), init(), and ~Camera().
cv::VideoCapture Camera::capture [private]
Definition at line 58 of file Camera.h.
Referenced by getFrame(), and init().
pthread_t Camera::dataDumpThread [private]
Definition at line 64 of file Camera.h.
Referenced by init(), and ~Camera().
pthread_attr_t Camera::dataDumpThreadAttr [private]
Definition at line 65 of file Camera.h.
Referenced by init().
int Camera::ERODE_AMOUNT [private]
Definition at line 70 of file Camera.h.
Referenced by getWhite(), and loadConfiguration().
int Camera::GRID_SIZE [private]
Definition at line 68 of file Camera.h.
Referenced by getObstacles(), hasObstacles(), init(), initializeArray(), and loadConfiguration().
int Camera::HSV_VECTOR [private]
Definition at line 71 of file Camera.h.
Referenced by getWhite(), and loadConfiguration().
cv::Mat Camera::image [private]
Definition at line 59 of file Camera.h.
Referenced by getFrame(), getObstacles(), hasObstacles(), and init().
bool Camera::killThread = false [static, private]
Definition at line 63 of file Camera.h.
Referenced by cameraDataShow(), and ~Camera().
mrpt::slam::CSimplePointsMap* Camera::map [private]
Definition at line 61 of file Camera.h.
Referenced by dumpData(), getData(), init(), sensorProcess(), and ~Camera().
double Camera::PERCENT_FILLED [private]
Definition at line 67 of file Camera.h.
Referenced by hasObstacles(), and loadConfiguration().
int Camera::THRESHOLD [private]
Definition at line 69 of file Camera.h.
Referenced by getWhite(), and loadConfiguration().
The documentation for this class was generated from the following files:
/home/tallred3/ecen493/SeniorProject/trunk/Code/YClopsLib/inc/Camera.h
/home/tallred3/ecen493/SeniorProject/trunk/Code/YClopsLib/src/Camera.cpp