YClops: SimpleNavigation Class Reference
SimpleNavigation Class Reference
#include <SimpleNavigation.h>
Public Member Functions
SimpleNavigation (std::string &fileName, mrpt::reactivenav::CReactiveInterfaceImplementation *interface)
virtual ~SimpleNavigation ()
void setFileName (std::string &fileName, bool inMeters)
void navigate (mrpt::reactivenav::CAbstractReactiveNavigationSystem::TNavigationParams *navParams)
void go ()
void navigationStep ()
void loadConfigFile (mrpt::utils::CConfigFileBase &interfaceConfig, mrpt::utils::CConfigFileBase &robotConfig)
mrpt::reactivenav::CAbstractReactiveNavigationSystem::TState getCurrentState ()
Private Member Functions
void gotoNextPoint ()
float distance (mrpt::poses::CPose2D &curPose)
double calcBearing (mrpt::poses::CPose2D &curPose)
Private Attributes
std::string fileName
bool inMeters
mrpt::reactivenav::CReactiveInterfaceImplementation * interface
mrpt::aligned_containers
< mrpt::poses::CPoint2D >
::vector_t points
mrpt::reactivenav::CAbstractReactiveNavigationSystem::TState state
mrpt::reactivenav::CAbstractReactiveNavigationSystem::TNavigationParams * navParams
Detailed Description
Definition at line 20 of file SimpleNavigation.h.
Constructor & Destructor Documentation
SimpleNavigation::SimpleNavigation (std::string & fileName, mrpt::reactivenav::CReactiveInterfaceImplementation * interface)
Definition at line 16 of file SimpleNavigation.cpp.
SimpleNavigation::~SimpleNavigation () [virtual]
Definition at line 19 of file SimpleNavigation.cpp.
References interface.
Member Function Documentation
double SimpleNavigation::calcBearing (mrpt::poses::CPose2D & curPose) [inline, private]
Definition at line 40 of file SimpleNavigation.h.
Referenced by navigationStep().
float SimpleNavigation::distance (mrpt::poses::CPose2D & curPose) [inline, private]
Definition at line 29 of file SimpleNavigation.h.
Referenced by navigationStep().
mrpt::reactivenav::CAbstractReactiveNavigationSystem::TState SimpleNavigation::getCurrentState () [inline]
Definition at line 59 of file SimpleNavigation.h.
void SimpleNavigation::go ()
Definition at line 30 of file SimpleNavigation.cpp.
References fileName, gotoNextPoint(), inMeters, interface, AbstractNavigationInterface::loadPoints(), points, and TSPNavigation::solve().
Referenced by main().
void SimpleNavigation::gotoNextPoint () [private]
Definition at line 56 of file SimpleNavigation.cpp.
References navigate(), navParams, and points.
Referenced by go(), and navigationStep().
void SimpleNavigation::loadConfigFile (mrpt::utils::CConfigFileBase & interfaceConfig, mrpt::utils::CConfigFileBase & robotConfig) [inline]
Definition at line 58 of file SimpleNavigation.h.
void SimpleNavigation::navigate (mrpt::reactivenav::CAbstractReactiveNavigationSystem::TNavigationParams * navParams)
Definition at line 71 of file SimpleNavigation.cpp.
References navParams, points, and state.
Referenced by gotoNextPoint().
void SimpleNavigation::navigationStep ()
Definition at line 88 of file SimpleNavigation.cpp.
References calcBearing(), DEBUG, DEBUG4, distance(), gotoNextPoint(), INFO, interface, LOG_AI, navParams, points, and state.
void SimpleNavigation::setFileName (std::string & fileName, bool inMeters)
Member Data Documentation
std::string SimpleNavigation::fileName [private]
Definition at line 22 of file SimpleNavigation.h.
Referenced by go(), and mrpt::reactivenav::YclopsNavigationSystem::setFileName().
bool SimpleNavigation::inMeters [private]
Definition at line 23 of file SimpleNavigation.h.
Referenced by go(), and mrpt::reactivenav::YclopsNavigationSystem::setFileName().
mrpt::reactivenav::CReactiveInterfaceImplementation* SimpleNavigation::interface [private]
Definition at line 24 of file SimpleNavigation.h.
Referenced by go(), navigationStep(), and ~SimpleNavigation().
mrpt::reactivenav::CAbstractReactiveNavigationSystem::TNavigationParams* SimpleNavigation::navParams [private]
Definition at line 27 of file SimpleNavigation.h.
Referenced by gotoNextPoint(), navigate(), and navigationStep().
mrpt::aligned_containers<mrpt::poses::CPoint2D>::vector_t SimpleNavigation::points [private]
Definition at line 25 of file SimpleNavigation.h.
Referenced by go(), gotoNextPoint(), navigate(), and navigationStep().
mrpt::reactivenav::CAbstractReactiveNavigationSystem::TState SimpleNavigation::state [private]
Definition at line 26 of file SimpleNavigation.h.
Referenced by navigate(), and navigationStep().
The documentation for this class was generated from the following files:
/home/tallred3/ecen493/SeniorProject/trunk/Code/YClopsLib/inc/SimpleNavigation.h
/home/tallred3/ecen493/SeniorProject/trunk/Code/YClopsLib/src/SimpleNavigation.cpp