YClops: tkhl::TSPDriver Class Reference
tkhl::TSPDriver Class Reference
#include <ACO.h>
Public Member Functions
void UpdateTrial ()
void initmap ()
void GetAnt ()
void StartSearch ()
TSPDriver (mrpt::aligned_containers< mrpt::poses::CPoint2D >::vector_t &toVisit)
Public Attributes
double m_dLength
TSPAnt ants [iAntCount]
Private Member Functions
double getDistance (double lat1, double lon1, double lat2, double lon2)
Detailed Description
Definition at line 185 of file ACO.h.
Constructor & Destructor Documentation
tkhl::TSPDriver::TSPDriver (mrpt::aligned_containers< mrpt::poses::CPoint2D >::vector_t & toVisit)
Definition at line 273 of file ACO.h.
References tkhl::besttour, tkhl::TSPGInfo::distance, getDistance(), tkhl::iCityCount, initmap(), tkhl::LAT, tkhl::LON, m_dLength, and tkhl::Map.
Member Function Documentation
void tkhl::TSPDriver::GetAnt ()
Definition at line 307 of file ACO.h.
References tkhl::TSPAnt::addcity(), ants, tkhl::iAntCount, tkhl::iCityCount, and tkhl::rnd().
Referenced by TSPNavigation::acoTSPSolution().
double tkhl::TSPDriver::getDistance (double lat1, double lon1, double lat2, double lon2) [private]
Definition at line 382 of file ACO.h.
Referenced by TSPDriver().
void tkhl::TSPDriver::initmap ()
Definition at line 226 of file ACO.h.
References tkhl::iCityCount, tkhl::TSPGInfo::m_dDeltTrial, tkhl::TSPGInfo::m_dTrial, and tkhl::Map.
Referenced by TSPDriver().
void tkhl::TSPDriver::StartSearch ()
Definition at line 322 of file ACO.h.
References ants, tkhl::besttour, tkhl::iAntCount, tkhl::iCityCount, tkhl::iItCount, m_dLength, tkhl::TSPAnt::m_dLength, tkhl::TSPAnt::move2last(), tkhl::TSPAnt::UpdateResult(), and UpdateTrial().
Referenced by TSPNavigation::acoTSPSolution().
void tkhl::TSPDriver::UpdateTrial ()
Definition at line 199 of file ACO.h.
References ants, tkhl::iAntCount, tkhl::iCityCount, tkhl::TSPGInfo::m_dDeltTrial, tkhl::TSPAnt::m_dLength, tkhl::TSPGInfo::m_dTrial, tkhl::Map, tkhl::Q, tkhl::rou, and tkhl::TSPAnt::tabu.
Referenced by StartSearch().
Member Data Documentation
TSPAnt tkhl::TSPDriver::ants[iAntCount]
Definition at line 192 of file ACO.h.
Referenced by GetAnt(), StartSearch(), and UpdateTrial().
double tkhl::TSPDriver::m_dLength
Definition at line 190 of file ACO.h.
Referenced by StartSearch(), and TSPDriver().
The documentation for this class was generated from the following file:
Sensors/MultiSensorLib/inc/ACO.h