YClops: DualMotorCommand Class Reference
DualMotorCommand Class Reference
#include <MotorCommandInterface.h>
Public Member Functions
DualMotorCommand ()
virtual ~DualMotorCommand ()
void doProcess ()
Detailed Description
Definition at line 55 of file MotorCommandInterface.h.
Constructor & Destructor Documentation
DualMotorCommand::DualMotorCommand ()
Definition at line 45 of file MotorCommandInterface.cpp.
DualMotorCommand::~DualMotorCommand () [virtual]
Definition at line 47 of file MotorCommandInterface.cpp.
Member Function Documentation
void DualMotorCommand::doProcess () [virtual]
doProcess - abstract function implements the functionality of the command
Implements MotorCommandInterface.
Definition at line 49 of file MotorCommandInterface.cpp.
References MotorController::Channel1, MotorController::Channel2, DEBUG, MotorController::doProcess(), WiiController::getLeftStick(), WiiController::getReference(), WiiController::getRightStick(), MotorController::instance(), LOG, and MotorController::setSpeed().
The documentation for this class was generated from the following files:
/home/tallred3/ecen493/SeniorProject/trunk/Code/YClopsLib/inc/MotorCommandInterface.h
MotorControllerResponseParsing/MotorCommandInterface.cpp
/home/tallred3/ecen493/SeniorProject/trunk/Code/YClopsLib/src/MotorCommandInterface.cpp