YClops: AI/Sim/ReactiveNavigationDemoMain.cpp File Reference
AI/Sim/ReactiveNavigationDemoMain.cpp File Reference
#include "ReactiveNavigationDemoMain.h"
#include <Yclopsnav.h>
#include "CIniEditor.h"
#include <wx/msgdlg.h>
#include <wx/filename.h>
#include <wx/settings.h>
#include <wx/string.h>
#include <wx/intl.h>
#include <wx/font.h>
#include <wx/bitmap.h>
#include <wx/icon.h>
#include <wx/image.h>
#include <wx/artprov.h>
#include <mrpt/gui/WxUtils.h>
#include "imgs/main_icon.xpm"
#include "../wx-common/mrpt_logo.xpm"
#include "DEFAULT_GRIDMAP_DATA.h"
#include <mrpt/maps.h>
#include <mrpt/reactivenav/CReactiveNavigationSystem.h>
Classes
class MyArtProvider
class CMyReactInterface
Defines
#define SIMULATION_TIME_STEPS 100
#define ENABLE_reactivenav_LOG_FILES false
#define WX_START_TRY
#define WX_END_TRY
Functions
CRobotSimulator robotSim (1e-9f, 0)
void emul_printf (const char *s)
void createConfigSources (ReactiveNavigationDemoFrame *frame, CConfigFileBase *&iniReactive, CConfigFileBase *&configRobotIni)
Variables
std::string EDIT_internalCfgReactive
std::string EDIT_internalCfgRobot
CIniEditor * iniEditorRobot = NULL
CIniEditor * iniEditoreactivenav = NULL
YclopsNavigationSystem * reacNavObj = NULL
COccupancyGridMap2D gridMap
TPoint2D curCursorPos
CMyReactInterface myReactiveInterface
Define Documentation
#define ENABLE_reactivenav_LOG_FILES false
Definition at line 39 of file ReactiveNavigationDemoMain.cpp.
#define SIMULATION_TIME_STEPS 100
Definition at line 36 of file ReactiveNavigationDemoMain.cpp.
#define WX_END_TRY
Value:
} \
        catch(std::exception &e) \
    { \
        wxMessageBox( wxString(e.what(),wxConvUTF8), wxT("Exception"), wxOK, this); \
    } \
    catch(...) \
    { \
        wxMessageBox( _("Untyped exception!"), _("Exception"), wxOK, this); \
    }
Definition at line 61 of file ReactiveNavigationDemoMain.cpp.
#define WX_START_TRY
Value:
try \
    {
Definition at line 56 of file ReactiveNavigationDemoMain.cpp.
Function Documentation
void createConfigSources (ReactiveNavigationDemoFrame * frame, CConfigFileBase *& iniReactive, CConfigFileBase *& configRobotIni)
Definition at line 497 of file ReactiveNavigationDemoMain.cpp.
References EDIT_internalCfgRobot.
void emul_printf (const char * s)
Definition at line 222 of file ReactiveNavigationDemoMain.cpp.
CRobotSimulator robotSim (1e- 9f, 0)
Referenced by CMyReactInterface::changeSpeeds(), CMyReactInterface::getCurrentPoseAndSpeeds(), and CMyReactInterface::senseObstacles().
Variable Documentation
TPoint2D curCursorPos
Definition at line 128 of file ReactiveNavigationDemoMain.cpp.
std::string EDIT_internalCfgReactive
Definition at line 75 of file ReactiveNavigationDemoMain.cpp.
std::string EDIT_internalCfgRobot
Definition at line 76 of file ReactiveNavigationDemoMain.cpp.
Referenced by createConfigSources().
COccupancyGridMap2D gridMap
Definition at line 126 of file ReactiveNavigationDemoMain.cpp.
Referenced by CMyReactInterface::senseObstacles().
CIniEditor * iniEditoreactivenav = NULL
Definition at line 78 of file ReactiveNavigationDemoMain.cpp.
CIniEditor* iniEditorRobot = NULL
Definition at line 78 of file ReactiveNavigationDemoMain.cpp.
CMyReactInterface myReactiveInterface
Definition at line 184 of file ReactiveNavigationDemoMain.cpp.
YclopsNavigationSystem* reacNavObj = NULL
Definition at line 123 of file ReactiveNavigationDemoMain.cpp.