YClops: Sensors/GPS/main.cpp File Reference
Sensors/GPS/main.cpp File Reference
#include <iostream>
#include <fstream>
#include <iomanip>
#include <cassert>
#include <cstdio>
#include <cstring>
#include <vector>
#include <mrpt/hwdrivers/CGPSInterface.h>
#include "GPS.h"
#include "WaypointPlanner.h"
Defines
#define length 7
Functions
double GetGpsSpeed ()
double GetGpsDirection ()
double GetGpsLat ()
double GetGpsLon ()
double GetDistanceToWaypoint (double lon, double lat)
double GetDistanceToWaypoint (double lat1, double lon1, double lat2, double lon2)
int main ()
Variables
CObservationGPSPtr gpsData
bool TESTING = true
double PrevPosLat
double PrevPosLon
const double metersToFeet = 3.2808399
Define Documentation
#define length 7
Definition at line 23 of file main.cpp.
Function Documentation
double GetDistanceToWaypoint (double lon, double lat)
Definition at line 69 of file main.cpp.
References gpsData, and AbstractNavigationInterface::haversineDistance().
Referenced by main().
double GetDistanceToWaypoint (double lat1, double lon1, double lat2, double lon2)
Definition at line 73 of file main.cpp.
References AbstractNavigationInterface::haversineDistance().
double GetGpsDirection ()
Definition at line 49 of file main.cpp.
References gpsData.
double GetGpsLat ()
Definition at line 55 of file main.cpp.
References gpsData.
double GetGpsLon ()
Definition at line 62 of file main.cpp.
References gpsData.
double GetGpsSpeed ()
Definition at line 44 of file main.cpp.
References gpsData.
int main ()
Definition at line 78 of file main.cpp.
References GetDistanceToWaypoint(), gpsData, GPS::initConfig(), GPS::initialize(), metersToFeet, PrevPosLat, PrevPosLon, TESTING, GPS::usesGpgga(), and GPS::usesGprmc().
Variable Documentation
CObservationGPSPtr gpsData
Definition at line 33 of file main.cpp.
Referenced by YclopsReactiveNavInterface::getCurrentPoseAndSpeeds(), GetDistanceToWaypoint(), GetGpsDirection(), GetGpsLat(), GetGpsLon(), GetGpsSpeed(), main(), and YclopsReactiveNavInterface::YclopsReactiveNavInterface().
const double metersToFeet = 3.2808399
Definition at line 39 of file main.cpp.
Referenced by main().
double PrevPosLat
Definition at line 37 of file main.cpp.
Referenced by main().
double PrevPosLon
Definition at line 38 of file main.cpp.
Referenced by main().
bool TESTING = true
Definition at line 35 of file main.cpp.
Referenced by main().