YClops: /home/tallred3/ecen493/SeniorProject/trunk/Code/YClopsLib/src/WiiController.cpp File Reference
/home/tallred3/ecen493/SeniorProject/trunk/Code/YClopsLib/src/WiiController.cpp File Reference
#include "WiiController.h"
#include "logging.h"
#include <iostream>
#include <signal.h>
#include <cstdlib>
#include <unistd.h>
#include <bluetooth/hci.h>
#include <bluetooth/hci_lib.h>
Functions
void cwiid_callback (cwiid_wiimote_t *wiimote, int mesg_count, union cwiid_mesg mesg[], struct timespec *timestamp)
Variables
cwiid_mesg_callback_t cwiid_callback
Detailed Description
Date:
Feb 4, 2011
Author:
Thomas Eldon Allred
Definition in file WiiController.cpp.
Function Documentation
void cwiid_callback (cwiid_wiimote_t * wiimote, int mesg_count, union cwiid_mesg mesg[], struct timespec * timestamp)
Definition at line 84 of file WiiController.cpp.
References DEBUG4, ERROR, WiiController::getReference(), LOG_WII, WiiController::process_btn_mesg(), and WiiController::process_classic_mesg().
Variable Documentation
cwiid_mesg_callback_t cwiid_callback
Definition at line 20 of file WiiController.cpp.
Referenced by WiiController::WiiController().