YClops: Sensors/GPSandCompassUnitTest/main.cpp File Reference
Sensors/GPSandCompassUnitTest/main.cpp File Reference
#include <iostream>
#include <fstream>
#include <iomanip>
#include <cassert>
#include <cstdio>
#include <cstring>
#include <vector>
#include <mrpt/hwdrivers/CGPSInterface.h>
#include <mrpt/utils/CConfigFile.h>
#include <mrpt/hwdrivers/CGenericSensor.h>
#include "GPS.h"
#include "WaypointPlanner.h"
#include "Compass.h"
Functions
bool testGPSInitialize (GPS *gps, CConfigFile *config)
bool testGPSConnection (GPS *gps)
bool testGPSShowData (GPS *gps, unsigned numOfRecord)
bool testCompassInitialize (Compass *compass, CConfigFile *config)
bool testCompassConnection (Compass *compass)
bool testCompassShowData (Compass *compass, int numOfRecord)
bool testCompassAndGPSConnections (GPS *gps, Compass *compass)
bool testCompassAndGPSShowData (GPS *gps, Compass *compass)
int main (int argc, char **argv)
Variables
CObservationGPSPtr gpsData
CGenericSensor::TListObservations lstObs
CGenericSensor::TListObservations::iterator itObs
bool outside = false
const double metersToFeet = 3.2808399
Function Documentation
int main (int argc, char ** argv)
Definition at line 150 of file main.cpp.
References testCompassConnection(), testCompassInitialize(), testCompassShowData(), testGPSInitialize(), and testGPSShowData().
bool testCompassAndGPSConnections (GPS * gps, Compass * compass)
Definition at line 138 of file main.cpp.
References testCompassConnection(), and testGPSConnection().
bool testCompassAndGPSShowData (GPS * gps, Compass * compass)
Definition at line 143 of file main.cpp.
References testCompassShowData(), and testGPSShowData().
bool testCompassConnection (Compass * compass)
Definition at line 118 of file main.cpp.
Referenced by main(), and testCompassAndGPSConnections().
bool testCompassInitialize (Compass * compass, CConfigFile * config)
Definition at line 112 of file main.cpp.
Referenced by main().
bool testCompassShowData (Compass * compass, int numOfRecord)
Definition at line 125 of file main.cpp.
References Compass::dumpData(), and Compass::getPitch().
Referenced by main(), and testCompassAndGPSShowData().
bool testGPSConnection (GPS * gps)
Definition at line 82 of file main.cpp.
Referenced by testCompassAndGPSConnections().
bool testGPSInitialize (GPS * gps, CConfigFile * config)
Definition at line 56 of file main.cpp.
References gpsData, GPS::initConfig(), lstObs, and outside.
Referenced by main().
bool testGPSShowData (GPS * gps, unsigned numOfRecord)
Definition at line 87 of file main.cpp.
References GPS::dumpData(), gpsData, itObs, and lstObs.
Referenced by main(), and testCompassAndGPSShowData().
Variable Documentation
CObservationGPSPtr gpsData
Definition at line 31 of file main.cpp.
Referenced by YClopsReactiveNavInterface::getCurrentPoseAndSpeeds(), main(), testGPSInitialize(), and testGPSShowData().
CGenericSensor::TListObservations::iterator itObs
Definition at line 33 of file main.cpp.
Referenced by main(), and testGPSShowData().
CGenericSensor::TListObservations lstObs
Definition at line 32 of file main.cpp.
Referenced by main(), testGPSInitialize(), and testGPSShowData().
const double metersToFeet = 3.2808399
Definition at line 36 of file main.cpp.
bool outside = false
Definition at line 34 of file main.cpp.
Referenced by testGPSInitialize().