YClops: main.cpp File Reference
main.cpp File Reference
#include <iostream>
#include <fstream>
#include <iomanip>
#include <cassert>
#include <cstdio>
#include <cstring>
#include <vector>
#include <mrpt/hwdrivers/CGPSInterface.h>
#include "GPS.h"
#include "WaypointPlanner.h"
Defines
#define reps 1800
Functions
void accuracyTest (GPS *gps)
int main ()
Define Documentation
#define reps 1800
Definition at line 33 of file branches/Sensors/GPS/main.cpp.
Referenced by accuracyTest().
Function Documentation
void accuracyTest (GPS * gps)
Definition at line 39 of file branches/Sensors/GPS/main.cpp.
References GPS::GetDistanceToWaypoint(), GPS::GetGpsLatitude(), GPS::GetGpsLongitude(), and reps.
Referenced by main().
int main ()
Definition at line 83 of file branches/Sensors/GPS/main.cpp.
References accuracyTest().