YClops: Mechanical/WiiDriver/main.cpp File Reference
Mechanical/WiiDriver/main.cpp File Reference
#include <iostream>
#include <stdlib.h>
#include <signal.h>
#include <cassert>
#include "MotorController.h"
#include "MotorCommandInterface.h"
#include "Compass.h"
#include "WiiController.h"
#include "YClopsReactiveNavInterface.h"
#include "YclopsNavigationSystem.h"
#include "Beeper.h"
#include "logging.h"
#include "YClopsConfiguration.h"
#include <mrpt/hwdrivers/CSerialPort.h>
Functions
void signal_handler (int signum)
void shutdown (int exitStatus)
int main (int argc, char **argv)
Variables
bool closing = false
LOG_LEVEL loggingLevel = DEBUG4
YClopsReactiveNavInterface * yclops = NULL
ofstream of
mrpt::reactivenav::YclopsNavigationSystem * ai = NULL
const string DEFAULT_POINTS_FILE = "points.txt"
Function Documentation
int main (int argc, char ** argv)
Definition at line 38 of file main.cpp.
References ai, ALL_LOG, YClopsReactiveNavInterface::changeSpeeds(), closing, WiiController::create(), DEBUG, DEBUG4, YClopsReactiveNavInterface::getCurrentPoseAndSpeeds(), Log::GetOStream(), YClopsConfiguration::instance(), mrpt::reactivenav::YclopsNavigationSystem::loadConfigFile(), LOG, loggingLevel, of, YClopsReactiveNavInterface::senseObstacles(), YClopsConfiguration::setConfigFile(), Log::SetLogFile(), Log::SetReportLevel(), Log::SetReportStreamBits(), Log::SetTimeStampDisplay(), shutdown(), signal_handler(), YClopsReactiveNavInterface::useNullMotorCommand(), WII_LOG, and yclops.
void shutdown (int exitStatus)
Definition at line 286 of file main.cpp.
References WiiController::destroyReference(), INFO, LOG, and yclops.
Referenced by main(), and signal_handler().
void signal_handler (int signum)
Definition at line 108 of file main.cpp.
References ai, Beeper::beep(), CLASSIC_A, CLASSIC_B, CLASSIC_D_DOWN, CLASSIC_D_LEFT, CLASSIC_D_RIGHT, CLASSIC_D_UP, CLASSIC_HOME, CLASSIC_L1, CLASSIC_L2, CLASSIC_R1, CLASSIC_R2, CLASSIC_SELECT, CLASSIC_START, CLASSIC_X, CLASSIC_Y, closing, DEBUG, DEBUG2, DEBUG3, DEBUG4, DISABLE, ERROR, FATAL, WiiController::getClassicButtons(), WiiController::getLeftAnalog(), WiiController::getLeftStick(), WiiController::getMoteButtons(), Log::GetOStream(), WiiController::getReference(), WiiController::getRightAnalog(), WiiController::getRightStick(), INFO, YClopsConfiguration::instance(), LOG, LOG_WII, loggingLevel, MOTE_1, MOTE_2, MOTE_A, MOTE_B, MOTE_D_DOWN, MOTE_D_LEFT, MOTE_D_RIGHT, MOTE_D_UP, MOTE_HOME, MOTE_MINUS, MOTE_PLUS, YClopsReactiveNavInterface::setAutonomusMode(), mrpt::reactivenav::YclopsNavigationSystem::setChallenge(), mrpt::reactivenav::YclopsNavigationSystem::setFileName(), YClopsReactiveNavInterface::setIdle(), YClopsReactiveNavInterface::setNavigationMode(), Log::SetReportLevel(), mrpt::reactivenav::YclopsNavigationSystem::setup(), shutdown(), mrpt::reactivenav::YclopsNavigationSystem::stop(), YClopsReactiveNavInterface::toggleCameraDump(), YClopsReactiveNavInterface::toggleCompassDump(), YClopsReactiveNavInterface::toggleEncoderDump(), YClopsReactiveNavInterface::toggleGpsDump(), YClopsReactiveNavInterface::toggleLidarDump(), Log::ToString(), YClopsReactiveNavInterface::useNullMotorCommand(), YClopsReactiveNavInterface::useWiiMotorCommand(), WARNING, and yclops.
Referenced by main().
Variable Documentation
mrpt::reactivenav::YclopsNavigationSystem* ai = NULL
Definition at line 35 of file main.cpp.
Referenced by main(), and signal_handler().
bool closing = false
Definition at line 27 of file main.cpp.
Referenced by main(), and signal_handler().
const string DEFAULT_POINTS_FILE = "points.txt"
Definition at line 36 of file main.cpp.
LOG_LEVEL loggingLevel = DEBUG4
Definition at line 31 of file main.cpp.
Referenced by main(), and signal_handler().
ofstream of
Definition at line 34 of file main.cpp.
Referenced by main().
YClopsReactiveNavInterface* yclops = NULL
Definition at line 33 of file main.cpp.
Referenced by main(), shutdown(), and signal_handler().