YClops: YClopsNavigationSystem2 Class Reference
YClopsNavigationSystem2 Class Reference
#include <YClopsNavigationSystem2.h>
Public Member Functions
YClopsNavigationSystem2 (mrpt::utils::CConfigFile &config)
virtual ~YClopsNavigationSystem2 ()
void doProcess ()
void setAutonomusMode ()
void setNavigationMode ()
void setIdle ()
bool toggleGpsDump ()
bool toggleCompassDump ()
bool toggleLidarDump ()
bool toggleCameraDump ()
void useYclopsMotorCommand ()
void useWiiMotorCommand ()
void useNullMotorCommand ()
Private Attributes
bool isGpsDataShown
bool isCompassDataShown
bool isLidarDataShown
bool isCameraDataShown
bool isEncoderDataShown
MotorCommandInterface * motor
Compass * compass
GPS * gps
Camera * camera
mrpt::hwdrivers::CSickLaserSerial * lidar
Detailed Description
Definition at line 18 of file YClopsNavigationSystem2.h.
Constructor & Destructor Documentation
YClopsNavigationSystem2::YClopsNavigationSystem2 (mrpt::utils::CConfigFile & config)
YClopsNavigationSystem2::~YClopsNavigationSystem2 () [virtual]
Definition at line 41 of file YClopsNavigationSystem2.cpp.
References camera, compass, gps, lidar, and motor.
Member Function Documentation
void YClopsNavigationSystem2::doProcess ()
Definition at line 50 of file YClopsNavigationSystem2.cpp.
References camera, compass, Camera::doProcess(), Compass::doProcess(), MotorCommandInterface::doProcess(), Camera::dumpData(), GPS::dumpData(), Compass::dumpData(), gps, isCameraDataShown, isCompassDataShown, isGpsDataShown, isLidarDataShown, lidar, and motor.
void YClopsNavigationSystem2::setAutonomusMode ()
Definition at line 109 of file YClopsNavigationSystem2.cpp.
References useYclopsMotorCommand().
Referenced by signal_handler().
void YClopsNavigationSystem2::setIdle ()
Definition at line 117 of file YClopsNavigationSystem2.cpp.
Referenced by signal_handler().
void YClopsNavigationSystem2::setNavigationMode ()
Definition at line 113 of file YClopsNavigationSystem2.cpp.
References useYclopsMotorCommand().
Referenced by signal_handler().
bool YClopsNavigationSystem2::toggleCameraDump ()
Definition at line 136 of file YClopsNavigationSystem2.cpp.
References isCameraDataShown.
Referenced by signal_handler().
bool YClopsNavigationSystem2::toggleCompassDump ()
Definition at line 126 of file YClopsNavigationSystem2.cpp.
References isCompassDataShown.
Referenced by signal_handler().
bool YClopsNavigationSystem2::toggleGpsDump ()
Definition at line 121 of file YClopsNavigationSystem2.cpp.
References isGpsDataShown.
Referenced by signal_handler().
bool YClopsNavigationSystem2::toggleLidarDump ()
Definition at line 131 of file YClopsNavigationSystem2.cpp.
References isLidarDataShown.
Referenced by signal_handler().
void YClopsNavigationSystem2::useNullMotorCommand ()
useYclopsMotorCommand - makes the YclopsReactiveNavInterface use an instance of the DummyMotorCommand class
Definition at line 153 of file YClopsNavigationSystem2.cpp.
References motor.
Referenced by signal_handler().
void YClopsNavigationSystem2::useWiiMotorCommand ()
useYclopsMotorCommand - makes the YclopsReactiveNavInterface use an instance of the DualMotorCommand class
Definition at line 147 of file YClopsNavigationSystem2.cpp.
References motor.
Referenced by signal_handler().
void YClopsNavigationSystem2::useYclopsMotorCommand ()
useYclopsMotorCommand - makes the YclopsReactiveNavInterface use an instance of the MotorCommand class
Definition at line 141 of file YClopsNavigationSystem2.cpp.
References motor.
Referenced by setAutonomusMode(), and setNavigationMode().
Member Data Documentation
Camera* YClopsNavigationSystem2::camera [private]
Definition at line 62 of file YClopsNavigationSystem2.h.
Referenced by doProcess(), and ~YClopsNavigationSystem2().
Compass* YClopsNavigationSystem2::compass [private]
Definition at line 60 of file YClopsNavigationSystem2.h.
Referenced by doProcess(), and ~YClopsNavigationSystem2().
GPS* YClopsNavigationSystem2::gps [private]
Definition at line 61 of file YClopsNavigationSystem2.h.
Referenced by doProcess(), and ~YClopsNavigationSystem2().
bool YClopsNavigationSystem2::isCameraDataShown [private]
Definition at line 56 of file YClopsNavigationSystem2.h.
Referenced by doProcess(), and toggleCameraDump().
bool YClopsNavigationSystem2::isCompassDataShown [private]
Definition at line 54 of file YClopsNavigationSystem2.h.
Referenced by doProcess(), and toggleCompassDump().
bool YClopsNavigationSystem2::isEncoderDataShown [private]
Definition at line 57 of file YClopsNavigationSystem2.h.
bool YClopsNavigationSystem2::isGpsDataShown [private]
Definition at line 53 of file YClopsNavigationSystem2.h.
Referenced by doProcess(), and toggleGpsDump().
bool YClopsNavigationSystem2::isLidarDataShown [private]
Definition at line 55 of file YClopsNavigationSystem2.h.
Referenced by doProcess(), and toggleLidarDump().
mrpt::hwdrivers::CSickLaserSerial* YClopsNavigationSystem2::lidar [private]
Definition at line 63 of file YClopsNavigationSystem2.h.
Referenced by doProcess(), and ~YClopsNavigationSystem2().
MotorCommandInterface* YClopsNavigationSystem2::motor [private]
Definition at line 59 of file YClopsNavigationSystem2.h.
Referenced by doProcess(), useNullMotorCommand(), useWiiMotorCommand(), useYclopsMotorCommand(), and ~YClopsNavigationSystem2().
The documentation for this class was generated from the following files:
Sensors/MultiSensorLib/inc/YClopsNavigationSystem2.h
Sensors/MultiSensorLib/src/YClopsNavigationSystem2.cpp