YClops: CIniEditor Class Reference
CIniEditor Class Reference
#include <CIniEditor.h>
Public Member Functions
CIniEditor (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)
virtual ~CIniEditor ()
Public Attributes
wxButton * btnCancel
wxTextCtrl * edText
wxButton * btnOK
Static Protected Attributes
static const long ID_BUTTON1 = wxNewId()
static const long ID_BUTTON2 = wxNewId()
static const long ID_TEXTCTRL1 = wxNewId()
Private Member Functions
void OnbtnCancelClick (wxCommandEvent &event)
void OnbtnOKClick (wxCommandEvent &event)
Detailed Description
Definition at line 38 of file CIniEditor.h.
Constructor & Destructor Documentation
CIniEditor::CIniEditor (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize)
Definition at line 50 of file CIniEditor.cpp.
References OnbtnCancelClick(), and OnbtnOKClick().
CIniEditor::~CIniEditor () [virtual]
Definition at line 84 of file CIniEditor.cpp.
Member Function Documentation
void CIniEditor::OnbtnCancelClick (wxCommandEvent & event) [private]
Definition at line 91 of file CIniEditor.cpp.
Referenced by CIniEditor().
void CIniEditor::OnbtnOKClick (wxCommandEvent & event) [private]
Definition at line 96 of file CIniEditor.cpp.
Referenced by CIniEditor().
Member Data Documentation
wxButton* CIniEditor::btnCancel
Definition at line 46 of file CIniEditor.h.
wxButton* CIniEditor::btnOK
Definition at line 48 of file CIniEditor.h.
wxTextCtrl* CIniEditor::edText
Definition at line 47 of file CIniEditor.h.
Referenced by ReactiveNavigationDemoFrame::OnbtnEditNavParamsClick(), ReactiveNavigationDemoFrame::OnbtnEditRobotParamsClick(), and ReactiveNavigationDemoFrame::ReactiveNavigationDemoFrame().
const long CIniEditor::ID_BUTTON1 = wxNewId() [static, protected]
Definition at line 54 of file CIniEditor.h.
const long CIniEditor::ID_BUTTON2 = wxNewId() [static, protected]
Definition at line 55 of file CIniEditor.h.
const long CIniEditor::ID_TEXTCTRL1 = wxNewId() [static, protected]
Definition at line 56 of file CIniEditor.h.
The documentation for this class was generated from the following files:
/home/tallred3/ecen493/SeniorProject/trunk/Code/Simulator/Simulator/CIniEditor.h
/home/tallred3/ecen493/SeniorProject/trunk/Code/Simulator/Simulator/CIniEditor.cpp