YClops: Log Class Reference
Log Class Reference
#include <logging.h>
Public Member Functions
Log ()
virtual ~Log ()
std::stringstream & Get (LOG_LEVEL level=INFO)
Static Public Member Functions
static LOG_LEVEL & ReportingLevel ()
static unsigned int GetReportStreamBits ()
static void SetReportStreamBits (unsigned int s)
static void SetTimeStampDisplay (bool ts)
static void SetReportLevel (LOG_LEVEL level=INFO)
static void SetLogFile (std::ostream *out)
static std::ostream * GetOStream ()
static std::string ToString (LOG_LEVEL level)
Static Protected Member Functions
static std::string GetTime ()
Protected Attributes
std::stringstream os
Private Member Functions
Log (const Log &)
Log & operator= (const Log &)
Private Attributes
LOG_LEVEL messageLevel
Static Private Attributes
static LOG_LEVEL logLevel = INFO
static unsigned int streamBits = ~ALL_LOG
static bool timestamp = true
static std::ostream * outputStream = &(std::cerr)
Detailed Description
Definition at line 64 of file logging.h.
Constructor & Destructor Documentation
Log::Log () [inline]
Definition at line 66 of file logging.h.
Log::~Log () [virtual]
Definition at line 79 of file logging.cpp.
References FATAL, GetOStream(), and ReportingLevel().
Log::Log (const Log &) [private]
Member Function Documentation
std::stringstream & Log::Get (LOG_LEVEL level = INFO)
Definition at line 57 of file logging.cpp.
References DEBUG, GetTime(), timestamp, and ToString().
static std::ostream* Log::GetOStream () [inline, static]
Definition at line 76 of file logging.h.
References outputStream.
Referenced by main(), signal_handler(), and ~Log().
unsigned int Log::GetReportStreamBits () [static]
Definition at line 71 of file logging.cpp.
References streamBits.
std::string Log::GetTime () [static, protected]
Definition at line 20 of file logging.cpp.
Referenced by Get().
Log& Log::operator= (const Log &) [private]
LOG_LEVEL & Log::ReportingLevel () [static]
Definition at line 69 of file logging.cpp.
References logLevel.
Referenced by ~Log().
void Log::SetLogFile (std::ostream * out) [static]
Definition at line 92 of file logging.cpp.
References outputStream.
Referenced by main().
void Log::SetReportLevel (LOG_LEVEL level = INFO) [static]
Definition at line 77 of file logging.cpp.
Referenced by main(), and signal_handler().
void Log::SetReportStreamBits (unsigned int s) [static]
Definition at line 73 of file logging.cpp.
References streamBits.
Referenced by main().
void Log::SetTimeStampDisplay (bool ts) [static]
Definition at line 75 of file logging.cpp.
References timestamp.
Referenced by main().
std::string Log::ToString (LOG_LEVEL level) [static]
Definition at line 25 of file logging.cpp.
References DEBUG, DEBUG2, DEBUG3, DEBUG4, ERROR, FATAL, INFO, and WARNING.
Referenced by Get(), and signal_handler().
Member Data Documentation
LOG_LEVEL Log::logLevel = INFO [static, private]
Definition at line 88 of file logging.h.
Referenced by ReportingLevel().
LOG_LEVEL Log::messageLevel [private]
Definition at line 86 of file logging.h.
std::stringstream Log::os [protected]
Definition at line 79 of file logging.h.
std::ostream * Log::outputStream = &(std::cerr) [static, private]
Definition at line 91 of file logging.h.
Referenced by GetOStream(), and SetLogFile().
unsigned int Log::streamBits = ~ALL_LOG [static, private]
Definition at line 89 of file logging.h.
Referenced by GetReportStreamBits(), and SetReportStreamBits().
bool Log::timestamp = true [static, private]
Definition at line 90 of file logging.h.
Referenced by Get(), and SetTimeStampDisplay().
The documentation for this class was generated from the following files:
/home/tallred3/ecen493/SeniorProject/trunk/Code/YClopsLib/inc/logging.h
/home/tallred3/ecen493/SeniorProject/trunk/Code/YClopsLib/src/logging.cpp