YClops: MotorCommandInterface Class Reference
MotorCommandInterface Class Reference
#include <MotorCommandInterface.h>
Public Member Functions
MotorCommandInterface ()
bool setVelocity (double linearVelocity, double angularVelocity)
virtual void doProcess ()=0
bool getSuccess ()
virtual ~MotorCommandInterface ()
Protected Attributes
double linearVelocity
double angularVelocity
The most recent linearVelocity set.
bool success
The most recent angularVelocity set.
Detailed Description
Definition at line 13 of file MotorCommandInterface.h.
Constructor & Destructor Documentation
MotorCommandInterface::MotorCommandInterface ()
MotorCommandInterface - abstract class to send commands to the motor controller
Parameters:
motorPtr - pointer to the MotorController
Definition at line 15 of file MotorCommandInterface.cpp.
MotorCommandInterface::~MotorCommandInterface () [virtual]
Definition at line 17 of file MotorCommandInterface.cpp.
Member Function Documentation
virtual void MotorCommandInterface::doProcess () [pure virtual]
doProcess - abstract function implements the functionality of the command
Implemented in MotorCommand, DualMotorCommand, and DummyMotorCommand.
Referenced by YClopsReactiveNavInterface::changeSpeeds().
bool MotorCommandInterface::getSuccess ()
Definition at line 25 of file MotorCommandInterface.cpp.
Referenced by YClopsReactiveNavInterface::changeSpeeds().
bool MotorCommandInterface::setVelocity (double linearVelocity, double angularVelocity)
setVelocity - sets the speed for the robot
Parameters:
linearVelocity - the linear speed of the robot
angularVelocity - the angular speed of the robot follows directions on the unit circle eg. left is positive right is negative
Returns:
true upon success
Definition at line 19 of file MotorCommandInterface.cpp.
Referenced by YClopsReactiveNavInterface::changeSpeeds().
Member Data Documentation
double MotorCommandInterface::angularVelocity [protected]
The most recent linearVelocity set.
Definition at line 41 of file MotorCommandInterface.h.
Referenced by MotorCommand::doProcess().
double MotorCommandInterface::linearVelocity [protected]
Definition at line 40 of file MotorCommandInterface.h.
Referenced by MotorCommand::doProcess().
bool MotorCommandInterface::success [protected]
The most recent angularVelocity set.
Definition at line 42 of file MotorCommandInterface.h.
Referenced by MotorCommand::doProcess().
The documentation for this class was generated from the following files:
/home/tallred3/ecen493/SeniorProject/trunk/Code/YClopsLib/inc/MotorCommandInterface.h
MotorControllerResponseParsing/MotorCommandInterface.cpp
/home/tallred3/ecen493/SeniorProject/trunk/Code/YClopsLib/src/MotorCommandInterface.cpp