YClops: YClopsReactiveNavInterface Class Reference
YClopsReactiveNavInterface Class Reference
#include <YClopsReactiveNavInterface.h>
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW YClopsReactiveNavInterface ()
virtual ~YClopsReactiveNavInterface ()
bool getCurrentPoseAndSpeeds (mrpt::poses::CPose2D &curPose, float &curV, float &curW)
bool changeSpeeds (float v, float w)
bool senseObstacles (mrpt::slam::CSimplePointsMap &obstacles)
void setAutonomusMode ()
void setNavigationMode ()
void setIdle ()
bool toggleGpsDump ()
bool toggleCompassDump ()
bool toggleLidarDump ()
bool toggleCameraDump ()
bool toggleEncoderDump ()
void useYclopsMotorCommand ()
void useWiiMotorCommand ()
void useNullMotorCommand ()
Private Attributes
bool isGpsDataShown
bool isCompassDataShown
bool isLidarDataShown
bool isCameraDataShown
bool isEncoderDataShown
MotorCommandInterface * motor
Compass * compass
GPS * gps
Camera * camera
Lidar * lidar
WheelEncoder * encoder
AbstractPoseEstimator * poseEst
mrpt::poses::CPose3D * robotPose
AbstractNavigationInterface * nav
float curV
float curW
Detailed Description
Definition at line 25 of file YClopsReactiveNavInterface.h.
Constructor & Destructor Documentation
YClopsReactiveNavInterface::YClopsReactiveNavInterface ()
Definition at line 20 of file YClopsReactiveNavInterface.cpp.
References camera, compass, curV, curW, DEBUG2, encoder, gps, INFO, WheelEncoder::init(), Lidar::init(), Camera::init(), GPS::init(), Compass::init(), YClopsConfiguration::instance(), lidar, WheelEncoder::loadConfiguration(), Lidar::loadConfiguration(), Camera::loadConfiguration(), GPS::loadConfiguration(), Compass::loadConfiguration(), LOG, motor, poseEst, and robotPose.
YClopsReactiveNavInterface::~YClopsReactiveNavInterface () [virtual]
Definition at line 121 of file YClopsReactiveNavInterface.cpp.
References camera, compass, DEBUG4, encoder, gps, lidar, LOG, motor, nav, poseEst, and robotPose.
Member Function Documentation
bool YClopsReactiveNavInterface::changeSpeeds (float v, float w)
Definition at line 226 of file YClopsReactiveNavInterface.cpp.
References curV, curW, MotorCommandInterface::doProcess(), MotorCommandInterface::getSuccess(), motor, and MotorCommandInterface::setVelocity().
Referenced by NavigationChallenge::AutonomousMode(), and main().
bool YClopsReactiveNavInterface::getCurrentPoseAndSpeeds (mrpt::poses::CPose2D & curPose, float & curV, float & curW)
Definition at line 142 of file YClopsReactiveNavInterface.cpp.
References compass, curV, curW, DEBUG2, DEBUG4, WheelEncoder::dumpData(), GPS::dumpData(), Compass::dumpData(), encoder, WheelEncoder::getData(), GPS::getData(), Compass::getData(), AbstractPoseEstimator::getPose(), AbstractPoseEstimator::getYaw(), gps, gpsData, isCompassDataShown, isEncoderDataShown, isGpsDataShown, LOG, LOG_AI, CompassData::pitch, CompassData::pitchValid, poseEst, robotPose, CompassData::roll, CompassData::rollValid, WheelEncoder::sensorProcess(), GPS::sensorProcess(), Compass::sensorProcess(), AbstractPoseEstimator::update(), CompassData::yaw, and CompassData::yawValid.
Referenced by NavigationChallenge::AutonomousMode(), and main().
bool YClopsReactiveNavInterface::senseObstacles (mrpt::slam::CSimplePointsMap & obstacles)
Definition at line 240 of file YClopsReactiveNavInterface.cpp.
References camera, Lidar::dumpData(), Camera::dumpData(), isCameraDataShown, isLidarDataShown, lidar, Lidar::sensorProcess(), and Camera::sensorProcess().
Referenced by main().
void YClopsReactiveNavInterface::setAutonomusMode ()
Definition at line 262 of file YClopsReactiveNavInterface.cpp.
References nav, robotPose, and useYclopsMotorCommand().
Referenced by signal_handler().
void YClopsReactiveNavInterface::setIdle ()
Definition at line 274 of file YClopsReactiveNavInterface.cpp.
References nav.
Referenced by signal_handler().
void YClopsReactiveNavInterface::setNavigationMode ()
Definition at line 268 of file YClopsReactiveNavInterface.cpp.
References nav, robotPose, and useYclopsMotorCommand().
Referenced by signal_handler().
bool YClopsReactiveNavInterface::toggleCameraDump ()
Definition at line 300 of file YClopsReactiveNavInterface.cpp.
References camera, and isCameraDataShown.
Referenced by signal_handler().
bool YClopsReactiveNavInterface::toggleCompassDump ()
Definition at line 286 of file YClopsReactiveNavInterface.cpp.
References compass, and isCompassDataShown.
Referenced by signal_handler().
bool YClopsReactiveNavInterface::toggleEncoderDump ()
Definition at line 307 of file YClopsReactiveNavInterface.cpp.
References encoder, and isEncoderDataShown.
Referenced by signal_handler().
bool YClopsReactiveNavInterface::toggleGpsDump ()
Definition at line 279 of file YClopsReactiveNavInterface.cpp.
References gps, and isGpsDataShown.
Referenced by signal_handler().
bool YClopsReactiveNavInterface::toggleLidarDump ()
Definition at line 293 of file YClopsReactiveNavInterface.cpp.
References isLidarDataShown, and lidar.
Referenced by signal_handler().
void YClopsReactiveNavInterface::useNullMotorCommand ()
useYclopsMotorCommand - makes the YclopsReactiveNavInterface use an instance of the DummyMotorCommand class
Definition at line 326 of file YClopsReactiveNavInterface.cpp.
References motor.
Referenced by main(), and signal_handler().
void YClopsReactiveNavInterface::useWiiMotorCommand ()
useYclopsMotorCommand - makes the YclopsReactiveNavInterface use an instance of the DualMotorCommand class
Definition at line 320 of file YClopsReactiveNavInterface.cpp.
References motor.
Referenced by signal_handler().
void YClopsReactiveNavInterface::useYclopsMotorCommand ()
useYclopsMotorCommand - makes the YclopsReactiveNavInterface use an instance of the MotorCommand class
Definition at line 314 of file YClopsReactiveNavInterface.cpp.
References motor.
Referenced by setAutonomusMode(), and setNavigationMode().
Member Data Documentation
Camera* YClopsReactiveNavInterface::camera [private]
Definition at line 73 of file YClopsReactiveNavInterface.h.
Referenced by senseObstacles(), toggleCameraDump(), YClopsReactiveNavInterface(), and ~YClopsReactiveNavInterface().
Compass* YClopsReactiveNavInterface::compass [private]
Definition at line 71 of file YClopsReactiveNavInterface.h.
Referenced by getCurrentPoseAndSpeeds(), toggleCompassDump(), YClopsReactiveNavInterface(), and ~YClopsReactiveNavInterface().
float YClopsReactiveNavInterface::curV [private]
Definition at line 82 of file YClopsReactiveNavInterface.h.
Referenced by changeSpeeds(), getCurrentPoseAndSpeeds(), and YClopsReactiveNavInterface().
float YClopsReactiveNavInterface::curW [private]
Definition at line 83 of file YClopsReactiveNavInterface.h.
Referenced by changeSpeeds(), getCurrentPoseAndSpeeds(), and YClopsReactiveNavInterface().
WheelEncoder* YClopsReactiveNavInterface::encoder [private]
Definition at line 75 of file YClopsReactiveNavInterface.h.
Referenced by getCurrentPoseAndSpeeds(), toggleEncoderDump(), YClopsReactiveNavInterface(), and ~YClopsReactiveNavInterface().
GPS* YClopsReactiveNavInterface::gps [private]
Definition at line 72 of file YClopsReactiveNavInterface.h.
Referenced by getCurrentPoseAndSpeeds(), toggleGpsDump(), YClopsReactiveNavInterface(), and ~YClopsReactiveNavInterface().
bool YClopsReactiveNavInterface::isCameraDataShown [private]
Definition at line 67 of file YClopsReactiveNavInterface.h.
Referenced by senseObstacles(), and toggleCameraDump().
bool YClopsReactiveNavInterface::isCompassDataShown [private]
Definition at line 65 of file YClopsReactiveNavInterface.h.
Referenced by getCurrentPoseAndSpeeds(), and toggleCompassDump().
bool YClopsReactiveNavInterface::isEncoderDataShown [private]
Definition at line 68 of file YClopsReactiveNavInterface.h.
Referenced by getCurrentPoseAndSpeeds(), and toggleEncoderDump().
bool YClopsReactiveNavInterface::isGpsDataShown [private]
Definition at line 64 of file YClopsReactiveNavInterface.h.
Referenced by getCurrentPoseAndSpeeds(), and toggleGpsDump().
bool YClopsReactiveNavInterface::isLidarDataShown [private]
Definition at line 66 of file YClopsReactiveNavInterface.h.
Referenced by senseObstacles(), and toggleLidarDump().
Lidar* YClopsReactiveNavInterface::lidar [private]
Definition at line 74 of file YClopsReactiveNavInterface.h.
Referenced by senseObstacles(), toggleLidarDump(), YClopsReactiveNavInterface(), and ~YClopsReactiveNavInterface().
MotorCommandInterface* YClopsReactiveNavInterface::motor [private]
Definition at line 70 of file YClopsReactiveNavInterface.h.
Referenced by changeSpeeds(), useNullMotorCommand(), useWiiMotorCommand(), useYclopsMotorCommand(), YClopsReactiveNavInterface(), and ~YClopsReactiveNavInterface().
AbstractNavigationInterface* YClopsReactiveNavInterface::nav [private]
Definition at line 80 of file YClopsReactiveNavInterface.h.
Referenced by setAutonomusMode(), setIdle(), setNavigationMode(), and ~YClopsReactiveNavInterface().
AbstractPoseEstimator* YClopsReactiveNavInterface::poseEst [private]
Definition at line 77 of file YClopsReactiveNavInterface.h.
Referenced by getCurrentPoseAndSpeeds(), YClopsReactiveNavInterface(), and ~YClopsReactiveNavInterface().
mrpt::poses::CPose3D* YClopsReactiveNavInterface::robotPose [private]
Definition at line 78 of file YClopsReactiveNavInterface.h.
Referenced by getCurrentPoseAndSpeeds(), setAutonomusMode(), setNavigationMode(), YClopsReactiveNavInterface(), and ~YClopsReactiveNavInterface().
The documentation for this class was generated from the following files:
/home/tallred3/ecen493/SeniorProject/trunk/Code/YClopsLib/inc/YClopsReactiveNavInterface.h
/home/tallred3/ecen493/SeniorProject/trunk/Code/YClopsLib/src/YClopsReactiveNavInterface.cpp