YClops: mrpt::reactivenav::YclopsNavigationSystem Class Reference
mrpt::reactivenav::YclopsNavigationSystem Class Reference
#include <Yclopsnav.h>
Classes
class CDynamicWindow
struct THolonomicMovement
Public Types
enum TNavigatorBehavior {
beNormalNavigation = 0, beHeadDirection, beDoorCrosing1, beDoorCrosing2,
beDoorCrosing3, beNormalNavigation = 0, beHeadDirection, beDoorCrosing1,
beDoorCrosing2, beDoorCrosing3, beNormalNavigation = 0, beHeadDirection,
beDoorCrosing1, beDoorCrosing2, beDoorCrosing3
}
enum TNavigatorBehavior {
beNormalNavigation = 0, beHeadDirection, beDoorCrosing1, beDoorCrosing2,
beDoorCrosing3, beNormalNavigation = 0, beHeadDirection, beDoorCrosing1,
beDoorCrosing2, beDoorCrosing3, beNormalNavigation = 0, beHeadDirection,
beDoorCrosing1, beDoorCrosing2, beDoorCrosing3
}
enum TNavigatorBehavior {
beNormalNavigation = 0, beHeadDirection, beDoorCrosing1, beDoorCrosing2,
beDoorCrosing3, beNormalNavigation = 0, beHeadDirection, beDoorCrosing1,
beDoorCrosing2, beDoorCrosing3, beNormalNavigation = 0, beHeadDirection,
beDoorCrosing1, beDoorCrosing2, beDoorCrosing3
}
Public Member Functions
YclopsNavigationSystem (CReactiveInterfaceImplementation &react_iterf_impl, bool enableConsoleOutput=true, bool enableLogFile=false)
virtual ~YclopsNavigationSystem ()
void loadConfigFile (const mrpt::utils::CConfigFileBase &ini, const mrpt::utils::CConfigFileBase &robotIni)
void initialize ()
float evaluate (TNavigationParams *params)
void navigate (TNavigationParams *params)
void setParams (TNavigationParams *params)
void setHolonomicMethod (THolonomicMethod method, const char *config_INIfile="./CONFIG_ReactiveNavigator.ini")
void changeRobotShape (math::CPolygon &shape)
void getLastLogRecord (CLogFileRecord &o)
void enableLogFile (bool enable)
YclopsNavigationSystem (CReactiveInterfaceImplementation &react_iterf_impl, bool enableConsoleOutput=true, bool enableLogFile=false)
virtual ~YclopsNavigationSystem ()
void loadConfigFile (const mrpt::utils::CConfigFileBase &ini, const mrpt::utils::CConfigFileBase &robotIni)
void initialize ()
float evaluate (TNavigationParams *params)
void navigate (TNavigationParams *params)
void setParams (TNavigationParams *params)
void setHolonomicMethod (THolonomicMethod method, const char *config_INIfile="./CONFIG_ReactiveNavigator.ini")
void changeRobotShape (math::CPolygon &shape)
void getLastLogRecord (CLogFileRecord &o)
void enableLogFile (bool enable)
EIGEN_MAKE_ALIGNED_OPERATOR_NEW YclopsNavigationSystem (CReactiveInterfaceImplementation &react_iterf_impl, bool enableConsoleOutput=true, bool enableLogFile=false)
virtual ~YclopsNavigationSystem ()
void loadConfigFile (const mrpt::utils::CConfigFileBase &ini, const mrpt::utils::CConfigFileBase &robotIni)
void initialize ()
float evaluate (TNavigationParams *params)
void navigate (TNavigationParams *params)
void setParams (TNavigationParams *params)
void setFileName (std::string &fileName, bool inMeters)
void setup ()
void stop ()
void setChallenge (bool c)
void getTarget (mrpt::poses::TPoint2D *target)
void setHolonomicMethod (THolonomicMethod method, const char *config_INIfile="./CONFIG_ReactiveNavigator.ini")
void changeRobotShape (math::CPolygon &shape)
void getLastLogRecord (CLogFileRecord &o)
void enableLogFile (bool enable)
Private Member Functions
void performNavigationStep ()
void STEP1_CollisionGridsBuilder ()
bool STEP2_Sense (mrpt::slam::CSimplePointsMap &out_obstacles)
void STEP3_SpaceTransformer (poses::CPointsMap &in_obstacles, CParameterizedTrajectoryGenerator *in_PTG, vector_double &out_TPObstacles)
void STEP4_HolonomicMethod (vector_double &in_Obstacles, poses::CPoint2D &in_Target, float in_maxRobotSpeed, THolonomicMovement &out_selectedMovement, CHolonomicLogFileRecordPtr &in_HLFR)
void STEP5_Evaluator (THolonomicMovement &in_holonomicMovement, vector_double &in_TPObstacles, poses::CPoint2D &WS_Target, poses::CPoint2D &TP_Target, bool wasSelectedInLast, CLogFileRecord::TInfoPerPTG &log)
void STEP6_Selector (std::vector< THolonomicMovement > &in_holonomicMovements, THolonomicMovement &out_selectedHolonomicMovement, int &out_nSelectedPTG)
void STEP7_NonHolonomicMovement (THolonomicMovement &in_movement, float &out_v, float &out_w)
void Error_ParadaDeEmergencia (const char *msg)
void performNavigationStep ()
void STEP1_CollisionGridsBuilder ()
bool STEP2_Sense (mrpt::slam::CSimplePointsMap &out_obstacles)
void STEP3_SpaceTransformer (poses::CPointsMap &in_obstacles, CParameterizedTrajectoryGenerator *in_PTG, vector_double &out_TPObstacles)
void STEP4_HolonomicMethod (vector_double &in_Obstacles, poses::CPoint2D &in_Target, float in_maxRobotSpeed, THolonomicMovement &out_selectedMovement, CHolonomicLogFileRecordPtr &in_HLFR)
void STEP5_Evaluator (THolonomicMovement &in_holonomicMovement, vector_double &in_TPObstacles, poses::CPoint2D &WS_Target, poses::CPoint2D &TP_Target, bool wasSelectedInLast, CLogFileRecord::TInfoPerPTG &log)
void STEP6_Selector (std::vector< THolonomicMovement > &in_holonomicMovements, THolonomicMovement &out_selectedHolonomicMovement, int &out_nSelectedPTG)
void STEP7_NonHolonomicMovement (THolonomicMovement &in_movement, float &out_v, float &out_w)
void Error_ParadaDeEmergencia (const char *msg)
void gotoNextPoint ()
void performNavigationStep ()
void STEP1_CollisionGridsBuilder ()
bool STEP2_Sense (mrpt::slam::CSimplePointsMap &out_obstacles)
void STEP3_SpaceTransformer (poses::CPointsMap &in_obstacles, CParameterizedTrajectoryGenerator *in_PTG, vector_double &out_TPObstacles)
void STEP4_HolonomicMethod (vector_double &in_Obstacles, poses::CPoint2D &in_Target, float in_maxRobotSpeed, THolonomicMovement &out_selectedMovement, CHolonomicLogFileRecordPtr &in_HLFR)
void STEP5_Evaluator (THolonomicMovement &in_holonomicMovement, vector_double &in_TPObstacles, poses::CPoint2D &WS_Target, poses::CPoint2D &TP_Target, bool wasSelectedInLast, CLogFileRecord::TInfoPerPTG &log)
void STEP6_Selector (std::vector< THolonomicMovement > &in_holonomicMovements, THolonomicMovement &out_selectedHolonomicMovement, int &out_nSelectedPTG)
void STEP7_NonHolonomicMovement (THolonomicMovement &in_movement, float &out_v, float &out_w)
void Error_ParadaDeEmergencia (const char *msg)
Private Attributes
TNavigatorBehavior navigatorBehavior
float m_beHeadDirection_rad
CPoint2D m_beAuxTarget
CPoint2D m_bePassPoint1
CPoint2D m_bePassPoint2
CLogFileRecord lastLogRecord
float last_cmd_v
float last_cmd_w
bool navigationEndEventSent
synch::CCriticalSection m_critZoneLastLog
synch::CCriticalSection m_critZoneNavigating
CAbstractHolonomicReactiveMethod * holonomicMethod
utils::CStream * logFile
bool enableConsoleOutput
CTicTac timerForExecutionPeriod
std::string robotName
float refDistance
float colGridRes_x
float colGridRes_y
float robotMax_V_mps
float robotMax_W_degps
float ROBOTMODEL_TAU
float ROBOTMODEL_DELAY
vector_float weights
float minObstaclesHeight
float maxObstaclesHeight
float DIST_TO_TARGET_FOR_SENDING_EVENT
float DOOR_CROSSING_SEARCH_TARGET_DISTANCEx2
float VORONOI_MINIMUM_CLEARANCE
float DISABLE_PERIOD_AFTER_FAIL
float VORONOI_PATH_DIST_FROM_DOORWAY
float DOORCROSSING_HEADING_ACCURACY_DEG
float DOORCROSSING_ROTATION_CTE_DEG
float DOOR_CROSSING_DIST_TO_AUX_TARGETS
float DOOR_CROOSING_BEH3_TIMEOUT
float DOOR_CROSSING_MAXIMUM_DOORWAY_SIZE
unsigned long nIteration
float meanExecutionPeriod
float badNavAlarm_minDistTarget
mrpt::system::TTimeStamp badNavAlarm_lastMinDistTime
float badNavAlarm_AlarmTimeout
math::CPolygon robotShape
bool collisionGridsMustBeUpdated
std::vector
< CParameterizedTrajectoryGenerator * > PTGs
bool CerrandoHilo
bool NavChallenge
float targetAllowedDistance
mrpt::aligned_containers
< mrpt::poses::CPoint2D >
::vector_t points
std::string fileName
bool inMeters
Detailed Description
The implemented reactive navigation methods Implements a reactive navigation system based on TP-Space, with an arbitrary holonomic reactive method running on it, and any desired number of PTG for transforming the navigation space. Both, the holonomic method and the PTGs can be customized by the apropriate user derived classes. For running it, the method NavigateStep must be invoked periodically.
17/JUN/2004: First design.
16/SEP/2004: Totally redesigned, according to document "MultiParametric Based Space Transformation for Reactive Navigation"
29/SEP/2005: Totally rewritten again, for integration into MRPT library and according to the ICRA paper.
17/OCT/2007: Whole code updated to accomodate to MRPT 0.5 and make it portable to Linux.
See also:
CAbstractReactiveNavigationSystem, CParameterizedTrajectoryGenerator, CAbstractHolonomicReactiveMethod
This namespace contains classes for building a TP-Space Reactive Navigation System. The implemented reactive navigation methods Implements a reactive navigation system based on TP-Space, with an arbitrary holonomic reactive method running on it, and any desired number of PTG for transforming the navigation space. Both, the holonomic method and the PTGs can be customized by the apropriate user derived classes. For running it, the method NavigateStep must be invoked periodically.
17/JUN/2004: First design.
16/SEP/2004: Totally redesigned, according to document "MultiParametric Based Space Transformation for Reactive Navigation"
29/SEP/2005: Totally rewritten again, for integration into MRPT library and according to the ICRA paper.
17/OCT/2007: Whole code updated to accomodate to MRPT 0.5 and make it portable to Linux.
See also:
CAbstractReactiveNavigationSystem, CParameterizedTrajectoryGenerator, CAbstractHolonomicReactiveMethod
Definition at line 40 of file Yclopsnav.h.
Member Enumeration Documentation
enum mrpt::reactivenav::YclopsNavigationSystem::TNavigatorBehavior
See 'navigatorBehavior'
Enumerator:
beNormalNavigation
The robot tries to get to the given target point
beHeadDirection
The robot rotates to head the direction "m_beHeadDirection_rad", then goes into normal behavior
beDoorCrosing1
The robot tries to get to a given auxiliar target "m_beAuxTarget", then goes into behavior 'beDoorCrosing2'
beDoorCrosing2
The robot rotates to head the direction "m_beHeadDirection_rad", then goes into behavior 'beDoorCrosing3'
beDoorCrosing3
The robot rotates tries to get to a given auxiliar target "m_beAuxTarget", then goes into normal behavior
beNormalNavigation
The robot tries to get to the given target point
beHeadDirection
The robot rotates to head the direction "m_beHeadDirection_rad", then goes into normal behavior
beDoorCrosing1
The robot tries to get to a given auxiliar target "m_beAuxTarget", then goes into behavior 'beDoorCrosing2'
beDoorCrosing2
The robot rotates to head the direction "m_beHeadDirection_rad", then goes into behavior 'beDoorCrosing3'
beDoorCrosing3
The robot rotates tries to get to a given auxiliar target "m_beAuxTarget", then goes into normal behavior
beNormalNavigation
The robot tries to get to the given target point
beHeadDirection
The robot rotates to head the direction "m_beHeadDirection_rad", then goes into normal behavior
beDoorCrosing1
The robot tries to get to a given auxiliar target "m_beAuxTarget", then goes into behavior 'beDoorCrosing2'
beDoorCrosing2
The robot rotates to head the direction "m_beHeadDirection_rad", then goes into behavior 'beDoorCrosing3'
beDoorCrosing3
The robot rotates tries to get to a given auxiliar target "m_beAuxTarget", then goes into normal behavior
Definition at line 103 of file Yclopsnav.h.
enum mrpt::reactivenav::YclopsNavigationSystem::TNavigatorBehavior
See 'navigatorBehavior'
Enumerator:
beNormalNavigation
The robot tries to get to the given target point
beHeadDirection
The robot rotates to head the direction "m_beHeadDirection_rad", then goes into normal behavior
beDoorCrosing1
The robot tries to get to a given auxiliar target "m_beAuxTarget", then goes into behavior 'beDoorCrosing2'
beDoorCrosing2
The robot rotates to head the direction "m_beHeadDirection_rad", then goes into behavior 'beDoorCrosing3'
beDoorCrosing3
The robot rotates tries to get to a given auxiliar target "m_beAuxTarget", then goes into normal behavior
beNormalNavigation
The robot tries to get to the given target point
beHeadDirection
The robot rotates to head the direction "m_beHeadDirection_rad", then goes into normal behavior
beDoorCrosing1
The robot tries to get to a given auxiliar target "m_beAuxTarget", then goes into behavior 'beDoorCrosing2'
beDoorCrosing2
The robot rotates to head the direction "m_beHeadDirection_rad", then goes into behavior 'beDoorCrosing3'
beDoorCrosing3
The robot rotates tries to get to a given auxiliar target "m_beAuxTarget", then goes into normal behavior
beNormalNavigation
The robot tries to get to the given target point
beHeadDirection
The robot rotates to head the direction "m_beHeadDirection_rad", then goes into normal behavior
beDoorCrosing1
The robot tries to get to a given auxiliar target "m_beAuxTarget", then goes into behavior 'beDoorCrosing2'
beDoorCrosing2
The robot rotates to head the direction "m_beHeadDirection_rad", then goes into behavior 'beDoorCrosing3'
beDoorCrosing3
The robot rotates tries to get to a given auxiliar target "m_beAuxTarget", then goes into normal behavior
Definition at line 136 of file YclopsNavigationSystem.h.
enum mrpt::reactivenav::YclopsNavigationSystem::TNavigatorBehavior
See 'navigatorBehavior'
Enumerator:
beNormalNavigation
The robot tries to get to the given target point
beHeadDirection
The robot rotates to head the direction "m_beHeadDirection_rad", then goes into normal behavior
beDoorCrosing1
The robot tries to get to a given auxiliar target "m_beAuxTarget", then goes into behavior 'beDoorCrosing2'
beDoorCrosing2
The robot rotates to head the direction "m_beHeadDirection_rad", then goes into behavior 'beDoorCrosing3'
beDoorCrosing3
The robot rotates tries to get to a given auxiliar target "m_beAuxTarget", then goes into normal behavior
beNormalNavigation
The robot tries to get to the given target point
beHeadDirection
The robot rotates to head the direction "m_beHeadDirection_rad", then goes into normal behavior
beDoorCrosing1
The robot tries to get to a given auxiliar target "m_beAuxTarget", then goes into behavior 'beDoorCrosing2'
beDoorCrosing2
The robot rotates to head the direction "m_beHeadDirection_rad", then goes into behavior 'beDoorCrosing3'
beDoorCrosing3
The robot rotates tries to get to a given auxiliar target "m_beAuxTarget", then goes into normal behavior
beNormalNavigation
The robot tries to get to the given target point
beHeadDirection
The robot rotates to head the direction "m_beHeadDirection_rad", then goes into normal behavior
beDoorCrosing1
The robot tries to get to a given auxiliar target "m_beAuxTarget", then goes into behavior 'beDoorCrosing2'
beDoorCrosing2
The robot rotates to head the direction "m_beHeadDirection_rad", then goes into behavior 'beDoorCrosing3'
beDoorCrosing3
The robot rotates tries to get to a given auxiliar target "m_beAuxTarget", then goes into normal behavior
Definition at line 103 of file Yclopsnav.h.
Constructor & Destructor Documentation
YclopsNavigationSystem::YclopsNavigationSystem (CReactiveInterfaceImplementation & react_iterf_impl, bool enableConsoleOutput = true, bool enableLogFile = false)
Constructor
Parameters:
configINIFile The file to load the configuration from. See loadConfigFile
robotConfigFile The file to load the robot specific configuration from.
rmc A set of wrappers that must be filled in.
sensors A set of wrappers that must be filled in.
dbg A set of wrappers that must be filled in.
evnts A set of wrappers that must be filled in.
enableConsoleOutput Set to false if console output is not desired.
enableLogFile Set to true to enable logging to file.
Definition at line 27 of file YclopsNavigationSystem.cpp.
References beNormalNavigation, CerrandoHilo, enableConsoleOutput, enableLogFile(), holonomicMethod, last_cmd_v, last_cmd_w, logFile, meanExecutionPeriod, navigatorBehavior, nIteration, and PTGs.
YclopsNavigationSystem::~YclopsNavigationSystem () [virtual]
Destructor
Definition at line 1218 of file YclopsNavigationSystem.cpp.
References CerrandoHilo, holonomicMethod, logFile, m_critZoneNavigating, and PTGs.
mrpt::reactivenav::YclopsNavigationSystem::YclopsNavigationSystem (CReactiveInterfaceImplementation & react_iterf_impl, bool enableConsoleOutput = true, bool enableLogFile = false)
Constructor
Parameters:
configINIFile The file to load the configuration from. See loadConfigFile
robotConfigFile The file to load the robot specific configuration from.
rmc A set of wrappers that must be filled in.
sensors A set of wrappers that must be filled in.
dbg A set of wrappers that must be filled in.
evnts A set of wrappers that must be filled in.
enableConsoleOutput Set to false if console output is not desired.
enableLogFile Set to true to enable logging to file.
virtual mrpt::reactivenav::YclopsNavigationSystem::~YclopsNavigationSystem () [virtual]
Destructor
EIGEN_MAKE_ALIGNED_OPERATOR_NEW mrpt::reactivenav::YclopsNavigationSystem::YclopsNavigationSystem (CReactiveInterfaceImplementation & react_iterf_impl, bool enableConsoleOutput = true, bool enableLogFile = false)
Constructor
Parameters:
configINIFile The file to load the configuration from. See loadConfigFile
robotConfigFile The file to load the robot specific configuration from.
rmc A set of wrappers that must be filled in.
sensors A set of wrappers that must be filled in.
dbg A set of wrappers that must be filled in.
evnts A set of wrappers that must be filled in.
enableConsoleOutput Set to false if console output is not desired.
enableLogFile Set to true to enable logging to file.
virtual mrpt::reactivenav::YclopsNavigationSystem::~YclopsNavigationSystem () [virtual]
Destructor
Member Function Documentation
void YclopsNavigationSystem::changeRobotShape (math::CPolygon & shape)
Change the robot shape, which is taken into account for collision grid building.
Definition at line 64 of file YclopsNavigationSystem.cpp.
References collisionGridsMustBeUpdated, and robotShape.
Referenced by loadConfigFile().
void mrpt::reactivenav::YclopsNavigationSystem::changeRobotShape (math::CPolygon & shape)
Change the robot shape, which is taken into account for collision grid building.
void mrpt::reactivenav::YclopsNavigationSystem::changeRobotShape (math::CPolygon & shape)
Change the robot shape, which is taken into account for collision grid building.
void YclopsNavigationSystem::enableLogFile (bool enable)
Enables / disables the logging into a file.
Definition at line 266 of file YclopsNavigationSystem.cpp.
References logFile.
Referenced by YclopsNavigationSystem().
void mrpt::reactivenav::YclopsNavigationSystem::enableLogFile (bool enable)
Enables / disables the logging into a file.
void mrpt::reactivenav::YclopsNavigationSystem::enableLogFile (bool enable)
Enables / disables the logging into a file.
void YclopsNavigationSystem::Error_ParadaDeEmergencia (const char * msg) [private]
Definition at line 1313 of file YclopsNavigationSystem.cpp.
Referenced by performNavigationStep().
void mrpt::reactivenav::YclopsNavigationSystem::Error_ParadaDeEmergencia (const char * msg) [private]
void mrpt::reactivenav::YclopsNavigationSystem::Error_ParadaDeEmergencia (const char * msg) [private]
float mrpt::reactivenav::YclopsNavigationSystem::evaluate (TNavigationParams * params)
Evaluate navigation hardness:
float mrpt::reactivenav::YclopsNavigationSystem::evaluate (TNavigationParams * params)
Evaluate navigation hardness:
float YclopsNavigationSystem::evaluate (TNavigationParams * params)
Evaluate navigation hardness:
Definition at line 1256 of file YclopsNavigationSystem.cpp.
void YclopsNavigationSystem::getLastLogRecord (CLogFileRecord & o)
Provides a copy of the last log record with information about execution. On any unexpected error "*o" will be NULL.
Parameters:
o An object where the log will be stored into.
Definition at line 79 of file YclopsNavigationSystem.cpp.
References lastLogRecord, and m_critZoneLastLog.
void mrpt::reactivenav::YclopsNavigationSystem::getLastLogRecord (CLogFileRecord & o)
Provides a copy of the last log record with information about execution. On any unexpected error "*o" will be NULL.
Parameters:
o An object where the log will be stored into.
void mrpt::reactivenav::YclopsNavigationSystem::getLastLogRecord (CLogFileRecord & o)
Provides a copy of the last log record with information about execution. On any unexpected error "*o" will be NULL.
Parameters:
o An object where the log will be stored into.
void YclopsNavigationSystem::getTarget (mrpt::poses::TPoint2D * target)
Definition at line 1525 of file YclopsNavigationSystem.cpp.
void YclopsNavigationSystem::gotoNextPoint () [private]
starts navigating to next point in ordered list
Definition at line 1453 of file YclopsNavigationSystem.cpp.
References navigate(), points, and targetAllowedDistance.
Referenced by setup().
void mrpt::reactivenav::YclopsNavigationSystem::initialize ()
Must be called for loading collision grids, or the first navigation command may last a long time to be executed.
void mrpt::reactivenav::YclopsNavigationSystem::initialize ()
Must be called for loading collision grids, or the first navigation command may last a long time to be executed.
void YclopsNavigationSystem::initialize ()
Must be called for loading collision grids, or the first navigation command may last a long time to be executed.
Definition at line 54 of file YclopsNavigationSystem.cpp.
References STEP1_CollisionGridsBuilder().
void YclopsNavigationSystem::loadConfigFile (const mrpt::utils::CConfigFileBase & ini, const mrpt::utils::CConfigFileBase & robotIni)
Reload the configuration from a file
Definition at line 92 of file YclopsNavigationSystem.cpp.
References badNavAlarm_AlarmTimeout, changeRobotShape(), colGridRes_x, colGridRes_y, collisionGridsMustBeUpdated, DISABLE_PERIOD_AFTER_FAIL, DIST_TO_TARGET_FOR_SENDING_EVENT, DOOR_CROOSING_BEH3_TIMEOUT, DOOR_CROSSING_DIST_TO_AUX_TARGETS, DOOR_CROSSING_MAXIMUM_DOORWAY_SIZE, DOOR_CROSSING_SEARCH_TARGET_DISTANCEx2, DOORCROSSING_HEADING_ACCURACY_DEG, DOORCROSSING_ROTATION_CTE_DEG, holonomicMethod, maxObstaclesHeight, minObstaclesHeight, PTGs, refDistance, robotMax_V_mps, robotMax_W_degps, ROBOTMODEL_DELAY, ROBOTMODEL_TAU, robotName, robotShape, setHolonomicMethod(), VORONOI_MINIMUM_CLEARANCE, VORONOI_PATH_DIST_FROM_DOORWAY, and weights.
Referenced by NavigationChallenge::AutonomousMode(), main(), and ReactiveNavigationDemoFrame::tryConstructReactiveNavigator().
void mrpt::reactivenav::YclopsNavigationSystem::loadConfigFile (const mrpt::utils::CConfigFileBase & ini, const mrpt::utils::CConfigFileBase & robotIni)
Reload the configuration from a file
void mrpt::reactivenav::YclopsNavigationSystem::loadConfigFile (const mrpt::utils::CConfigFileBase & ini, const mrpt::utils::CConfigFileBase & robotIni)
Reload the configuration from a file
void mrpt::reactivenav::YclopsNavigationSystem::navigate (TNavigationParams * params)
Start navigation:
Referenced by NavigationChallenge::AutonomousMode(), gotoNextPoint(), and ReactiveNavigationDemoFrame::OnbtnNavigateClick().
void mrpt::reactivenav::YclopsNavigationSystem::navigate (TNavigationParams * params)
Start navigation:
void mrpt::reactivenav::YclopsNavigationSystem::navigate (TNavigationParams * params)
Start navigation:
void YclopsNavigationSystem::performNavigationStep () [private]
The main method for the navigator
Definition at line 323 of file YclopsNavigationSystem.cpp.
References badNavAlarm_AlarmTimeout, badNavAlarm_lastMinDistTime, badNavAlarm_minDistTarget, beDoorCrosing1, beDoorCrosing2, beDoorCrosing3, beNormalNavigation, CerrandoHilo, mrpt::reactivenav::YclopsNavigationSystem::THolonomicMovement::direction, DIST_TO_TARGET_FOR_SENDING_EVENT, Error_ParadaDeEmergencia(), mrpt::reactivenav::YclopsNavigationSystem::THolonomicMovement::evaluation, mrpt::reactivenav::YclopsNavigationSystem::CDynamicWindow::findBestApproximation(), last_cmd_v, last_cmd_w, lastLogRecord, logFile, m_bePassPoint1, m_bePassPoint2, m_critZoneLastLog, m_critZoneNavigating, maxObstaclesHeight, meanExecutionPeriod, minObstaclesHeight, navigationEndEventSent, navigatorBehavior, nIteration, PREVIOUS_VALUES_IN_LOG, mrpt::reactivenav::YclopsNavigationSystem::THolonomicMovement::PTG, PTGs, refDistance, robotShape, STEP1_CollisionGridsBuilder(), STEP2_Sense(), STEP3_SpaceTransformer(), STEP4_HolonomicMethod(), STEP5_Evaluator(), STEP6_Selector(), STEP7_NonHolonomicMovement(), and timerForExecutionPeriod.
void mrpt::reactivenav::YclopsNavigationSystem::performNavigationStep () [private]
The main method for the navigator
void mrpt::reactivenav::YclopsNavigationSystem::performNavigationStep () [private]
The main method for the navigator
void YclopsNavigationSystem::setChallenge (bool c)
Definition at line 1520 of file YclopsNavigationSystem.cpp.
References NavChallenge.
Referenced by ReactiveNavigationDemoFrame::OnLoadPointsFileClick(), and signal_handler().
void YclopsNavigationSystem::setFileName (std::string & fileName, bool inMeters)
sets filename for waypoints to be loaded from and if the points are stored internally in meters (for the simulator) or in gps coordinates)
Definition at line 23 of file SimpleNavigation.cpp.
References SimpleNavigation::fileName, and SimpleNavigation::inMeters.
Referenced by ReactiveNavigationDemoFrame::OnLoadPointsFileClick(), and signal_handler().
void mrpt::reactivenav::YclopsNavigationSystem::setHolonomicMethod (THolonomicMethod method, const char * config_INIfile = "./CONFIG_ReactiveNavigator.ini")
Selects which one from the set of available holonomic methods will be used into transformed TP-Space, and sets its configuration from a configuration file.
void mrpt::reactivenav::YclopsNavigationSystem::setHolonomicMethod (THolonomicMethod method, const char * config_INIfile = "./CONFIG_ReactiveNavigator.ini")
Selects which one from the set of available holonomic methods will be used into transformed TP-Space, and sets its configuration from a configuration file.
Referenced by loadConfigFile().
void mrpt::reactivenav::YclopsNavigationSystem::setHolonomicMethod (THolonomicMethod method, const char * config_INIfile = "./CONFIG_ReactiveNavigator.ini")
Selects which one from the set of available holonomic methods will be used into transformed TP-Space, and sets its configuration from a configuration file.
void mrpt::reactivenav::YclopsNavigationSystem::setParams (TNavigationParams * params)
Change current navigation params:
void mrpt::reactivenav::YclopsNavigationSystem::setParams (TNavigationParams * params)
Change current navigation params:
void mrpt::reactivenav::YclopsNavigationSystem::setParams (TNavigationParams * params)
Change current navigation params:
void YclopsNavigationSystem::setup ()
loads waypoints from file and plans navigation order, and starts navigating, so that it will navigate from the first point to the second until the last.
Definition at line 1479 of file YclopsNavigationSystem.cpp.
References fileName, gotoNextPoint(), inMeters, AbstractNavigationInterface::loadPoints(), NavChallenge, points, and AbstractNavigationInterface::solve().
Referenced by ReactiveNavigationDemoFrame::OnLoadPointsFileClick(), and signal_handler().
void mrpt::reactivenav::YclopsNavigationSystem::STEP1_CollisionGridsBuilder () [private]
void YclopsNavigationSystem::STEP1_CollisionGridsBuilder () [private]
Definition at line 799 of file YclopsNavigationSystem.cpp.
References collisionGridsMustBeUpdated, PTGs, robotName, and robotShape.
Referenced by initialize(), and performNavigationStep().
void mrpt::reactivenav::YclopsNavigationSystem::STEP1_CollisionGridsBuilder () [private]
bool YclopsNavigationSystem::STEP2_Sense (mrpt::slam::CSimplePointsMap & out_obstacles) [private]
Definition at line 828 of file YclopsNavigationSystem.cpp.
Referenced by performNavigationStep().
bool mrpt::reactivenav::YclopsNavigationSystem::STEP2_Sense (mrpt::slam::CSimplePointsMap & out_obstacles) [private]
bool mrpt::reactivenav::YclopsNavigationSystem::STEP2_Sense (mrpt::slam::CSimplePointsMap & out_obstacles) [private]
void mrpt::reactivenav::YclopsNavigationSystem::STEP3_SpaceTransformer (poses::CPointsMap & in_obstacles, CParameterizedTrajectoryGenerator * in_PTG, vector_double & out_TPObstacles) [private]
void mrpt::reactivenav::YclopsNavigationSystem::STEP3_SpaceTransformer (poses::CPointsMap & in_obstacles, CParameterizedTrajectoryGenerator * in_PTG, vector_double & out_TPObstacles) [private]
Referenced by performNavigationStep().
void mrpt::reactivenav::YclopsNavigationSystem::STEP3_SpaceTransformer (poses::CPointsMap & in_obstacles, CParameterizedTrajectoryGenerator * in_PTG, vector_double & out_TPObstacles) [private]
void mrpt::reactivenav::YclopsNavigationSystem::STEP4_HolonomicMethod (vector_double & in_Obstacles, poses::CPoint2D & in_Target, float in_maxRobotSpeed, THolonomicMovement & out_selectedMovement, CHolonomicLogFileRecordPtr & in_HLFR) [private]
void mrpt::reactivenav::YclopsNavigationSystem::STEP4_HolonomicMethod (vector_double & in_Obstacles, poses::CPoint2D & in_Target, float in_maxRobotSpeed, THolonomicMovement & out_selectedMovement, CHolonomicLogFileRecordPtr & in_HLFR) [private]
void mrpt::reactivenav::YclopsNavigationSystem::STEP4_HolonomicMethod (vector_double & in_Obstacles, poses::CPoint2D & in_Target, float in_maxRobotSpeed, THolonomicMovement & out_selectedMovement, CHolonomicLogFileRecordPtr & in_HLFR) [private]
Referenced by performNavigationStep().
void mrpt::reactivenav::YclopsNavigationSystem::STEP5_Evaluator (THolonomicMovement & in_holonomicMovement, vector_double & in_TPObstacles, poses::CPoint2D & WS_Target, poses::CPoint2D & TP_Target, bool wasSelectedInLast, CLogFileRecord::TInfoPerPTG & log) [private]
void mrpt::reactivenav::YclopsNavigationSystem::STEP5_Evaluator (THolonomicMovement & in_holonomicMovement, vector_double & in_TPObstacles, poses::CPoint2D & WS_Target, poses::CPoint2D & TP_Target, bool wasSelectedInLast, CLogFileRecord::TInfoPerPTG & log) [private]
void mrpt::reactivenav::YclopsNavigationSystem::STEP5_Evaluator (THolonomicMovement & in_holonomicMovement, vector_double & in_TPObstacles, poses::CPoint2D & WS_Target, poses::CPoint2D & TP_Target, bool wasSelectedInLast, CLogFileRecord::TInfoPerPTG & log) [private]
Referenced by performNavigationStep().
void YclopsNavigationSystem::STEP6_Selector (std::vector< THolonomicMovement > & in_holonomicMovements, THolonomicMovement & out_selectedHolonomicMovement, int & out_nSelectedPTG) [private]
Definition at line 1127 of file YclopsNavigationSystem.cpp.
References mrpt::reactivenav::YclopsNavigationSystem::THolonomicMovement::direction, mrpt::reactivenav::YclopsNavigationSystem::THolonomicMovement::evaluation, mrpt::reactivenav::YclopsNavigationSystem::THolonomicMovement::PTG, and mrpt::reactivenav::YclopsNavigationSystem::THolonomicMovement::speed.
Referenced by performNavigationStep().
void mrpt::reactivenav::YclopsNavigationSystem::STEP6_Selector (std::vector< THolonomicMovement > & in_holonomicMovements, THolonomicMovement & out_selectedHolonomicMovement, int & out_nSelectedPTG) [private]
void mrpt::reactivenav::YclopsNavigationSystem::STEP6_Selector (std::vector< THolonomicMovement > & in_holonomicMovements, THolonomicMovement & out_selectedHolonomicMovement, int & out_nSelectedPTG) [private]
void YclopsNavigationSystem::STEP7_NonHolonomicMovement (THolonomicMovement & in_movement, float & out_v, float & out_w) [private]
Definition at line 1158 of file YclopsNavigationSystem.cpp.
References mrpt::reactivenav::YclopsNavigationSystem::THolonomicMovement::direction, mrpt::reactivenav::YclopsNavigationSystem::THolonomicMovement::PTG, robotMax_V_mps, robotMax_W_degps, and mrpt::reactivenav::YclopsNavigationSystem::THolonomicMovement::speed.
Referenced by performNavigationStep().
void mrpt::reactivenav::YclopsNavigationSystem::STEP7_NonHolonomicMovement (THolonomicMovement & in_movement, float & out_v, float & out_w) [private]
void mrpt::reactivenav::YclopsNavigationSystem::STEP7_NonHolonomicMovement (THolonomicMovement & in_movement, float & out_v, float & out_w) [private]
void YclopsNavigationSystem::stop ()
stops the current navigation process.
Definition at line 1473 of file YclopsNavigationSystem.cpp.
References points.
Referenced by signal_handler().
Member Data Documentation
float mrpt::reactivenav::YclopsNavigationSystem::badNavAlarm_AlarmTimeout [private]
Definition at line 228 of file Yclopsnav.h.
Referenced by loadConfigFile(), and performNavigationStep().
mrpt::system::TTimeStamp mrpt::reactivenav::YclopsNavigationSystem::badNavAlarm_lastMinDistTime [private]
Definition at line 227 of file Yclopsnav.h.
Referenced by performNavigationStep().
float mrpt::reactivenav::YclopsNavigationSystem::badNavAlarm_minDistTarget [private]
For sending an alarm (error event) when it seems that we are not approaching toward the target in a while...
Definition at line 226 of file Yclopsnav.h.
Referenced by performNavigationStep().
bool mrpt::reactivenav::YclopsNavigationSystem::CerrandoHilo [private]
Definition at line 279 of file Yclopsnav.h.
Referenced by performNavigationStep(), YclopsNavigationSystem(), and ~YclopsNavigationSystem().
float mrpt::reactivenav::YclopsNavigationSystem::colGridRes_x [private]
Definition at line 197 of file Yclopsnav.h.
Referenced by loadConfigFile().
float mrpt::reactivenav::YclopsNavigationSystem::colGridRes_y [private]
Definition at line 197 of file Yclopsnav.h.
Referenced by loadConfigFile().
bool mrpt::reactivenav::YclopsNavigationSystem::collisionGridsMustBeUpdated [private]
Definition at line 234 of file Yclopsnav.h.
Referenced by changeRobotShape(), loadConfigFile(), and STEP1_CollisionGridsBuilder().
float mrpt::reactivenav::YclopsNavigationSystem::DISABLE_PERIOD_AFTER_FAIL [private]
Definition at line 207 of file Yclopsnav.h.
Referenced by loadConfigFile().
float mrpt::reactivenav::YclopsNavigationSystem::DIST_TO_TARGET_FOR_SENDING_EVENT [private]
Definition at line 203 of file Yclopsnav.h.
Referenced by loadConfigFile(), and performNavigationStep().
float mrpt::reactivenav::YclopsNavigationSystem::DOOR_CROOSING_BEH3_TIMEOUT [private]
Definition at line 212 of file Yclopsnav.h.
Referenced by loadConfigFile().
float mrpt::reactivenav::YclopsNavigationSystem::DOOR_CROSSING_DIST_TO_AUX_TARGETS [private]
Definition at line 211 of file Yclopsnav.h.
Referenced by loadConfigFile().
float mrpt::reactivenav::YclopsNavigationSystem::DOOR_CROSSING_MAXIMUM_DOORWAY_SIZE [private]
Definition at line 213 of file Yclopsnav.h.
Referenced by loadConfigFile().
float mrpt::reactivenav::YclopsNavigationSystem::DOOR_CROSSING_SEARCH_TARGET_DISTANCEx2 [private]
Definition at line 205 of file Yclopsnav.h.
Referenced by loadConfigFile().
float mrpt::reactivenav::YclopsNavigationSystem::DOORCROSSING_HEADING_ACCURACY_DEG [private]
Definition at line 209 of file Yclopsnav.h.
Referenced by loadConfigFile().
float mrpt::reactivenav::YclopsNavigationSystem::DOORCROSSING_ROTATION_CTE_DEG [private]
Definition at line 210 of file Yclopsnav.h.
Referenced by loadConfigFile().
bool mrpt::reactivenav::YclopsNavigationSystem::enableConsoleOutput [private]
Enables / disables the console debug output.
Definition at line 190 of file Yclopsnav.h.
Referenced by YclopsNavigationSystem().
std::string mrpt::reactivenav::YclopsNavigationSystem::fileName [private]
Definition at line 184 of file YclopsNavigationSystem.h.
Referenced by setup().
CAbstractHolonomicReactiveMethod * mrpt::reactivenav::YclopsNavigationSystem::holonomicMethod [private]
The current log file stream, or NULL if not being used
Definition at line 184 of file Yclopsnav.h.
Referenced by loadConfigFile(), YclopsNavigationSystem(), and ~YclopsNavigationSystem().
bool mrpt::reactivenav::YclopsNavigationSystem::inMeters [private]
Definition at line 185 of file YclopsNavigationSystem.h.
Referenced by setup().
float mrpt::reactivenav::YclopsNavigationSystem::last_cmd_v [private]
For the histeresis:
Definition at line 161 of file Yclopsnav.h.
Referenced by performNavigationStep(), and YclopsNavigationSystem().
float mrpt::reactivenav::YclopsNavigationSystem::last_cmd_w [private]
Definition at line 161 of file Yclopsnav.h.
Referenced by performNavigationStep(), and YclopsNavigationSystem().
CLogFileRecord mrpt::reactivenav::YclopsNavigationSystem::lastLogRecord [private]
The last log.
Definition at line 157 of file Yclopsnav.h.
Referenced by getLastLogRecord(), and performNavigationStep().
utils::CStream * mrpt::reactivenav::YclopsNavigationSystem::logFile [private]
The current log file stream, or NULL if not being used
Definition at line 187 of file Yclopsnav.h.
Referenced by enableLogFile(), performNavigationStep(), YclopsNavigationSystem(), and ~YclopsNavigationSystem().
CPoint2D mrpt::reactivenav::YclopsNavigationSystem::m_beAuxTarget [private]
Auxiliary target position, for behaviors 'beDoorCrosing1' and 'beDoorCrosing3'.
Definition at line 141 of file Yclopsnav.h.
float mrpt::reactivenav::YclopsNavigationSystem::m_beHeadDirection_rad [private]
The desired heading direction (in rads), for behaviors 'beHeadDirection' and 'beDoorCrosing2'.
Definition at line 137 of file Yclopsnav.h.
CPoint2D mrpt::reactivenav::YclopsNavigationSystem::m_bePassPoint1 [private]
This is the desired "path" for passing a door (in GLOBAL coordinates!)
Definition at line 145 of file Yclopsnav.h.
Referenced by performNavigationStep().
CPoint2D mrpt::reactivenav::YclopsNavigationSystem::m_bePassPoint2 [private]
Definition at line 145 of file Yclopsnav.h.
Referenced by performNavigationStep().
synch::CCriticalSection mrpt::reactivenav::YclopsNavigationSystem::m_critZoneLastLog [private]
Critical zones:
Definition at line 169 of file Yclopsnav.h.
Referenced by getLastLogRecord(), and performNavigationStep().
synch::CCriticalSection mrpt::reactivenav::YclopsNavigationSystem::m_critZoneNavigating [private]
Definition at line 169 of file Yclopsnav.h.
Referenced by performNavigationStep(), and ~YclopsNavigationSystem().
float mrpt::reactivenav::YclopsNavigationSystem::maxObstaclesHeight [private]
Definition at line 202 of file Yclopsnav.h.
Referenced by loadConfigFile(), and performNavigationStep().
float mrpt::reactivenav::YclopsNavigationSystem::meanExecutionPeriod [private]
Runtime estimation of execution period of the method.
Definition at line 221 of file Yclopsnav.h.
Referenced by performNavigationStep(), and YclopsNavigationSystem().
float mrpt::reactivenav::YclopsNavigationSystem::minObstaclesHeight [private]
Definition at line 202 of file Yclopsnav.h.
Referenced by loadConfigFile(), and performNavigationStep().
bool mrpt::reactivenav::YclopsNavigationSystem::NavChallenge [private]
Definition at line 164 of file YclopsNavigationSystem.h.
Referenced by setChallenge(), and setup().
bool mrpt::reactivenav::YclopsNavigationSystem::navigationEndEventSent [private]
Will be false until the navigation end is sent, and it is reset with each new command
Definition at line 165 of file Yclopsnav.h.
Referenced by performNavigationStep().
TNavigatorBehavior mrpt::reactivenav::YclopsNavigationSystem::navigatorBehavior [private]
This defines the 'behavior' of the navigator (see posible values in TNavigatorBehavior)
Definition at line 133 of file Yclopsnav.h.
Referenced by performNavigationStep(), and YclopsNavigationSystem().
unsigned long mrpt::reactivenav::YclopsNavigationSystem::nIteration [private]
The iterations count.
Definition at line 217 of file Yclopsnav.h.
Referenced by performNavigationStep(), and YclopsNavigationSystem().
mrpt::aligned_containers<mrpt::poses::CPoint2D>::vector_t mrpt::reactivenav::YclopsNavigationSystem::points [private]
Definition at line 167 of file YclopsNavigationSystem.h.
Referenced by gotoNextPoint(), setup(), and stop().
std::vector< CParameterizedTrajectoryGenerator * > mrpt::reactivenav::YclopsNavigationSystem::PTGs [private]
The set of transformations to be used:
Definition at line 238 of file Yclopsnav.h.
Referenced by loadConfigFile(), performNavigationStep(), STEP1_CollisionGridsBuilder(), YclopsNavigationSystem(), and ~YclopsNavigationSystem().
float mrpt::reactivenav::YclopsNavigationSystem::refDistance [private]
Definition at line 196 of file Yclopsnav.h.
Referenced by loadConfigFile(), and performNavigationStep().
float mrpt::reactivenav::YclopsNavigationSystem::robotMax_V_mps [private]
Definition at line 198 of file Yclopsnav.h.
Referenced by loadConfigFile(), and STEP7_NonHolonomicMovement().
float mrpt::reactivenav::YclopsNavigationSystem::robotMax_W_degps [private]
Definition at line 199 of file Yclopsnav.h.
Referenced by loadConfigFile(), and STEP7_NonHolonomicMovement().
float mrpt::reactivenav::YclopsNavigationSystem::ROBOTMODEL_DELAY [private]
Definition at line 200 of file Yclopsnav.h.
Referenced by loadConfigFile().
float mrpt::reactivenav::YclopsNavigationSystem::ROBOTMODEL_TAU [private]
Definition at line 200 of file Yclopsnav.h.
Referenced by loadConfigFile().
std::string mrpt::reactivenav::YclopsNavigationSystem::robotName [private]
Definition at line 195 of file Yclopsnav.h.
Referenced by loadConfigFile(), and STEP1_CollisionGridsBuilder().
math::CPolygon mrpt::reactivenav::YclopsNavigationSystem::robotShape [private]
The robot 2D shape model
Definition at line 233 of file Yclopsnav.h.
Referenced by changeRobotShape(), loadConfigFile(), performNavigationStep(), and STEP1_CollisionGridsBuilder().
float mrpt::reactivenav::YclopsNavigationSystem::targetAllowedDistance [private]
Definition at line 165 of file YclopsNavigationSystem.h.
Referenced by gotoNextPoint().
CTicTac mrpt::reactivenav::YclopsNavigationSystem::timerForExecutionPeriod [private]
Definition at line 192 of file Yclopsnav.h.
Referenced by performNavigationStep().
float mrpt::reactivenav::YclopsNavigationSystem::VORONOI_MINIMUM_CLEARANCE [private]
Definition at line 206 of file Yclopsnav.h.
Referenced by loadConfigFile().
float mrpt::reactivenav::YclopsNavigationSystem::VORONOI_PATH_DIST_FROM_DOORWAY [private]
Definition at line 208 of file Yclopsnav.h.
Referenced by loadConfigFile().
vector_float mrpt::reactivenav::YclopsNavigationSystem::weights [private]
Definition at line 201 of file Yclopsnav.h.
Referenced by loadConfigFile().
The documentation for this class was generated from the following files:
AI/ReactiveNavInterface/YclopsReactiveNavigationSimulator/Yclopsnav.h
AI/Sim/Yclopsnav.h
/home/tallred3/ecen493/SeniorProject/trunk/Code/YClopsLib/inc/YclopsNavigationSystem.h
AI/ReactiveNavInterface/YclopsReactiveNavigationSimulator/YclopsNavigationSystem.cpp
AI/Sim/YclopsNavigationSystem.cpp
/home/tallred3/ecen493/SeniorProject/trunk/Code/YClopsLib/src/SimpleNavigation.cpp
/home/tallred3/ecen493/SeniorProject/trunk/Code/YClopsLib/src/YclopsNavigationSystem.cpp