YClops: AbstractNavigationInterface Class Reference
AbstractNavigationInterface Class Reference
AbstractNavigationInterface.h - This file defines the classes relating to path planning.
#include <WaypointPlanner.h>
Public Member Functions
AbstractNavigationInterface (double lat, double lon)
Index for the Longitude in a CPoint2D.
virtual ~AbstractNavigationInterface ()
virtual
mrpt::aligned_containers
< mrpt::poses::CPoint2D >
::vector_t solve (bool inMeters)=0
void convertPointToMeters (mrpt::poses::CPoint2D &point)
void loadPoints (std::string filename, bool convertToMeters=false)
Static Public Member Functions
static double haversineDistance (double lat1, double lon1, double lat2, double lon2)
static double calcBearing (double lat1, double lon1, double lat2, double lon2, bool isDegrees=false)
Static Public Attributes
static const int LAT = 0
static const int LON = 1
Index for the Latitude in a CPoint2D.
Protected Attributes
mrpt::aligned_containers
< mrpt::poses::CPoint2D >
::vector_t toVisit
mrpt::aligned_containers
< mrpt::poses::CPoint2D >
::vector_t visited
Vector of points that haven't been visited by the planning.
Detailed Description
AbstractNavigationInterface.h - This file defines the classes relating to path planning.
Date:
Dec 27, 2010
Author:
Thomas Eldon Allred This class is an abstract interface for path planning for the robot
Definition at line 17 of file WaypointPlanner.h.
Constructor & Destructor Documentation
AbstractNavigationInterface::AbstractNavigationInterface (double lat, double lon)
Index for the Longitude in a CPoint2D.
Abstract Navigation class constructor
Parameters:
lat - representing the initial latitude
lon - representing the initial longitude
Definition at line 15 of file WaypointPlanner.cpp.
AbstractNavigationInterface::~AbstractNavigationInterface () [virtual]
Class destructor
Definition at line 19 of file WaypointPlanner.cpp.
Member Function Documentation
double AbstractNavigationInterface::calcBearing (double lat1, double lon1, double lat2, double lon2, bool isDegrees = false) [static]
Bearing Calculator - is a function that computes the bearing (angle) between two points measured in degrees
Returns:
the bearing between two points in degrees
Definition at line 85 of file WaypointPlanner.cpp.
Referenced by NoFilterPoseEstimator::update().
void AbstractNavigationInterface::convertPointToMeters (mrpt::poses::CPoint2D & point)
convertToMeters - changes a point from latitude and longitude to meters in x (positive direction is north) and y (positive direction is east) from the starting position
Definition at line 21 of file WaypointPlanner.cpp.
double AbstractNavigationInterface::haversineDistance (double lat1, double lon1, double lat2, double lon2) [static]
"Haver Sine" Distance - is a function that computes the great circle distance of two points measured in degrees
Returns:
The distance between two points in meters
Definition at line 65 of file WaypointPlanner.cpp.
Referenced by GPS::GetDistanceToWaypoint(), TSPNavigation::nieveTSPSolution(), and NoFilterPoseEstimator::update().
void AbstractNavigationInterface::loadPoints (std::string filename, bool convertToMeters = false)
loadRawGPSPointFile - reads in a stream of ascii whitespace delimited gps points from a file where the first one is the starting location and all subsequent are weighpoints to travel to.
Parameters:
filename - the name of the raw gps point file
Definition at line 30 of file WaypointPlanner.cpp.
Referenced by NavigationChallenge::AutonomousMode(), SimpleNavigation::go(), main(), and mrpt::reactivenav::YclopsNavigationSystem::setup().
virtual mrpt::aligned_containers<mrpt::poses::CPoint2D>::vector_t AbstractNavigationInterface::solve (bool inMeters) [pure virtual]
solve - solves the navigation problem
Returns:
- a list of gps weighpoints that need to be visited index 0 is the first then 1 then 2 ect.
Implemented in SequentialNavigation, and TSPNavigation.
Referenced by main(), and mrpt::reactivenav::YclopsNavigationSystem::setup().
Member Data Documentation
const int AbstractNavigationInterface::LAT = 0 [static]
Definition at line 20 of file WaypointPlanner.h.
Referenced by main(), and TSPNavigation::nieveTSPSolution().
const int AbstractNavigationInterface::LON = 1 [static]
Index for the Latitude in a CPoint2D.
Definition at line 21 of file WaypointPlanner.h.
Referenced by main(), and TSPNavigation::nieveTSPSolution().
mrpt::aligned_containers<mrpt::poses::CPoint2D>::vector_t AbstractNavigationInterface::toVisit [protected]
Definition at line 68 of file WaypointPlanner.h.
Referenced by TSPNavigation::solve(), and SequentialNavigation::solve().
mrpt::aligned_containers<mrpt::poses::CPoint2D>::vector_t AbstractNavigationInterface::visited [protected]
Vector of points that haven't been visited by the planning.
Definition at line 69 of file WaypointPlanner.h.
Referenced by TSPNavigation::solve(), and SequentialNavigation::solve().
The documentation for this class was generated from the following files:
/home/tallred3/ecen493/SeniorProject/trunk/Code/YClopsLib/inc/WaypointPlanner.h
/home/tallred3/ecen493/SeniorProject/trunk/Code/YClopsLib/src/WaypointPlanner.cpp