YClops: NavigationChallenge Class Reference
NavigationChallenge Class Reference
#include <NavigationChallenge.h>
Public Member Functions
void AutonomousMode (std::string &waypointsFile, bool challange)
Detailed Description
Definition at line 12 of file NavigationChallenge.h.
Member Function Documentation
void NavigationChallenge::AutonomousMode (std::string & waypointsFile, bool challange)
Definition at line 21 of file NavigationChallenge.cpp.
References YClopsReactiveNavInterface::changeSpeeds(), YClopsReactiveNavInterface::getCurrentPoseAndSpeeds(), mrpt::reactivenav::YclopsNavigationSystem::loadConfigFile(), AbstractNavigationInterface::loadPoints(), mrpt::reactivenav::YclopsNavigationSystem::navigate(), and TSPNavigation::solve().
The documentation for this class was generated from the following files:
AutonomousMode/NavigationChallenge.h
AutonomousMode/NavigationChallenge.cpp