YClops: tkhl::TSPAnt Class Reference
tkhl::TSPAnt Class Reference
#include <ACO.h>
Public Member Functions
void addcity (int city)
void Clear ()
void UpdateResult ()
void move ()
TSPAnt ()
void move2last ()
Public Attributes
int tabu [iCityCount]
double m_dLength
double m_dShortest
Private Member Functions
int ChooseNextCity ()
Private Attributes
double prob [iCityCount]
int m_iCityCount
int AllowedCity [iCityCount]
Detailed Description
Definition at line 53 of file ACO.h.
Constructor & Destructor Documentation
tkhl::TSPAnt::TSPAnt ()
Definition at line 97 of file ACO.h.
References AllowedCity, tkhl::iCityCount, m_dLength, m_dShortest, m_iCityCount, and prob.
Member Function Documentation
void tkhl::TSPAnt::addcity (int city)
Definition at line 108 of file ACO.h.
References AllowedCity, m_iCityCount, and tabu.
Referenced by Clear(), tkhl::TSPDriver::GetAnt(), move(), and move2last().
int tkhl::TSPAnt::ChooseNextCity () [private]
Definition at line 115 of file ACO.h.
References AllowedCity, tkhl::alpha, tkhl::beta, tkhl::TSPGInfo::distance, tkhl::iCityCount, tkhl::TSPGInfo::m_dTrial, m_iCityCount, tkhl::Map, prob, tabu, and tkhl::TSPrnd().
Referenced by move().
void tkhl::TSPAnt::Clear ()
Definition at line 83 of file ACO.h.
References addcity(), AllowedCity, tkhl::iCityCount, m_dLength, m_iCityCount, prob, and tabu.
void tkhl::TSPAnt::move ()
Definition at line 178 of file ACO.h.
References addcity(), and ChooseNextCity().
void tkhl::TSPAnt::move2last ()
Definition at line 72 of file ACO.h.
References addcity(), AllowedCity, and tkhl::iCityCount.
Referenced by tkhl::TSPDriver::StartSearch().
void tkhl::TSPAnt::UpdateResult ()
Definition at line 170 of file ACO.h.
References tkhl::TSPGInfo::distance, tkhl::iCityCount, m_dLength, tkhl::Map, and tabu.
Referenced by tkhl::TSPDriver::StartSearch().
Member Data Documentation
int tkhl::TSPAnt::AllowedCity[iCityCount] [private]
Definition at line 59 of file ACO.h.
Referenced by addcity(), ChooseNextCity(), Clear(), move2last(), and TSPAnt().
double tkhl::TSPAnt::m_dLength
Definition at line 65 of file ACO.h.
Referenced by Clear(), tkhl::TSPDriver::StartSearch(), TSPAnt(), UpdateResult(), and tkhl::TSPDriver::UpdateTrial().
double tkhl::TSPAnt::m_dShortest
Definition at line 66 of file ACO.h.
Referenced by TSPAnt().
int tkhl::TSPAnt::m_iCityCount [private]
Definition at line 58 of file ACO.h.
Referenced by addcity(), ChooseNextCity(), Clear(), and TSPAnt().
double tkhl::TSPAnt::prob[iCityCount] [private]
Definition at line 57 of file ACO.h.
Referenced by ChooseNextCity(), Clear(), and TSPAnt().
int tkhl::TSPAnt::tabu[iCityCount]
Definition at line 62 of file ACO.h.
Referenced by addcity(), ChooseNextCity(), Clear(), UpdateResult(), and tkhl::TSPDriver::UpdateTrial().
The documentation for this class was generated from the following file:
Sensors/MultiSensorLib/inc/ACO.h