YClops: WheelEncoder Class Reference
WheelEncoder Class Reference
#include <WheelEncoder.h>
Public Member Functions
WheelEncoder ()
void loadConfiguration (const mrpt::utils::CConfigFileBase &config, const std::string &sectionName)
void init ()
void sensorProcess ()
SensorData * getData ()
void dumpData (std::ostream &out) const
virtual ~WheelEncoder ()
Protected Attributes
int leftCount
int rightCount
int leftCountAbsolute
int rightCountAbsolute
int leftEncoderSpeed
int rightEncoderSpeed
int encoderPPR
Detailed Description
Definition at line 13 of file WheelEncoder.h.
Constructor & Destructor Documentation
WheelEncoder::WheelEncoder ()
Definition at line 15 of file WheelEncoder.cpp.
WheelEncoder::~WheelEncoder () [virtual]
Definition at line 70 of file WheelEncoder.cpp.
Member Function Documentation
void WheelEncoder::dumpData (std::ostream & out) const
dumps data out to the parameter out
Parameters:
out - the stream to which to write the data
Reimplemented from YClopsSensor.
Definition at line 59 of file WheelEncoder.cpp.
References leftCount, leftCountAbsolute, leftEncoderSpeed, rightCount, rightCountAbsolute, and rightEncoderSpeed.
Referenced by YClopsReactiveNavInterface::getCurrentPoseAndSpeeds().
SensorData * WheelEncoder::getData () [virtual]
SensorData needs to be allocated on the heap to avoid splicing when we cast it to be a various sensor type
Implements YClopsSensor.
Definition at line 52 of file WheelEncoder.cpp.
References leftCount, leftCountAbsolute, leftEncoderSpeed, rightCount, rightCountAbsolute, and rightEncoderSpeed.
Referenced by YClopsReactiveNavInterface::getCurrentPoseAndSpeeds().
void WheelEncoder::init () [virtual]
initialize the sensor
Implements YClopsSensor.
Definition at line 26 of file WheelEncoder.cpp.
References MotorController::BothChannels, DEBUG4, encoderPPR, MotorController::instance(), leftCountAbsolute, LOG_ENCODER, MotorController::setEncoderCounter(), MotorController::setEncoderPPR(), and MotorController::setEncoderUsage().
Referenced by YClopsReactiveNavInterface::YClopsReactiveNavInterface().
void WheelEncoder::loadConfiguration (const mrpt::utils::CConfigFileBase & config, const std::string & sectionName) [virtual]
load sensor specific values from the configuration file
Implements YClopsSensor.
Definition at line 17 of file WheelEncoder.cpp.
References encoderPPR, leftCountAbsolute, and rightCountAbsolute.
Referenced by YClopsReactiveNavInterface::YClopsReactiveNavInterface().
void WheelEncoder::sensorProcess () [virtual]
collect data from the sensor and cache it
Implements YClopsSensor.
Definition at line 38 of file WheelEncoder.cpp.
References DEBUG4, MotorController::getAbsoluteEncoderCount(), MotorController::getEncoderSpeeds(), MotorController::getRelativeEncoderCount(), MotorController::instance(), leftCount, leftCountAbsolute, leftEncoderSpeed, LOG_ENCODER, rightCount, rightCountAbsolute, and rightEncoderSpeed.
Referenced by YClopsReactiveNavInterface::getCurrentPoseAndSpeeds().
Member Data Documentation
int WheelEncoder::encoderPPR [protected]
Definition at line 51 of file WheelEncoder.h.
Referenced by init(), and loadConfiguration().
int WheelEncoder::leftCount [protected]
Definition at line 45 of file WheelEncoder.h.
Referenced by dumpData(), getData(), and sensorProcess().
int WheelEncoder::leftCountAbsolute [protected]
Definition at line 47 of file WheelEncoder.h.
Referenced by dumpData(), getData(), init(), loadConfiguration(), and sensorProcess().
int WheelEncoder::leftEncoderSpeed [protected]
Definition at line 49 of file WheelEncoder.h.
Referenced by dumpData(), getData(), and sensorProcess().
int WheelEncoder::rightCount [protected]
Definition at line 46 of file WheelEncoder.h.
Referenced by dumpData(), getData(), and sensorProcess().
int WheelEncoder::rightCountAbsolute [protected]
Definition at line 48 of file WheelEncoder.h.
Referenced by dumpData(), getData(), loadConfiguration(), and sensorProcess().
int WheelEncoder::rightEncoderSpeed [protected]
Definition at line 50 of file WheelEncoder.h.
Referenced by dumpData(), getData(), and sensorProcess().
The documentation for this class was generated from the following files:
/home/tallred3/ecen493/SeniorProject/trunk/Code/YClopsLib/inc/WheelEncoder.h
/home/tallred3/ecen493/SeniorProject/trunk/Code/YClopsLib/src/WheelEncoder.cpp