YClops: CMyReactInterface Class Reference
CMyReactInterface Class Reference
Public Member Functions
bool getCurrentPoseAndSpeeds (mrpt::poses::CPose2D &curPose, float &curV, float &curW)
bool changeSpeeds (float v, float w)
bool senseObstacles (mrpt::slam::CSimplePointsMap &obstacles)
void notifyHeadingDirection (const double heading_dir_angle)
bool getCurrentPoseAndSpeeds (mrpt::poses::CPose2D &curPose, float &curV, float &curW)
bool changeSpeeds (float v, float w)
bool senseObstacles (mrpt::slam::CSimplePointsMap &obstacles)
void notifyHeadingDirection (const double heading_dir_angle)
Detailed Description
Definition at line 130 of file ReactiveNavigationDemoMain.cpp.
Member Function Documentation
bool CMyReactInterface::changeSpeeds (float v, float w) [inline]
Definition at line 141 of file ReactiveNavigationDemoMain.cpp.
References robotSim().
bool CMyReactInterface::changeSpeeds (float v, float w) [inline]
Definition at line 153 of file ReactiveNavigationDemoMain.cpp.
References robotSim().
bool CMyReactInterface::getCurrentPoseAndSpeeds (mrpt::poses::CPose2D & curPose, float & curV, float & curW) [inline]
Definition at line 133 of file ReactiveNavigationDemoMain.cpp.
References robotSim().
bool CMyReactInterface::getCurrentPoseAndSpeeds (mrpt::poses::CPose2D & curPose, float & curV, float & curW) [inline]
Definition at line 134 of file ReactiveNavigationDemoMain.cpp.
References robotSim().
void CMyReactInterface::notifyHeadingDirection (const double heading_dir_angle) [inline]
Definition at line 178 of file ReactiveNavigationDemoMain.cpp.
void CMyReactInterface::notifyHeadingDirection (const double heading_dir_angle) [inline]
Definition at line 191 of file ReactiveNavigationDemoMain.cpp.
bool CMyReactInterface::senseObstacles (mrpt::slam::CSimplePointsMap & obstacles) [inline]
Definition at line 147 of file ReactiveNavigationDemoMain.cpp.
References gridMap, and robotSim().
bool CMyReactInterface::senseObstacles (mrpt::slam::CSimplePointsMap & obstacles) [inline]
Definition at line 160 of file ReactiveNavigationDemoMain.cpp.
References gridMap, and robotSim().
The documentation for this class was generated from the following files:
AI/Sim/ReactiveNavigationDemoMain.cpp
/home/tallred3/ecen493/SeniorProject/trunk/Code/Simulator/Simulator/ReactiveNavigationDemoMain.cpp