YClops: AbstractPoseEstimator Class Reference
AbstractPoseEstimator Class Reference
#include <PoseEstimator.h>
Public Member Functions
AbstractPoseEstimator ()
virtual ~AbstractPoseEstimator ()
virtual void update (const GPSData *gpsData, const CompassData *compassData, const EncoderData *encoderData)=0
double getYaw (void)
bool getPose (mrpt::poses::CPose3D &pose)
Protected Attributes
mrpt::poses::CPose3D poseEstimate
Detailed Description
Definition at line 15 of file PoseEstimator.h.
Constructor & Destructor Documentation
AbstractPoseEstimator::AbstractPoseEstimator ()
Definition at line 16 of file PoseEstimator.cpp.
AbstractPoseEstimator::~AbstractPoseEstimator () [virtual]
Definition at line 19 of file PoseEstimator.cpp.
Member Function Documentation
bool AbstractPoseEstimator::getPose (mrpt::poses::CPose3D & pose)
Definition at line 22 of file PoseEstimator.cpp.
Referenced by YClopsReactiveNavInterface::getCurrentPoseAndSpeeds().
double AbstractPoseEstimator::getYaw (void) [inline]
Definition at line 27 of file PoseEstimator.h.
References poseEstimate.
Referenced by YClopsReactiveNavInterface::getCurrentPoseAndSpeeds().
virtual void AbstractPoseEstimator::update (const GPSData * gpsData, const CompassData * compassData, const EncoderData * encoderData) [pure virtual]
updates the estimate of the position
Parameters:
yaw - the rotation about the y axis measured in radians
pitch - the rotation about the x axis measured in radians
roll - the rotation about the z axis measured in radians
Implemented in NoFilterPoseEstimator.
Referenced by YClopsReactiveNavInterface::getCurrentPoseAndSpeeds().
Member Data Documentation
mrpt::poses::CPose3D AbstractPoseEstimator::poseEstimate [protected]
Definition at line 30 of file PoseEstimator.h.
Referenced by getYaw(), and NoFilterPoseEstimator::update().
The documentation for this class was generated from the following files:
/home/tallred3/ecen493/SeniorProject/trunk/Code/YClopsLib/inc/PoseEstimator.h
/home/tallred3/ecen493/SeniorProject/trunk/Code/YClopsLib/src/PoseEstimator.cpp