YClops: Compass Class Reference
Compass Class Reference
#include <Compass.h>
Public Member Functions
Compass ()
void loadConfiguration (const mrpt::utils::CConfigFileBase &config, const std::string &sectionName)
void init ()
void sensorProcess ()
SensorData * getData ()
void dumpData (std::ostream &out) const
virtual ~Compass ()
double getYaw () const
double getPitch () const
double getRoll () const
bool isYawValid () const
bool isPitchValid () const
bool isRollValid () const
bool isDegrees () const
Static Public Member Functions
static std::string computeChecksum (const std::string &sentence)
Protected Member Functions
void loadConfig_sensorSpecific (const mrpt::utils::CConfigFileBase &, const std::string &="COMPASS")
Private Member Functions
void parseResponse (const std::string &data)
void reset ()
Private Attributes
bool degrees
double yaw
double pitch
double roll
std::string yawStatus
std::string pitchStatus
std::string rollStatus
mrpt::hwdrivers::CSerialPort serialPort
Detailed Description
Definition at line 20 of file Compass.h.
Constructor & Destructor Documentation
Compass::Compass ()
Definition at line 21 of file Compass.cpp.
Compass::~Compass () [virtual]
Definition at line 62 of file Compass.cpp.
Member Function Documentation
std::string Compass::computeChecksum (const std::string & sentence) [static]
Definition at line 114 of file Compass.cpp.
void Compass::dumpData (std::ostream & out) const
dumps data out to the parameter out
Parameters:
out - the stream to which to write the data
Reimplemented from YClopsSensor.
Definition at line 80 of file Compass.cpp.
References pitch, pitchStatus, roll, rollStatus, yaw, and yawStatus.
Referenced by YClopsReactiveNavInterface::getCurrentPoseAndSpeeds(), and testCompassShowData().
SensorData * Compass::getData () [virtual]
SensorData needs to be allocated on the heap to avoid splicing when we cast it to be a various sensor type
Implements YClopsSensor.
Definition at line 76 of file Compass.cpp.
References degrees, getPitch(), getRoll(), getYaw(), pitchStatus, rollStatus, and yawStatus.
Referenced by YClopsReactiveNavInterface::getCurrentPoseAndSpeeds().
double Compass::getPitch () const [inline]
Returns:
The last received Pitch value in degrees
Definition at line 46 of file Compass.h.
References degrees, and pitch.
Referenced by getData(), main(), and testCompassShowData().
double Compass::getRoll () const [inline]
Returns:
the last received Roll value in degrees
Definition at line 51 of file Compass.h.
References degrees, and roll.
Referenced by getData(), and main().
double Compass::getYaw () const [inline]
Returns:
The last received Yaw value in degrees
Definition at line 41 of file Compass.h.
References degrees, and yaw.
Referenced by getData(), and main().
void Compass::init () [virtual]
initialize the sensor
Implements YClopsSensor.
Definition at line 44 of file Compass.cpp.
References DEBUG3, LOG_COMPASS, and serialPort.
Referenced by YClopsReactiveNavInterface::YClopsReactiveNavInterface().
bool Compass::isDegrees () const [inline]
returns true if the compass was set to output degrees
Definition at line 71 of file Compass.h.
References degrees.
bool Compass::isPitchValid () const [inline]
returns true if the compass returned a valid pitch value
Definition at line 61 of file Compass.h.
References pitchStatus.
Referenced by main().
bool Compass::isRollValid () const [inline]
returns true if the compass returned a valid roll value
Definition at line 66 of file Compass.h.
References rollStatus.
Referenced by main().
bool Compass::isYawValid () const [inline]
returns true if the compass returned a valid yaw value
Definition at line 56 of file Compass.h.
References yawStatus.
Referenced by main().
void Compass::loadConfig_sensorSpecific (const mrpt::utils::CConfigFileBase & , const std::string & = "COMPASS") [protected]
void Compass::loadConfiguration (const mrpt::utils::CConfigFileBase & config, const std::string & sectionName) [virtual]
load sensor specific values from the configuration file
Implements YClopsSensor.
Definition at line 25 of file Compass.cpp.
References DEBUG3, degrees, LOG_COMPASS, and serialPort.
Referenced by YClopsReactiveNavInterface::YClopsReactiveNavInterface().
void Compass::parseResponse (const std::string & data) [private]
parses a response from the HMR3000 Compass Module
Definition at line 87 of file Compass.cpp.
References pitch, pitchStatus, roll, rollStatus, yaw, and yawStatus.
Referenced by sensorProcess().
void Compass::reset () [private]
clears out the data for parsing
Definition at line 105 of file Compass.cpp.
References pitch, pitchStatus, roll, rollStatus, yaw, and yawStatus.
void Compass::sensorProcess () [virtual]
collect data from the sensor and cache it
Implements YClopsSensor.
Definition at line 66 of file Compass.cpp.
References parseResponse(), and serialPort.
Referenced by YClopsReactiveNavInterface::getCurrentPoseAndSpeeds().
Member Data Documentation
bool Compass::degrees [private]
Definition at line 79 of file Compass.h.
Referenced by getData(), getPitch(), getRoll(), getYaw(), isDegrees(), and loadConfiguration().
double Compass::pitch [private]
Definition at line 81 of file Compass.h.
Referenced by dumpData(), getPitch(), parseResponse(), and reset().
std::string Compass::pitchStatus [private]
Definition at line 85 of file Compass.h.
Referenced by dumpData(), getData(), isPitchValid(), parseResponse(), and reset().
double Compass::roll [private]
Definition at line 82 of file Compass.h.
Referenced by dumpData(), getRoll(), parseResponse(), and reset().
std::string Compass::rollStatus [private]
Definition at line 86 of file Compass.h.
Referenced by dumpData(), getData(), isRollValid(), parseResponse(), and reset().
mrpt::hwdrivers::CSerialPort Compass::serialPort [private]
Definition at line 88 of file Compass.h.
Referenced by init(), loadConfiguration(), and sensorProcess().
double Compass::yaw [private]
Definition at line 80 of file Compass.h.
Referenced by dumpData(), getYaw(), parseResponse(), and reset().
std::string Compass::yawStatus [private]
Definition at line 84 of file Compass.h.
Referenced by dumpData(), getData(), isYawValid(), parseResponse(), and reset().
The documentation for this class was generated from the following files:
/home/tallred3/ecen493/SeniorProject/trunk/Code/YClopsLib/inc/Compass.h
/home/tallred3/ecen493/SeniorProject/trunk/Code/YClopsLib/src/Compass.cpp