YClops: Mechanical/WiiDriver/main.cpp File Reference
Mechanical/WiiDriver/main.cpp File Reference
#include <iostream>
#include <stdlib.h>
#include <signal.h>
#include <cassert>
#include "MotorController.h"
#include "MotorCommandInterface.h"
#include "Compass.h"
#include "WiiController.h"
#include "YClopsReactiveNavInterface.h"
#include "YclopsNavigationSystem.h"
#include "Beeper.h"
#include "logging.h"
#include "YClopsConfiguration.h"
#include <mrpt/hwdrivers/CSerialPort.h>
Functions
void signal_handler (int signum)
void shutdown (int exitStatus)
int main (int argc, char **argv)
Variables
bool closing = false
LOG_LEVEL loggingLevel = DEBUG4
YClopsReactiveNavInterface * yclops = NULL
ofstream of
mrpt::reactivenav::YclopsNavigationSystem * ai = NULL
const string DEFAULT_POINTS_FILE = "points.txt"
Function Documentation
int main (int argc, char ** argv)
Definition at line 38 of file main.cpp.
References ai, closing, mrpt::reactivenav::YclopsNavigationSystem::loadConfigFile(), loggingLevel, of, shutdown(), signal_handler(), and yclops.
void shutdown (int exitStatus)
Definition at line 286 of file main.cpp.
References yclops.
Referenced by main(), and signal_handler().
void signal_handler (int signum)
Definition at line 108 of file main.cpp.
References ai, closing, loggingLevel, shutdown(), and yclops.
Referenced by main().
Variable Documentation
mrpt::reactivenav::YclopsNavigationSystem* ai = NULL
Definition at line 35 of file main.cpp.
Referenced by main(), and signal_handler().
bool closing = false
Definition at line 27 of file main.cpp.
Referenced by main(), and signal_handler().
const string DEFAULT_POINTS_FILE = "points.txt"
Definition at line 36 of file main.cpp.
LOG_LEVEL loggingLevel = DEBUG4
Definition at line 31 of file main.cpp.
Referenced by main(), and signal_handler().
ofstream of
Definition at line 34 of file main.cpp.
Referenced by main().
YClopsReactiveNavInterface* yclops = NULL
Definition at line 33 of file main.cpp.
Referenced by main(), shutdown(), and signal_handler().