YClops: Sensors/MultiSensor/main.cpp File Reference
Sensors/MultiSensor/main.cpp File Reference
#include <iostream>
#include <vector>
#include <mrpt/poses/CPoint2D.h>
#include <mrpt/utils/CConfigFile.h>
#include "Compass.h"
#include "GPS.h"
#include "WaypointPlanner.h"
Functions
void initCompass (Compass &compass)
void initGPS (GPS &gps)
int main (int argc, char **argv)
Function Documentation
void initCompass (Compass & compass)
Definition at line 80 of file main.cpp.
Referenced by main().
void initGPS (GPS & gps)
Definition at line 87 of file main.cpp.
References GPS::initConfig(), and GPS::initialize().
Referenced by main().
int main (int argc, char ** argv)
Definition at line 29 of file main.cpp.
References Compass::doProcess(), Compass::getPitch(), Compass::getRoll(), Compass::getYaw(), initCompass(), initGPS(), Compass::isPitchValid(), Compass::isRollValid(), Compass::isYawValid(), AbstractNavigationInterface::LAT, AbstractNavigationInterface::loadPoints(), AbstractNavigationInterface::LON, and AbstractNavigationInterface::solve().